ASFLAGS_ADDITIONAL = -c -g -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -D_RUNONTARGETHARDWARE_BUILD_
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SupportPackages/R2024a/toolbox/target/supportpackages/arduinotarget/registry/..
STACK_SIZE = 64
