function out1 = Cov_diffx_slope(symx,symy,a,b,c,d,e,f,g)
%COV_DIFFX_SLOPE
%    OUT1 = COV_DIFFX_SLOPE(SYMX,SYMY,A,B,C,D,E,F,G)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-Aug-2021 11:51:17

t2 = d.*5.0;
t3 = symx.*5.0;
t4 = -symx;
t5 = -t3;
t6 = e+t4;
t7 = t2+t5;
t8 = t6.*t7;
t9 = tanh(t8);
out1 = a+(pi.*(t9.^2-1.0).*(tan((pi.*(t9+1.0))./4.0).^2+1.0).*(e.*5.0-symx.*1.0e+1+t2))./4.0;
