function symVp = Cov_slope(symx,symy,a,b,c,d,e,f,g)
%COV_SLOPE
%    SYMVP = COV_SLOPE(SYMX,SYMY,A,B,C,D,E,F,G)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-Aug-2021 11:51:17

symVp = c+tan((pi.*(tanh((e-symx).*(d.*5.0-symx.*5.0))+1.0))./4.0)+tan((pi.*(tanh((g-symy).*(f.*5.0-symy.*5.0))+1.0))./4.0)+a.*symx+b.*symy;
