function symVp = Cov_Agent2AgentPotential(symx,symy,symxob,symyob)
%COV_AGENT2AGENTPOTENTIAL
%    SYMVP = COV_AGENT2AGENTPOTENTIAL(SYMX,SYMY,SYMXOB,SYMYOB)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-Aug-2021 16:24:35

symVp = tan((pi.*tanh(sqrt((symx-symxob).^2+(symy-symyob).^2).*1.0e+1+1.0))./4.0).*1.0e+3;
