function out1 = Cov_diffy_Agent2AgentPotential(symx,symy,symxob,symyob)
%COV_DIFFY_AGENT2AGENTPOTENTIAL
%    OUT1 = COV_DIFFY_AGENT2AGENTPOTENTIAL(SYMX,SYMY,SYMXOB,SYMYOB)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-Aug-2021 16:24:36

t2 = -symxob;
t3 = -symyob;
t4 = symx+t2;
t5 = symy+t3;
t6 = t4.^2;
t7 = t5.^2;
t8 = t6+t7;
t9 = sqrt(t8);
t10 = t9.*1.0e+1;
t11 = t10+1.0;
t12 = tanh(t11);
out1 = (pi.*(symy.*2.0-symyob.*2.0).*(t12.^2-1.0).*(tan((t12.*pi)./4.0).^2+1.0).*-1.25e+3)./t9;
