function out1 = Cov_diffx_Agent2ObstaclePotential(symx,symy,symxob,symyob)
%COV_DIFFX_AGENT2OBSTACLEPOTENTIAL
%    OUT1 = COV_DIFFX_AGENT2OBSTACLEPOTENTIAL(SYMX,SYMY,SYMXOB,SYMYOB)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Aug-2021 10:53:18

t2 = symx-symxob;
out1 = -t2.*1.0./((symy-symyob).^2+t2.^2).^(3.0./2.0);
