function symVp = Cov_Agent2ObstaclePotential(symx,symy,symxob,symyob)
%COV_AGENT2OBSTACLEPOTENTIAL
%    SYMVP = COV_AGENT2OBSTACLEPOTENTIAL(SYMX,SYMY,SYMXOB,SYMYOB)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Aug-2021 10:53:18

symVp = 1.0./sqrt((symx-symxob).^2+(symy-symyob).^2);
