function out1 = Cov_diffy_Agent2ObstaclePotential(symx,symy,symxob,symyob)
%COV_DIFFY_AGENT2OBSTACLEPOTENTIAL
%    OUT1 = COV_DIFFY_AGENT2OBSTACLEPOTENTIAL(SYMX,SYMY,SYMXOB,SYMYOB)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Aug-2021 10:53:18

t2 = symy-symyob;
out1 = -t2.*1.0./((symx-symxob).^2+t2.^2).^(3.0./2.0);
