function Cf12 = Cf12est(in1,in2,y,y2,in5,in6)
%Cf12est
%    Cf12 = Cf12est(IN1,IN2,Y,Y2,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/07/26 13:50:32

Rb1_1 = in2(1);
Rb1_2 = in2(4);
Rb1_3 = in2(7);
Rb2_1 = in2(2);
Rb2_2 = in2(5);
Rb2_3 = in2(8);
Rb3_1 = in2(3);
Rb3_2 = in2(6);
Rb3_3 = in2(9);
Re1_1 = in6(1);
Re1_2 = in6(4);
Re1_3 = in6(7);
Re2_1 = in6(2);
Re2_2 = in6(5);
Re2_3 = in6(8);
Re3_1 = in6(3);
Re3_2 = in6(6);
Re3_3 = in6(9);
Rn1_1 = in5(1);
Rn2_1 = in5(2);
Rn3_1 = in5(3);
p1 = in1(1,:);
p2 = in1(2,:);
p3 = in1(3,:);
t2 = Re1_1.*p1;
t3 = Re1_2.*p2;
t4 = Re1_3.*p3;
t5 = Re2_1.*p1;
t6 = Re2_2.*p2;
t7 = Re2_3.*p3;
t8 = Re3_1.*p1;
t9 = Re3_2.*p2;
t10 = Re3_3.*p3;
t11 = t2+t3+t4;
t12 = t5+t6+t7;
t13 = t8+t9+t10;
Cf12 = reshape([t11,t11,t12,t12,t13,t13,Rb1_1,Rb1_1,Rb1_2,Rb1_2,Rb1_3,Rb1_3,Rb2_1,Rb2_1,Rb2_2,Rb2_2,Rb2_3,Rb2_3,Rb3_1,Rb3_1,Rb3_2,Rb3_2,Rb3_3,Rb3_3,Rb1_1.*y,Rb1_1.*Rn1_1.*y2,Rb1_2.*y,Rb1_2.*Rn1_1.*y2,Rb1_3.*y,Rb1_3.*Rn1_1.*y2,0.0,Rb1_1.*Rn2_1.*y2,0.0,Rb1_2.*Rn2_1.*y2,0.0,Rb1_3.*Rn2_1.*y2,0.0,Rb1_1.*Rn3_1.*y2,0.0,Rb1_2.*Rn3_1.*y2,0.0,Rb1_3.*Rn3_1.*y2,Rb2_1.*y,Rb2_1.*Rn1_1.*y2,Rb2_2.*y,Rb2_2.*Rn1_1.*y2,Rb2_3.*y,Rb2_3.*Rn1_1.*y2,0.0,Rb2_1.*Rn2_1.*y2,0.0,Rb2_2.*Rn2_1.*y2,0.0,Rb2_3.*Rn2_1.*y2,0.0,Rb2_1.*Rn3_1.*y2,0.0,Rb2_2.*Rn3_1.*y2,0.0,Rb2_3.*Rn3_1.*y2,Rb3_1.*y,Rb3_1.*Rn1_1.*y2,Rb3_2.*y,Rb3_2.*Rn1_1.*y2,Rb3_3.*y,Rb3_3.*Rn1_1.*y2,0.0,Rb3_1.*Rn2_1.*y2,0.0,Rb3_2.*Rn2_1.*y2,0.0,Rb3_3.*Rn2_1.*y2,0.0,Rb3_1.*Rn3_1.*y2,0.0,Rb3_2.*Rn3_1.*y2,0.0,Rb3_3.*Rn3_1.*y2],[2,39]);
end
