function out1 = Cf2_sens(in1,in2,y,in4,in5)
%Cf2_sens
%    OUT1 = Cf2_sens(IN1,IN2,Y,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/07/12 11:24:09

R_num2_1 = in4(2);
R_num3_1 = in4(3);
p1 = in1(1,:);
p2 = in1(2,:);
p3 = in1(3,:);
qb1 = in2(1,:);
qb2 = in2(2,:);
qb3 = in2(3,:);
qb4 = in2(4,:);
t2 = qb1.*qb2;
t3 = qb1.*qb3;
t4 = qb1.*qb4;
t5 = qb2.*qb3;
t6 = qb2.*qb4;
t7 = qb3.*qb4;
t8 = qb1.^2;
t9 = qb2.^2;
t10 = qb3.^2;
t11 = qb4.^2;
t12 = t2.*2.0;
t13 = t3.*2.0;
t14 = t4.*2.0;
t15 = t5.*2.0;
t16 = t6.*2.0;
t17 = t7.*2.0;
t18 = -t5;
t19 = -t6;
t20 = -t7;
t21 = -t9;
t22 = -t10;
t23 = -t11;
t24 = t2+t7;
t25 = t3+t6;
t26 = t4+t5;
t27 = t2+t20;
t28 = t3+t19;
t29 = t4+t18;
t30 = t8+t11+t21+t22;
t31 = t8+t10+t21+t23;
t32 = t8+t9+t22+t23;
out1 = [p1;p2;p3;t32;-t14+t15;t13+t16;t14+t15;t31;-t12+t17;-t13+t16;t12+t17;t30;R_num2_1.*t32.*y;R_num2_1.*t29.*y.*-2.0;R_num2_1.*t25.*y.*2.0;R_num3_1.*t32.*y;R_num3_1.*t29.*y.*-2.0;R_num3_1.*t25.*y.*2.0;R_num2_1.*t26.*y.*2.0;R_num2_1.*t31.*y;R_num2_1.*t27.*y.*-2.0;R_num3_1.*t26.*y.*2.0;R_num3_1.*t31.*y;R_num3_1.*t27.*y.*-2.0;R_num2_1.*t28.*y.*-2.0;R_num2_1.*t24.*y.*2.0;R_num2_1.*t30.*y;R_num3_1.*t28.*y.*-2.0;R_num3_1.*t24.*y.*2.0;R_num3_1.*t30.*y];
end
