function Cf12 = Cf2D(in1,in2,y,y2,in5)
%Cf2D
%    Cf12 = Cf2D(IN1,IN2,Y,Y2,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/07/19 13:27:18

Rb1_1 = in2(1);
Rb1_2 = in2(3);
Rb2_1 = in2(2);
Rb2_2 = in2(4);
Rn1_1 = in5(1);
Rn2_1 = in5(2);
p1 = in1(1,:);
p2 = in1(2,:);
Cf12 = reshape([p1,p1,p2,p2,Rb1_1,Rb1_1,Rb1_2,Rb1_2,Rb2_1,Rb2_1,Rb2_2,Rb2_2,Rb1_1.*y,Rb1_1.*Rn1_1.*y2,Rb1_2.*y,Rb1_2.*Rn1_1.*y2,0.0,Rb1_1.*Rn2_1.*y2,0.0,Rb1_2.*Rn2_1.*y2,Rb2_1.*y,Rb2_1.*Rn1_1.*y2,Rb2_2.*y,Rb2_2.*Rn1_1.*y2,0.0,Rb2_1.*Rn2_1.*y2,0.0,Rb2_2.*Rn2_1.*y2],[2,14]);
end
