function out1 = Cfa(in1,in2,y,in4)
%Cfa
%    OUT1 = Cfa(IN1,IN2,Y,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/28 17:01:55

p1 = in1(1,:);
p2 = in1(2,:);
p3 = in1(3,:);
qb1 = in2(1,:);
qb2 = in2(2,:);
qb3 = in2(3,:);
qb4 = in2(4,:);
t2 = qb1.*qb2;
t3 = qb1.*qb3;
t4 = qb1.*qb4;
t5 = qb2.*qb3;
t6 = qb2.*qb4;
t7 = qb3.*qb4;
t8 = qb1.^2;
t9 = qb2.^2;
t10 = qb3.^2;
t11 = qb4.^2;
t12 = t2.*2.0;
t13 = t3.*2.0;
t14 = t4.*2.0;
t15 = t5.*2.0;
t16 = t6.*2.0;
t17 = t7.*2.0;
t18 = -t9;
t19 = -t10;
t20 = -t11;
t21 = t8+t11+t18+t19;
t22 = t8+t10+t18+t20;
t23 = t8+t9+t19+t20;
out1 = [p1;p2;p3;t23;-t14+t15;t13+t16;t14+t15;t22;-t12+t17;-t13+t16;t12+t17;t21;t23.*y;y.*(t4-t5).*-2.0;y.*(t3+t6).*2.0;y.*(t4+t5).*2.0;t22.*y;y.*(t2-t7).*-2.0;y.*(t3-t6).*-2.0;y.*(t2+t7).*2.0;t21.*y];
end
