function [A,B] = conic_cfb_sigmoid(in1,in2,in3,k,C)
%CONIC_CFB_SIGMOID
%    [A,B] = CONIC_CFB_SIGMOID(IN1,IN2,IN3,K,C)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/07/15 17:10:56

a1 = in3(1,:);
a2 = in3(2,:);
cableL = in2(:,16);
m = in2(:,1);
ol1 = in1(17,:);
ol2 = in1(18,:);
ol3 = in1(19,:);
pT1 = in1(14,:);
pT2 = in1(15,:);
pT3 = in1(16,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = 1.0./cableL;
t7 = 1.0./m;
t8 = -t3;
t9 = -t4;
t10 = t2+t5+t8+t9;
A = [-pT1.*t6.*t7.*(pT1.*t10-pT3.*(q0.*q2.*2.0+q1.*q3.*2.0))-pT2.*t6.*t7.*(pT2.*t10+pT3.*(q0.*q1.*2.0-q2.*q3.*2.0)),0.0,0.0,0.0];
if nargout > 1
    B = a2.*(-1.0./2.0)+ol1.^2.*pT3+ol2.^2.*pT3+a2./(exp(k.*(a1.*(pT3+cos(C))+ol1.*pT2-ol2.*pT1))+1.0)-a1.*ol1.*pT2+a1.*ol2.*pT1-ol1.*ol3.*pT1-ol2.*ol3.*pT2;
end
end
