function cdo2J = do2J(in1,in2,in3,in4,in5)
%do2J
%    cdo2J = do2J(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    02-Jun-2022 13:17:00

Length = in5(:,16);
V1 = in4(:,1);
ddXd3 = in2(:,11);
ex = in5(:,17);
ey = in5(:,18);
ez = in5(:,19);
gravity = in5(:,6);
m = in5(:,1);
mL = in5(:,15);
o1 = in1(5,:);
o3 = in1(7,:);
ol1 = in1(17,:);
ol2 = in1(18,:);
ol3 = in1(19,:);
pT1 = in1(14,:);
pT2 = in1(15,:);
pT3 = in1(16,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
u3 = in3(3,:);
t2 = m+mL;
t3 = ol1.*pT2;
t4 = ol2.*pT1;
t5 = ol1.*pT3;
t6 = ol3.*pT1;
t7 = ol2.*pT3;
t8 = ol3.*pT2;
t9 = q0.^2;
t10 = q1.^2;
t11 = q2.^2;
t12 = q3.^2;
t13 = -t4;
t14 = -t6;
t15 = -t8;
t16 = 1.0./t2;
t17 = t3+t13;
t18 = t5+t14;
t19 = t7+t15;
t20 = t17.^2;
t21 = t18.^2;
t22 = t19.^2;
t23 = t20+t21+t22;
mt1 = zeros(1,0);
mt2 = [u3-(mL.*(V1+ddXd3+gravity+Length.*m.*pT3.*t16.*t23).*(-ex.*pT3.*t9-ex.*pT3.*t10+ex.*pT3.*t11+ex.*pT3.*t12-ez.*pT1.*t9+ez.*pT1.*t10+ez.*pT1.*t11-ez.*pT1.*t12-ex.*pT1.*q0.*q2.*2.0+ex.*pT1.*q1.*q3.*2.0+ey.*pT1.*q0.*q1.*2.0+ey.*pT1.*q2.*q3.*2.0+ey.*pT3.*q0.*q3.*2.0-ey.*pT3.*q1.*q2.*2.0+ez.*pT3.*q0.*q2.*2.0+ez.*pT3.*q1.*q3.*2.0))./pT3+Length.*m.*mL.*pT3.*t16.*t23.*(-ex.*t9-ex.*t10+ex.*t11+ex.*t12+ey.*q0.*q3.*2.0-ey.*q1.*q2.*2.0+ez.*q0.*q2.*2.0+ez.*q1.*q3.*2.0)+Length.*m.*mL.*pT1.*t16.*t23.*(-ez.*t9+ez.*t10+ez.*t11-ez.*t12-ex.*q0.*q2.*2.0+ex.*q1.*q3.*2.0+ey.*q0.*q1.*2.0+ey.*q2.*q3.*2.0)];
mt3 = [-o1.*o3];
cdo2J = [mt1,mt2,mt3];
