function dP = dQdEu(in1)
%dQdEu
%    dP = dQdEu(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/07/03 15:14:57

eu1 = in1(1,:);
eu2 = in1(2,:);
eu3 = in1(3,:);
t2 = eu1./2.0;
t3 = eu2./2.0;
t4 = eu3./2.0;
t5 = cos(t2);
t6 = cos(t3);
t7 = cos(t4);
t8 = sin(t2);
t9 = sin(t3);
t10 = sin(t4);
t11 = (t8.*t9.*t10)./2.0;
t12 = (t5.*t6.*t7)./2.0;
t13 = (t5.*t6.*t10)./2.0;
t14 = (t5.*t7.*t9)./2.0;
t15 = (t6.*t7.*t8)./2.0;
t16 = (t5.*t9.*t10)./2.0;
t17 = (t6.*t8.*t10)./2.0;
t18 = (t7.*t8.*t9)./2.0;
t19 = -t13;
t20 = -t14;
t21 = -t15;
t22 = -t16;
t23 = -t17;
t24 = -t18;
t25 = t11+t12;
t26 = t20+t23;
dP = reshape([t16+t21,t25,t13+t24,t26,t17+t20,t19+t24,-t11+t12,t21+t22,t18+t19,t26,t15+t22,t25],[4,3,size(in1,2)]);
end
