function [fun, Eval] = FunctionOpt(type, agent, params, ind, U)
%UNTITLED この関数の概要をここに記述
%   詳細説明をここに記述
    % 評価関数をまとめている関数
    ref_monte = agent.reference.result.state;
    % 重み
    PQ_monte = params.PQ_monte;
    VQ_monte = params.VQ_monte;
    WQ_monte = params.WQ_monte;
    QQ_monte = params.QQ_monte;
    R_monte = params.R_monte;
    ref_input = params.ref_input;
    
    % 評価関数
%     FuncArray = cell(10, 1);
    FuncArray{1,1} = @(p_monte, u_monte) (p_monte - ref_monte.p)'*PQ_monte*(p_monte - ref_monte.p)...
            +(u_monte - ref_input)'*R_monte*(u_monte - ref_input); 
    FuncArray{2,1} = @(p_monte, v_monte) (p_monte - ref_monte.p)'*PQ_monte*(p_monte - ref_monte.p)+v_monte'*VQ_monte*v_monte;
    FuncArray{3,1} = 0;
    FuncArray{4,1} = @(p_monte, q_monte, v_monte, w_monte) ...
            (p_monte - ref_monte.p)'*PQ_monte*(p_monte - ref_monte.p)...
            +v_monte'*VQ_monte*v_monte...
            +w_monte'*WQ_monte*w_monte...
            +q_monte'*QQ_monte*q_monte; 
      FuncArray{5,1} = 0;
%     FuncArray{5,1} = @(p_monte, q_monte, v_monte, w_monte, u_monte) ...
%             (p_monte - ref_monte.p)'*PQ_monte*(p_monte - ref_monte.p)...
%             +v_monte'*VQ_monte*v_monte...
%             +w_monte'*WQ_monte*w_monte...
%             +q_monte'*QQ_monte*q_monte...
%             +u_monte'*R_monte*u_monte; 
      FuncArray{6,1} = 0;
%     FuncArray{6,1} = @(p_monte, q_monte, v_monte, w_monte, udiff_monte) ...
%             (p_monte - ref_monte.p)'*PQ_monte*(p_monte - ref_monte.p)...
%             +v_monte'*VQ_monte*v_monte...
%             +w_monte'*WQ_monte*w_monte...
%             +q_monte'*QQ_monte*q_monte...
%             +udiff_monte'*UdiffQ_monte*udiff_monte; 
    FuncArray{7,1} = @(p_monte, q_monte, v_monte, w_monte, u_monte) ...
            (p_monte - ref_monte.p)'*PQ_monte*(p_monte - ref_monte.p)...
            +v_monte'*VQ_monte*v_monte...
            +w_monte'*WQ_monte*w_monte...
            +q_monte'*QQ_monte*q_monte...
            +(u_monte - ref_input)'*R_monte*(u_monte - ref_input);
    fun = FuncArray{type};
    Evaluation{1,1} = fun(params.P_monte(ind, :)', U);
    Evaluation{2,1} = fun(params.P_monte(ind, :)', params.V_monte(ind, :)');
    Evaluation{3,1} = 0;
    Evaluation{4,1} = fun(params.P_monte(ind, :)', params.Q_monte(ind, :)', params.V_monte(ind, :)', params.W_monte(ind, :)') ;
    Evaluation{5,1} = 0;
    Evaluation{6,1} = 0;
    Evaluation{7,1} = fun(params.P_monte(ind, :)', params.Q_monte(ind, :)', params.V_monte(ind, :)', params.W_monte(ind, :)', U);
    Eval = Evaluation{type};
end

