function gen_controller_entity_func()
arguments
end
fileID = fopen("@CONTROLLER_SYSTEM/stepImpl_entity.m",'w');
str0 = "function result = stepImpl_entity(obj,x,xd)\n"+...
"%% generated using gen_controller_entity_func.m\n"+...
"%% generated at : " + string(datetime("today")) +"\n"+...
"%% [Input]\n%% x : 13 state [q p v w] \n"+...
"%% xd : 20 reference [xd yd zd yawd; dxd dyd ..; ddxd ddyd ..; ..]\n"+...
"%% [Output]\n%% u : 4 inputs [total thrust force; 3 torques]\n";

str1 = "Rb0 = RodriguesQuaternion(Eul2Quat([0;0;xd(4,1)]));\n"+...
"p = x(5:7,1);\n"+...
"q = x(1:4,1);\n"+...
"v = x(8:10,1);\n"+...
"w = x(11:13,1);\n"+...
"x = [R2q(Rb0'*RodriguesQuaternion(q));Rb0'*p;Rb0'*v;Rb0'*w];\n"+...
"xd(1:3)=Rb0'*xd(1:3);\n"+...
"xd(4) = 0;\n"+...
"xd(5:7)=Rb0'*xd(5:7);\n"+...
"xd(9:11)=Rb0'*xd(9:11);\n"+...
"xd(13:15)=Rb0'*xd(13:15);\n"+...
"xd(17:19)=Rb0'*xd(17:19);\n"+...
"vf = Vfd(obj.dt,x,xd',obj.param.P,obj.param.F1);\n"+...
"vs = Vsd(obj.dt,x,xd',vf,obj.param.P,obj.param.F2,obj.param.F3,obj.param.F4);\n"+...
"tmp = Uf(x,xd',vf,obj.param.P) + Us(x,xd',vf,vs',obj.param.P);\n"+...
"%% max,min are applied for the safty\n"+...
"obj.result.input = [max(0,min(10,tmp(1)));max(-1,min(1,tmp(2)));max(-1,min(1,tmp(3)));max(-1,min(1,tmp(4)))];\n"+...
"result = obj.result;\nend";
str = str0 + str1;
fprintf(fileID, str); 
fclose(fileID);
end