function H234 = H234_SuspendedLoadxyDst(in1,in2,in3,in4)
%H234_SuspendedLoadxyDst
%    H234 = H234_SuspendedLoadxyDst(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025/03/05 18:29:17

H234 = reshape([0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,3]);
end
