function [x,fval,exitflag,output,lambda,grad,hessian] = fminconMEX_AUTOGEN(x0,obj)
	assert(isa(x0,	'double'));		assert(all(size(x0)==	[7,11]));
	assert(isa(obj,	'TrackingMPC_Controller'));		assert(all(size(obj)==	[1,1]));
    options = optimoptions('fmincon',...
        'MaxIterations',                 Inf,...
        'MaxFunctionEvaluations',        1000000000000,...
        'ConstraintTolerance',           0.001,...
        'OptimalityTolerance',           1e-06,...
        'StepTolerance',                 1e-06,...
        'SpecifyObjectiveGradient',      false,...
        'SpecifyConstraintGradient',     false,...
        'Algorithm',                     'sqp');
    % 最大反復回数, 評価関数の最大値, 制約の許容誤差, 最適性の許容誤差, ステップサイズの下限, 評価関数の勾配設定, 制約条件の勾配設定, SQPアルゴリズムの指定
    evalfunc =                                                      @(x)obj.objectiveFim(x,obj.param);
    nonlcon  =                                                      @(x)obj.constraintsOM(x,obj.param);
    [x,fval,exitflag,output,lambda,grad,hessian] = fmincon(evalfunc,x0,[],[],[],[],[],[],nonlcon,options);
end