function Vd1 = Vfd_SuspendedLoadxyDst(dt,in2,in3,in4)
%Vfd_SuspendedLoadxyDst
%    Vd1 = Vfd_SuspendedLoadxyDst(DT,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025/03/05 19:25:46

Xd3 = in3(:,3);
dXd3 = in3(:,7);
dpl3 = in2(13,:);
f11 = in4(:,1);
f12 = in4(:,2);
pl3 = in2(10,:);
t2 = dt.*f12;
t3 = dt.^2;
t4 = -dpl3;
t5 = -pl3;
t6 = dXd3+t4;
t7 = Xd3+t5;
t8 = t2-1.0;
t9 = (f11.*t3)./2.0;
t10 = (dt.*t2)./2.0;
t11 = t8.^2;
t12 = -t10;
t13 = dt.*f11.*t8;
t15 = t9-1.0;
t14 = dt+t12;
t16 = t15.^2;
t17 = dt.*f11.*t15;
t18 = dt.*f11.*t14;
t20 = t8.*t14;
t21 = t14.*t15;
t22 = t13+t17;
t19 = -t18;
t27 = t20+t21;
t23 = t11+t19;
t25 = t16+t19;
t30 = t22.*t27;
t24 = t23.^2;
t26 = t25.^2;
t28 = t22.*t23;
t29 = t22.*t25;
t31 = t23.*t27;
t32 = -t30;
t33 = t25.*t27;
t34 = t24+t32;
t35 = t26+t32;
t36 = t28+t29;
t37 = t31+t33;
Vd1 = [f11.*t7+f12.*t6,-t7.*(f11.*t2+f11.*t15)-t6.*(f12.*t8-f11.*t14),t7.*(f12.*t22+f11.*t25)+t6.*(f12.*t23-f11.*t27),-t7.*(f12.*(t8.*t22+dt.*f11.*t25)-f11.*(t14.*t22-t15.*t25))-t6.*(f12.*(t8.*t23-dt.*f11.*t27)-f11.*(t14.*t23+t15.*t27)),t6.*(f12.*t34-f11.*t37)+t7.*(f11.*t35+f12.*t36),-t6.*(f12.*(t8.*t34-dt.*f11.*t37)-f11.*(t14.*t34+t15.*t37))-t7.*(f12.*(t8.*t36+dt.*f11.*t35)-f11.*(t14.*t36-t15.*t35))];
end
