function cZep3 = Zep3(in1,in2,in3)
%Zep3
%    cZep3 = Zep3(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/20 15:03:28

T1 = in1(14,:);
Xd2 = in2(:,2);
dT1 = in1(15,:);
dXd2 = in2(:,6);
ddXd2 = in2(:,10);
dddXd2 = in2(:,14);
dp2 = in1(9,:);
m = in3(:,1);
o1 = in1(11,:);
o2 = in1(12,:);
o3 = in1(13,:);
p2 = in1(6,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = q0.*q1.*2.0;
t3 = q2.*q3.*2.0;
t4 = 1.0./m;
t5 = -t3;
t6 = t2+t5;
cZep3 = [-Xd2+p2;-dXd2+dp2;-ddXd2-T1.*t4.*t6;-dddXd2-dT1.*t4.*t6-T1.*q0.*t4.*((o1.*q0)./2.0-(o2.*q3)./2.0+(o3.*q2)./2.0).*2.0+T1.*q2.*t4.*(o1.*q2.*(-1.0./2.0)+(o2.*q1)./2.0+(o3.*q0)./2.0).*2.0+T1.*q1.*t4.*((o1.*q1)./2.0+(o2.*q2)./2.0+(o3.*q3)./2.0).*2.0+T1.*q3.*t4.*((o2.*q0)./2.0+(o1.*q3)./2.0-(o3.*q1)./2.0).*2.0];
end
