function [A,B] = conic_cfb(in1,in2,in3,C)
%CONIC_CFB
%    [A,B] = CONIC_CFB(IN1,IN2,IN3,C)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/07/09 17:41:51

a1 = in3(1,:);
a2 = in3(2,:);
cableL = in2(:,16);
m = in2(:,1);
ol1 = in1(17,:);
ol2 = in1(18,:);
ol3 = in1(19,:);
pT1 = in1(14,:);
pT2 = in1(15,:);
pT3 = in1(16,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = 1.0./cableL;
t7 = 1.0./m;
t8 = -t3;
t9 = -t4;
t10 = t2+t5+t8+t9;
A = [-pT1.*t6.*t7.*(pT1.*t10-pT3.*(q0.*q2.*2.0+q1.*q3.*2.0))-pT2.*t6.*t7.*(pT2.*t10+pT3.*(q0.*q1.*2.0-q2.*q3.*2.0)),0.0,0.0,0.0];
if nargout > 1
    B = ol1.^2.*pT3+ol2.^2.*pT3-a1.*a2.*pT3-a1.*ol1.*pT2+a1.*ol2.*pT1-a2.*ol1.*pT2+a2.*ol2.*pT1-ol1.*ol3.*pT1-ol2.*ol3.*pT2-a1.*a2.*cos(C);
end
end
