function U1 = Uf_SuspendedLoad(in1,in2,in3,in4)
%Uf_SuspendedLoad
%    U1 = Uf_SuspendedLoad(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/06/28 16:37:52

V1 = in3(:,1);
cableL = in4(:,7);
d2Xd3 = in2(:,11);
gravity = in4(:,5);
m = in4(:,1);
mL = in4(:,6);
ol1 = in1(17,:);
ol2 = in1(18,:);
ol3 = in1(19,:);
pT1 = in1(14,:);
pT2 = in1(15,:);
pT3 = in1(16,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = m+mL;
U1 = [(t2.*(V1+d2Xd3+gravity+(cableL.*m.*pT3.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./t2))./(pT3.*(pT3.*q0.^2-pT3.*q1.^2-pT3.*q2.^2+pT3.*q3.^2+pT1.*q0.*q2.*2.0-pT2.*q0.*q1.*2.0+pT1.*q1.*q3.*2.0+pT2.*q2.*q3.*2.0));0.0;0.0;0.0];
end
