function V1 = Vf_SuspendedLoadxyDst(in1,in2,in3)
%Vf_SuspendedLoadxyDst
%    V1 = Vf_SuspendedLoadxyDst(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025/03/05 19:25:46

Xd3 = in2(:,3);
dXd3 = in2(:,7);
dpl3 = in1(13,:);
f11 = in3(:,1);
f12 = in3(:,2);
pl3 = in1(10,:);
t2 = f11.*f12;
t3 = f11.^2;
t4 = f12.^2;
t5 = -dpl3;
t6 = -pl3;
t7 = f12.*t2;
t8 = f11.*t2;
t10 = -t4;
t11 = dXd3+t5;
t12 = Xd3+t6;
t13 = -t7;
t14 = f11+t10;
t15 = t14.^2;
t16 = f12.*t14;
t17 = t2.*t14;
t19 = t2+t16;
t22 = t8+t17;
t25 = -f12.*(t7-t15);
t21 = f11.*t19;
t24 = f12.*t22;
t27 = t21+t25;
V1 = [f11.*t12+f12.*t11,-t2.*t12+t11.*t14,-t12.*(t3+t13)-t11.*t19,-t11.*(f11.*t14-f12.*t19)+t12.*(t8+f12.*(t3+t13)),t11.*t27-t12.*(t24-f11.*(t3+t13)),-t12.*(f11.*t22-f12.*(t24-f11.*(t3+t13)))-t11.*(f12.*t27+f11.*(t7-t15))];
end
