function cZ1 = Z1_SuspendedLoad(in1,in2,in3)
%Z1_SuspendedLoad
%    cZ1 = Z1_SuspendedLoad(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025/02/10 17:15:55

Xd3 = in2(:,3);
dXd3 = in2(:,7);
dpl3 = in1(13,:);
pl3 = in1(10,:);
cZ1 = [-Xd3+pl3;-dXd3+dpl3];
end
