function Odot = Odot11_12(in1,in2)
%Odot11_12
%    Odot = Odot11_12(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/16 20:41:38

x4 = in1(4,:);
x5 = in1(5,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(x4);
t5 = sin(x5);
t6 = 1.0./t3.^2;
Odot = (t2+t2.*t5.^2.*t6).*(t2.*x11-t4.*x12)-t4.*t5.*t6.*(t3.*x10+t2.*t5.*x12+t4.*t5.*x11);
end
