function Odot = Odot12_11(in1,in2)
%Odot12_11
%    Odot = Odot12_11(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/16 20:41:38

x4 = in1(4,:);
x5 = in1(5,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = cos(x5);
t3 = sin(x4);
t4 = sin(x5);
Odot = -(t3.*(t2.*x10+t4.*x12.*cos(x4)+t3.*t4.*x11))./t2;
end
