function Odot = Odot19_12(in1,in2)
%Odot19_12
%    Odot = Odot19_12(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/16 20:53:08

u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(x4);
t5 = sin(x5);
t6 = t3.*x10;
t7 = t2.*x11;
t8 = t2.*x12;
t9 = t4.*x11;
t10 = t4.*x12;
t11 = 1.0./t3;
t12 = t11.^2;
t13 = t5.*t8;
t14 = t5.*t9;
t15 = -t10;
t16 = t8+t9;
t17 = t7+t15;
t18 = t6+t13+t14;
Odot = t2.*u2.*(-5.0e+1./3.0)-t17.*(t2.*t16+t2.*t11.*(t3.*t8+t3.*t9-t5.*x10)+t2.*t5.*t12.*t18+t2.*t5.^2.*t12.*t16)-t11.*t18.*(t2.*t11.*(t5.*t7+t5.*t15)-t4.*t11.*t18+t2.*t5.*t11.*t17-t4.*t5.*t11.*t16)-t2.^2.*t5.*t11.*u4.*(1.0e+2./3.0)-t2.*t4.*t5.*t11.*u3.*(1.0e+2./3.0);
end
