function Odot = Odot13_5(in1,in2)
%Odot13_5
%    Odot = Odot13_5(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/16 20:41:39

u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(x4);
t5 = sin(x5);
t6 = t2.*x11;
t7 = t2.*x12;
t8 = t4.*x11;
t9 = t4.*x12;
t10 = 1.0./t3.^2;
t11 = 1.0./t3.^3;
t12 = -t9;
t13 = t7+t8;
t14 = t6+t12;
Odot = t14.*(t13./t3+t5.^2.*t11.*t13.*2.0)+t2.*t5.*t10.*u4.*(5.0e+1./3.0)+t4.*t5.*t10.*u3.*(5.0e+1./3.0)+t5.*t11.*t14.*(t5.*t7+t5.*t8+t3.*x10);
end
