function Odot = Odot11_5(in1,in2)
%Odot11_5
%    Odot = Odot11_5(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/16 20:41:37

u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(x4);
t5 = sin(x5);
t6 = t5.^2;
t7 = t3.*x10;
t8 = 1.0./t3;
t10 = t2.*t5.*x12;
t11 = t4.*t5.*x11;
t9 = t8.^2;
t12 = t7+t10+t11;
Odot = (t6.*t8.^3.*t12.*2.0+t5.*t9.*(-t5.*x10+t2.*t3.*x12+t3.*t4.*x11).*2.0).*(t2.*x11-t4.*x12)+u4.*(t2.*(5.0e+1./3.0)+t2.*t6.*t9.*(5.0e+1./3.0))+u3.*(t4.*(5.0e+1./3.0)+t4.*t6.*t9.*(5.0e+1./3.0))+t8.*t12.*(t8.*(t2.*t3.*x11-t3.*t4.*x12)+t5.*t9.*(t2.*t5.*x11-t4.*t5.*x12));
end
