function [h1,h2] = conic_cfb_x3_h1h2(in1,in2,in3,in4,C)
%CONIC_CFB_X3_H1H2
%    [H1,H2] = CONIC_CFB_X3_H1H2(IN1,IN2,IN3,IN4,C)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/07/16 18:32:37

a1 = in4(1,:);
a2 = in4(2,:);
cableL = in3(:,16);
f = in2(1,:);
m = in3(:,1);
ol1 = in1(17,:);
ol2 = in1(18,:);
ol3 = in1(19,:);
pT1 = in1(14,:);
pT2 = in1(15,:);
pT3 = in1(16,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = cos(C);
t3 = ol1.*pT2;
t4 = ol2.*pT1;
t5 = q0.^2;
t6 = q1.^2;
t7 = q2.^2;
t8 = q3.^2;
t10 = 1.0./cableL;
t11 = 1.0./m;
t9 = pT3+t2;
t12 = -t4;
t13 = -t6;
t14 = -t7;
t15 = a1.*t9;
h1 = -t3+t4-t15;
if nargout > 1
    t16 = t5+t8+t13+t14;
    h2 = -a1.*(t3+t12)+ol1.*(ol1.*pT3-ol3.*pT1)+ol2.*(ol2.*pT3-ol3.*pT2)-a2.*(t3+t12+t15).^3+f.*pT1.*t10.*t11.*(pT1.*t16-pT3.*(q0.*q2.*2.0+q1.*q3.*2.0))+f.*pT2.*t10.*t11.*(pT2.*t16+pT3.*(q0.*q1.*2.0-q2.*q3.*2.0));
end
end
