function [A,B] = conic_cfb_eul(in1,in2,in3,C)
%CONIC_CFB_EUL
%    [A,B] = CONIC_CFB_EUL(IN1,IN2,IN3,C)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/07/12 20:52:58

a1 = in3(1,:);
a2 = in3(2,:);
cableL = in2(:,16);
m = in2(:,1);
ol1 = in1(16,:);
ol2 = in1(17,:);
ol3 = in1(18,:);
pT1 = in1(13,:);
pT2 = in1(14,:);
pT3 = in1(15,:);
pitch = in1(2,:);
roll = in1(1,:);
yaw = in1(3,:);
t2 = 1.0./cableL;
t3 = 1.0./m;
t4 = pitch./2.0;
t5 = roll./2.0;
t6 = yaw./2.0;
t7 = cos(t4);
t8 = cos(t5);
t9 = cos(t6);
t10 = sin(t4);
t11 = sin(t5);
t12 = sin(t6);
t13 = t7.^2;
t14 = t8.^2;
t19 = t7.*t8.*t9;
t20 = t7.*t8.*t12;
t21 = t7.*t9.*t11;
t22 = t8.*t9.*t10;
t23 = t7.*t11.*t12;
t24 = t8.*t10.*t12;
t25 = t9.*t10.*t11;
t26 = t10.*t11.*t12;
t15 = t13.*2.0;
t16 = t14.*2.0;
t27 = -t24;
t28 = -t25;
t29 = t19+t26;
t30 = t22+t23;
t17 = t15-1.0;
t18 = t16-1.0;
t31 = t20+t28;
t32 = t21+t27;
A = [pT1.*t2.*t3.*(pT3.*(t29.*t30.*2.0+t31.*t32.*2.0)-pT1.*t17.*t18)-pT2.*t2.*t3.*(pT3.*(t29.*t32.*2.0-t30.*t31.*2.0)+pT2.*t17.*t18),0.0,0.0,0.0];
if nargout > 1
    B = ol1.^2.*pT3+ol2.^2.*pT3-a1.*a2.*pT3-a1.*ol1.*pT2+a1.*ol2.*pT1-a2.*ol1.*pT2+a2.*ol2.*pT1-ol1.*ol3.*pT1-ol2.*ol3.*pT2-a1.*a2.*cos(C);
end
end
