function [h1,h2] = conic_cfb_eul_h1h2(in1,in2,in3,in4,C)
%CONIC_CFB_EUL_H1H2
%    [H1,H2] = CONIC_CFB_EUL_H1H2(IN1,IN2,IN3,IN4,C)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/07/15 20:40:25

a1 = in4(1,:);
a2 = in4(2,:);
cableL = in3(:,16);
f = in2(1,:);
m = in3(:,1);
ol1 = in1(16,:);
ol2 = in1(17,:);
ol3 = in1(18,:);
pT1 = in1(13,:);
pT2 = in1(14,:);
pT3 = in1(15,:);
pitch = in1(2,:);
roll = in1(1,:);
yaw = in1(3,:);
t2 = cos(C);
t3 = ol1.*pT2;
t4 = ol2.*pT1;
h1 = -t3+t4-a1.*(pT3+t2);
if nargout > 1
    t5 = 1.0./cableL;
    t6 = 1.0./m;
    t8 = pitch./2.0;
    t9 = roll./2.0;
    t10 = yaw./2.0;
    t7 = -t4;
    t11 = cos(t8);
    t12 = cos(t9);
    t13 = cos(t10);
    t14 = sin(t8);
    t15 = sin(t9);
    t16 = sin(t10);
    t17 = t11.^2;
    t18 = t12.^2;
    t23 = t11.*t12.*t13;
    t24 = t11.*t12.*t16;
    t25 = t11.*t13.*t15;
    t26 = t12.*t13.*t14;
    t27 = t11.*t15.*t16;
    t28 = t12.*t14.*t16;
    t29 = t13.*t14.*t15;
    t30 = t14.*t15.*t16;
    t19 = t17.*2.0;
    t20 = t18.*2.0;
    t31 = -t28;
    t32 = -t29;
    t33 = t23+t30;
    t34 = t26+t27;
    t21 = t19-1.0;
    t22 = t20-1.0;
    t35 = t24+t32;
    t36 = t25+t31;
    h2 = -a1.*(t3+t7)-a2.*(t3+t7+a1.*pT3+a1.*t2)+ol1.*(ol1.*pT3-ol3.*pT1)+ol2.*(ol2.*pT3-ol3.*pT2)-f.*pT1.*t5.*t6.*(pT3.*(t33.*t34.*2.0+t35.*t36.*2.0)-pT1.*t21.*t22)+f.*pT2.*t5.*t6.*(pT3.*(t33.*t36.*2.0-t34.*t35.*2.0)+pT2.*t21.*t22);
end
end
