function [A,B] = conic_q_cfb(in1,in2,in3,C,Cq)
%CONIC_Q_CFB
%    [A,B] = CONIC_Q_CFB(IN1,IN2,IN3,C,Cq)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/07/16 20:11:50

a1 = in3(1,:);
a2 = in3(2,:);
cableL = in2(:,16);
jx = in2(:,3);
jy = in2(:,4);
jz = in2(:,5);
m = in2(:,1);
o1 = in1(5,:);
o2 = in1(6,:);
o3 = in1(7,:);
ol1 = in1(17,:);
ol2 = in1(18,:);
ol3 = in1(19,:);
pT1 = in1(14,:);
pT2 = in1(15,:);
pT3 = in1(16,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = o1.^2;
t3 = o2.^2;
t4 = q0.^2;
t5 = q1.^2;
t6 = q2.^2;
t7 = q3.^2;
t8 = q0.*q1.*2.0;
t9 = q0.*q2.*2.0;
t10 = q1.*q3.*2.0;
t11 = q2.*q3.*2.0;
t12 = 1.0./cableL;
t13 = 1.0./jx;
t14 = 1.0./jy;
t15 = 1.0./m;
t16 = -t5;
t17 = -t6;
t18 = t4+t7+t16+t17;
A = [pT1.*t12.*t15.*(pT3.*(t9+t10)-pT1.*t18)-pT2.*t12.*t15.*(pT2.*t18+pT3.*(t8-t11)),t13.*(t8+t11),t14.*(t9-t10),0.0];
if nargout > 1
    et1 = -t2.*t4+t2.*t5-t3.*t4+t2.*t6+t3.*t5-t2.*t7+t3.*t6-t3.*t7+ol1.^2.*pT3+ol2.^2.*pT3-a1.*a2.*pT3+a1.*a2.*t4+a1.*a2.*t7+a1.*a2.*t16+a1.*a2.*t17-a1.*ol1.*pT2+a1.*ol2.*pT1-a2.*ol1.*pT2+a2.*ol2.*pT1+a1.*o2.*t10+a2.*o2.*t10-ol1.*ol3.*pT1-ol2.*ol3.*pT2+o2.*o3.*t8+o1.*o3.*t10+o2.*o3.*t11-a1.*a2.*cos(C)-a1.*a2.*cos(Cq)-a1.*o1.*q0.*q1.*2.0-a2.*o1.*q0.*q1.*2.0-a1.*o2.*q0.*q2.*2.0-a2.*o2.*q0.*q2.*2.0-a1.*o1.*q2.*q3.*2.0-a2.*o1.*q2.*q3.*2.0-o1.*o3.*q0.*q2.*2.0+jx.*o1.*o3.*t9.*t14+jz.*o2.*o3.*t8.*t13+jz.*o1.*o3.*t10.*t14;
    et2 = jz.*o2.*o3.*t11.*t13-jx.*o1.*o3.*q1.*q3.*t14.*2.0-jy.*o2.*o3.*q0.*q1.*t13.*2.0-jy.*o2.*o3.*q2.*q3.*t13.*2.0-jz.*o1.*o3.*q0.*q2.*t14.*2.0;
    B = et1+et2;
end
end
