function [h1,h2] = conic_cfb_x3(in1,in2,in3,C)
%CONIC_CFB_X3
%    [H1,H2] = CONIC_CFB_X3(IN1,IN2,IN3,C)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/07/16 18:40:32

a1 = in3(1,:);
a2 = in3(2,:);
cableL = in2(:,16);
m = in2(:,1);
ol1 = in1(17,:);
ol2 = in1(18,:);
ol3 = in1(19,:);
pT1 = in1(14,:);
pT2 = in1(15,:);
pT3 = in1(16,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = ol1.*pT2;
t3 = ol2.*pT1;
t4 = q0.^2;
t5 = q1.^2;
t6 = q2.^2;
t7 = q3.^2;
t8 = 1.0./cableL;
t9 = 1.0./m;
t10 = -t3;
t11 = -t5;
t12 = -t6;
t13 = t4+t7+t11+t12;
h1 = [-pT1.*t8.*t9.*(pT1.*t13-pT3.*(q0.*q2.*2.0+q1.*q3.*2.0))-pT2.*t8.*t9.*(pT2.*t13+pT3.*(q0.*q1.*2.0-q2.*q3.*2.0)),0.0,0.0,0.0];
if nargout > 1
    h2 = -a1.*(t2+t10)-a2.*(t2+t10+a1.*(pT3+cos(C))).^3+ol1.*(ol1.*pT3-ol3.*pT1)+ol2.*(ol2.*pT3-ol3.*pT2);
end
end
