function out1 = Jacobian_load_model(in1,p1)
%Jacobian_load_model
%    OUT1 = Jacobian_load_model(IN1,P1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/10/07 18:43:57

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[7,7]);
end
