function dx = load_model(in1,in2,g)
%LOAD_MODEL
%    DX = LOAD_MODEL(IN1,IN2,G)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/10/07 18:42:41

mL = in1(7,:);
mu1 = in2(1,:);
mu2 = in2(2,:);
mu3 = in2(3,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
t2 = 1.0./mL;
dx = [v1;v2;v3;mu1.*t2;mu2.*t2;-g+mu3.*t2;0.0];
end
