function [E,E2,W] = make_grid_graph(nx,ny,gen,maxv)
% Make a graph for nx-ny grid with weight generated by gen
% gen(x,y) generates weight at (x,y)
%   high value means high possibility to burn
%   gen must work with matrix arguments,that is x or y possible to choose as
%   a matrix.
% maxv : max probability 
% E : edge matrix : N-N size matrix where N = nx*ny
% eij : (i,j) element of E
% eij > 0 if edge exists from j to i else eij = 0
% W : weight matrix : nx-ny size matrix
arguments
    nx
    ny
    gen
    maxv = 1
end
N = nx*ny;
[X,Y]=meshgrid(1:nx,1:ny);
% W = gen(X,Y);
gen=0.01;
A = zeros(nx,ny);
A = A + 0.00001;
Wm = gen*8; Wmp = gen*8; Sm = gen*2; RCm = gen*0.8;
%糸魚川市模擬マップ
%A area
A(4:8,54)=Wm;A(5:8,55:56)=Wm;A(9,53:55)=Wm;A(10,49:55)=Wm;A(11,49:56)=Wm;A(12:18,49:55)=Wm;A(12,53)=0;A(19:20,52:54)=Wm;A(19:20,49:51)=Sm;A(21:27,49:54)=Wm;A(25:26,51)=0;A(28,49:50)=Wm;A(29:30,50)=Wm;A(28:30,52:54)=Wm;
A(4:5,49)=Sm;A(4:5,50:52)=Wm;A(6:8,49:50)=Wm;A(6,51)=Wm;A(8:9,51)=Wm;A(6:9,52)=Wmp;A(4:8,53)=Wmp;
%B area
A(11,59)=Wm;A(14:17,57)=Wm;A(13:17,58)=Wm;A(12:17,59:62)=Wm;A(16,62)=0;A(18,59:64)=Wm;A(19,58:63)=Wm;A(20:21,57:64)=Wm;A(22:23,58:64)=Wm;A(24:25,57:60)=Wm;A(24:25,63:64)=Wm;A(26,57:59)=Wm;A(27,58:61)=Wm;A(25:27,62)=Wm;A(26:28,63)=Wm;A(28:30,56:59)=Wm;A(14:16,63:68)=RCm;A(15:16,69)=RCm;A(17:21,66:68)=RCm;A(22:23,66:67)=RCm;
A(10:12,63)=Sm;A(8:12,64:69)=Sm;A(13,66:68)=Sm;A(6:8,58)=Sm;A(5:8,59)=Sm;A(10,58:59)=Wmp;A(5:10,60)=Wm;A(6:7,61)=Wm;A(8:10,61)=Sm;A(6:10,62)=Sm;
%C area
A(34:40,49:53)=Wm;A(36,49)=0;A(44:52,51:53)=Wm;A(43,52:53)=Wm;A(41,49:52)=Sm;A(42,49:53)=Sm;A(43:51,49:50)=RCm;A(34,55:61)=Wm;A(35,54:59)=Wm;A(36,55:58)=Wm;A(37,57:58)=Wm;A(35:36,60:63)=Wm;A(37,60:62)=Wm;A(38,60)=Wm;A(39,60:61)=Sm;A(38:39,62)=Wm;A(38:45,55:58)=Wm;A(41,60)=Wm;A(42,60:61)=Wm;A(43:45,59:60)=Wm;A(46:52,54:60)=Wm;A(48,54)=0;A(47,59)=0;
A(44:51,64:66)=RCm;A(42:43,67)=Wm;A(36:43,68)=Wm;A(47:51,67:68)=Wm;A(40:51,69)=Wm;A(37:43,70)=Wm;A(48:51,70)=Wm;A(52,67:72)=Wm;A(35:39,71:72)=Wm;A(37,71)=0;A(35:38,73)=RCm;A(40:51,71:73)=Wm;   A(41:43,76:77)=Wm;A(42:43,78:82)=Wm;A(44:52,79:82)=Wm;
A(41:43,76:77)=Wm;A(42:43,78:84)=Wm;A(44:50,79:84)=Wm;A(51:52,79:83)=Wm;A(46:52,85:88)=Wm;A(45,85:87)=Wm;A(46:47,89)=Wm;A(36:44,87)=Wm;A(36:42,88)=Wm;A(37:42,89:90)=Wm;A(35:40,77)=Wmp;A(35:36,78:79)=Wmp;A(36:37,80:82)=Wmp;A(38:40,78:82)=Wmp;A(36:40,83:84)=Sm;A(41:44,85:86)=RCm;
%D area yet
A(47:51,34:37)=Sm;   A(39:42,40:46)=Wm;A(40:41,43:44)=0;A(43:45,40:44)=Wm;A(45,41)=0;A(46:52,39:46)=Wm;A(47,43)=0;
A(39:43,25:30)=Sm;A(44,24:30)=Sm;A(45:52,24:28)=Sm;A(45:52,29:30)=Wm;   A(33:36,26:28)=Wm;   A(33:35,37:40)=Wm;A(36,37)=Wm;A(36:37,39)=Wm;   A(38:40,32:33)=Wm;   A(33,43:45)=Wm;A(34,44:45)=Wm;A(35:37,45)=Sm;
%E area yet
A(56,31:37)=Wm;A(57:58,31:34)=Wm;A(59:61,31)=Wm;A(59:60,32)=Wm;A(61,33)=Wm;A(57:60,35)=Wm;A(57:61,36:39)=Wm;A(60,38)=0;A(62:63,31:37)=Wm;A(64,32:36)=Wm;A(65:66,31:37)=Wm;A(67,31:33)=Wm;A(68:69,32)=Wm;A(62:69,38)=Wm;A(64:69,39)=Wm;A(57:66,40)=Wm;A(66:68,41:42)=Wm;A(65:68,43:44)=Wm;A(64:68,45)=Wm;A(58:64,42:43)=Sm;A(56:63,45)=RCm;
A(57:64,22:25)=Wm;A(60,24)=0;A(57:62,26)=Wm;A(59:62,27)=Wm;   A(66:67,22:24)=Wmp;A(67,25)=Wmp;A(68:69,25:26)=Wmp;A(68:69,22:24)=Wm;
%F area yet
A(72,38:39)=Wm;A(73:76,38:40)=Wm;A(75,39)=0;A(77:80,39:40)=Wm;A(80:83,37:38)=Wm;A(83,39)=Wm;A(84:86,40:41)=Wm;A(72,42:45)=Wm;A(73:74,43:45)=Wm;A(75:76,41:45)=Wm;A(77:84,42:45)=Wm;A(78:80,46)=Wm;A(82:83,46)=Wm;A(84,46)=RCm;A(85:86,43:46)=RCm;
A(73:82,30:31)=Wm;A(76,31)=0;A(79,30)=0;A(72:73,32:33)=Wm;A(80:82,32)=Wm;A(81:83,33:34)=Wm;A(84,33:35)=RCm;A(85,30:34)=Wm;A(86,30:35)=Wm;A(83,35)=Wm;   A(76,33:34)=Wm;A(77,33:35)=Wm;   A(75:81,23:27)=Sm;A(84:85,23:26)=Wm;
A(82:83,23:26)=Wmp;   A(82:85,28)=Wm;
%G area
A(97:98,29:35)=Wm;A(96,30:33)=Wm;A(95,30)=Wm;A(95,32:35)=Wm;A(94,33:35)=Wm;A(91:93,32)=Wm;A(90:93,33)=Wm;A(88:93,34)=Wm;A(88:91,35)=Wm;   A(93:98,27)=Wm;A(92:95,28)=Wm;A(98,26)=Wm;A(93:98,27)=Wm;   A(95:96,24)=Wm;
A(89:94,37:38)=Wm;A(90:96,39)=Wm;A(95:96,40)=Wm;A(97:98,37:42)=Wm;A(91:96,41)=Wm;A(93:94,42)=Wm;A(89:96,43)=Sm;A(89:98,44:45)=Sm;A(89:92,46)=Sm;A(91:92,47)=Sm;A(96,46)=Sm;A(97,46:47)=Sm;A(98,46:48)=Sm;
A(85,12:13)=Wmp;A(85,15:16)=Wmp;A(85,19:20)=Wmp;A(86:88,12:20)=Wmp;A(89:91,12:13)=Wm;A(89,15)=Wmp;A(89:90,17)=Wmp;A(89,18)=Wmp;   A(89:93,21)=Wmp;A(90:91,22:23)=Wmp;A(88:90,23:25)=Wmp;A(88:90,26)=Wm;A(88:91,27:28)=Wmp;A(92:94,24)=Wmp;A(95:96,24)=Wm;A(96:98,25)=Wmp;A(96:97,26)=Wmp;A(98,26)=Wm;A(93:98,27)=Wm;A(92:95,28)=Wm;A(92:93,26)=Wm;
%H area yet
A(88:90,49)=Wm;A(88:94,50)=Wm;A(94,51)=Wm;A(88:90,51)=Wm;A(87:97,52)=Wm;A(88:90,53)=Wm;A(96:98,53)=Wm;A(88:91,54)=Wm;A(93,54)=Wm;A(92:93,55)=Wm;   A(88:90,56)=Wm;A(88:91,57)=Wm;A(87:91,58)=Wm;   A(93,59)=Wm;   A(96:98,58:59)=RCm;   A(98,61:63)=Wm;A(97,61:64)=Wm;A(96,62:64)=Wm;
A(87:89,62)=Wm;A(87:92,63:70)=Wm;A(93,63)=Wm;A(93:95,65)=Wm;A(93:94,69:70)=Wm;A(86,64:69)=Wm;A(85,66)=Wm;A(85,68:69)=Wm;A(88:92,71)=Wm;A(86:93,72)=Wm;A(85,71:72)=Wm;A(89:93,73)=Wm;
%I area yet
A(58:65,48:51)=RCm;   A(75:81,49)=Sm;A(74:81,50)=Sm;A(79:80,51)=Sm;A(82,50:55)=Wm;A(81,54:55)=Wm;A(82:83,56)=Wm;A(81:83,57)=Wm;A(84,53:55)=Wm;A(85,49:55)=Wm;  A(81:84,59)=Wm;A(81:83,60)=Wm;
A(59:65,53)=Wm;A(56,53:61)=Wm;A(57,54:61)=Wm;A(58,55:60)=Wm;A(59,54:60)=Wm;A(60:61,54:61)=Wm;A(62,56:61)=Wm;A(63:65,55:61)=Wm;A(64,61)=0;A(66,55:61)=Wm;A(67:71,54:62)=Wm;A(69,54)=0;A(72,59:62)=Wm;A(68:76,64:67)=RCm;A(69:71,63)=Wm;A(74:75,59:63)=Wm;A(77:80,64:67)=Wm;A(81:83,65:66)=Wmp;   A(76:77,58)=Wm;
A(57:62,63)=Sm;A(56:63,64:65)=Wmp;A(64:65,64)=Wmp;A(58:60,66:67)=Wmp;A(56:60,68)=Wmp;A(62:65,66)=Wmp;A(62:66,67)=Wmp;A(64:66,68:71)=Sm;A(67,69:72)=Sm;A(68:70,69:72)=Wm;A(71:72,69:71)=Wmp;   A(74:75,69:71)=Wmp;  A(77:79,69:72)=Wm;A(80,69:71)=Wmp;A(81,69:72)=Wmp;A(82,70:72)=Wmp;
%J area
A(57:58,76:78)=Wm;A(56:58,79)=Wm;A(56:59,80)=Wm;A(56:60,81)=Wm;A(59,77:79)=Sm;A(60:61,76:79)=Sm;A(61:62,79:81)=Sm;A(63:65,75:81)=Sm;A(66:69,80:81)=Sm;   A(57:61,83)=RCm;A(57:71,84:85)=RCm;A(56:66,85:86)=RCm;A(56:61,87)=RCm;A(56:64,88:89)=Wm;A(58,88)=0;A(66:71,87:88)=Sm;A(66:70,89)=Sm;
A(71,74:75)=Wm;A(71:72,76:78)=Sm;A(73,74:78)=Wm;A(74:75,75:77)=Wm;A(75:76,74:75)=Wm;A(77:82,74:76)=Wm;A(79,75)=0;A(78:80,77:78)=Wmp;   A(71:72,80:81)=Wm;   A(74:75,80:82)=Wm;   A(79:80,81:82)=Wmp;   A(73,88:89)=Wmp;A(74,84:89)=Wmp;A(75:77,84:86)=Wmp;A(76,87:88)=Wmp;A(78:80,84:88)=Wmp;
A(86:88,75:77)=Wmp;A(85,76:77)=Wmp;A(83:87,78:79)=Wm;A(83:86,80)=Wm;A(84:86,81)=Wmp;A(83:89,82:83)=Wmp;A(85,84)=Wmp;   A(90,79)=Wm;

%A' area
A(3:4,35:41)=Wm;A(4:10,39:45)=Wm;A(5,40)=0;A(9,39)=0;A(7:9,34:35)=Wmp;A(5:9,36)=Wm;A(5:10,37)=Wm;A(5:7,38)=Wm;A(10,38)=RCm;   A(15:16,30:33)=Wm;A(14,30:38)=Wmp;A(13,32:34)=Wmp;A(13,37:38)=Wmp;A(15,35:38)=Wmp;A(16,38)=Wmp;A(12:15,39:45)=Wm;A(14,42)=0;   A(18,35:37)=Wm;A(19,36:37)=Wm;   A(17:20,40:43)=Sm;   A(27:29,25)=Wm;A(26:29,26)=Wm;
A(19,30:31)=Wm;A(20:21,29:33)=Wm;A(22,29:35)=Wm;A(23:24,29:38)=Wm;A(25,30:38)=Wm;A(26,36:38)=Wm;A(27,35:37)=Wm;A(28:29,34:38)=Wm;   A(25:29,40)=RCm;   A(22,40:45)=Wm;A(23,40:45)=Sm;A(24,42:45)=Sm;A(25:26,42:45)=Wm;A(27:28,42:45)=Wmp;A(29,42:45)=Wm;
%B' area
A(8,74:77)=Wmp;A(9:11,73:76)=Wmp;A(12,74)=Wmp;A(13,72:74)=Wmp;A(14,71:74)=Wm;A(15,70:74)=Wm;A(16,72:74)=Wm;A(17:18,70:74)=Wm;A(12:19,75)=Wm;A(12:14,76)=Wm;   A(21:22,70:71)=RCm;A(21:23,72:74)=Wmp;A(23:25,69:71)=Wm;A(24:25,72:74)=Wm;A(26,70:71)=Wmp;A(27,69:71)=Wmp;A(28,69:70)=Wmp;A(27:30,72:73)=Wm;A(27,74)=Wm;

A(4,53:54)=Wm;A(5:7,53:55)=Wm;A(8,52:55)=Wm;A(9,52:54)=Wm;A(10,49:55)=Wm;A(11,49:56)=Wm;A(12:18,49:55)=Wm;A(12,53)=0;A(19:20,52:54)=Wm;A(19:20,49:51)=Sm;A(21:27,49:54)=Wm;A(25:26,51)=0;A(28,49:50)=Wm;A(29:30,50)=Wm;A(28:30,52:54)=Wm;
A(11,59)=Wm;A(14:17,57)=Wm;A(13:17,58)=Wm;A(12:17,59:62)=Wm;A(16,62)=0;A(18,59:64)=Wm;A(19,58:63)=Wm;A(20:21,57:64)=Wm;A(22:23,58:64)=Wm;A(24:25,58:60)=Wm;A(24:25,63:64)=Wm;A(26,57:59)=Wm;A(27,58:61)=Wm;A(25:27,62)=Wm;A(26:28,63)=Wm;A(28:30,56:59)=Wm;A(14:16,63:68)=RCm;A(15:16,69)=RCm;A(17:21,66:68)=RCm;A(22:23,66:67)=RCm;
A(34:40,49:53)=Wm;A(36,49)=0;A(44:52,51:53)=Wm;A(43,52:53)=Wm;A(41,49:52)=Sm;A(42,49:53)=Sm;A(43:51,49:50)=RCm;A(34,55:61)=Wm;A(35,54:59)=Wm;A(36,55:58)=Wm;A(37,57:58)=Wm;A(35:36,60:63)=Wm;A(37,60:62)=Wm;A(38,60)=Wm;A(39,60:61)=Sm;A(38:39,62)=Wm;A(38:45,55:58)=Wm;A(41,60)=Wm;A(42,60:61)=Wm;A(43:45,59:60)=Wm;A(46:52,54:60)=Wm;A(48,54)=0;A(47,59)=0;
A(47:51,34:37)=Sm;  A(39:42,40:46)=Wm;A(40:41,43:44)=0;A(43:45,40:44)=Wm;A(45,41)=0;A(46:52,39:46)=Wm;A(47,43)=0;
A(44:51,64:66)=RCm;A(42:43,67)=Wm;A(36:43,68)=Wm;A(47:51,67:68)=Wm;A(40:51,69)=Wm;A(37:43,70)=Wm;A(48:51,70)=Wm;A(52,67:72)=Wm;A(35:39,71:72)=Wm;A(37,71)=0;A(35:38,73)=RCm;A(40:51,71:73)=Wm;   A(41:43,76:77)=Wm;A(42:43,78:82)=Wm;A(44:52,79:82)=Wm;
A(56,31:37)=Wm;A(57:58,31:34)=Wm;A(59:61,31)=Wm;A(59:60,32)=Wm;A(61,33)=Wm;A(57:60,35)=Wm;A(57:61,36:39)=Wm;A(60,38)=0;A(62:63,31:37)=Wm;A(64,32:36)=Wm;A(65:66,31:37)=Wm;A(67,31:33)=Wm;A(68:69,32)=Wm;A(62:69,38)=Wm;A(64:69,39)=Wm;A(57:66,40)=Wm;A(66:68,41:42)=Wm;A(65:68,43:44)=Wm;A(64:68,45)=Wm;A(58:64,42:43)=Sm;A(56:63,45)=RCm;

A(130,130)=0.08;

W = A;
% W = sparse(A);

N1 = ones(N,1);
W1 = spdiags(N1,-(ny+1),N,N);W1(1:ny,:)=0;W1(ny+1:ny:N,:)=0;
W2 = spdiags(N1,-ny,N,N);W2(1:ny,:)=0;
W3 = spdiags(N1,-ny+1,N,N);W3(1:ny,:)=0;W3(2*ny:ny:N,:)=0;
W4 = spdiags(N1,-1,N,N);W4(1:ny:N,:)=0;
W5 = spdiags(N1,1,N,N);W5(ny:ny:N,:)=0;%W5(:,ny+1:ny:end) = 0;
W6 = spdiags(N1,ny-1,N,N);W6(1:ny:N-ny,:)=0;W6(N-ny+1:N,:)=0;
W7 = spdiags(N1,ny,N,N);W7(N-ny+1:N,:)=0;
W8 = spdiags(N1,ny+1,N,N);W8(ny:ny:N-ny,:)=0;W8(N-ny+1:N,:)=0;


N2 = (1/4).*N1; %この値はテキトー
W1_2 = spdiags(N2,-(2*ny+2),N,N);W1_2(1:2*ny,:)=0;W1_2(2*ny+1:ny:N,:)=0;W1_2(2*ny+2:ny:N,:)=0;
W2_2 = spdiags(N2,-(2*ny+1),N,N);W2_2(1:2*ny,:)=0;W2_2(2*ny+1:ny:N,:)=0;
W3_2 = spdiags(N2,-2*ny,N,N);W3_2(1:2*ny,:)=0;
W4_2 = spdiags(N2,-(2*ny-1),N,N);W4_2(1:2*ny,:)=0;W4_2(2*ny:ny:N,:)=0;
W5_2 = spdiags(N2,-(2*ny-2),N,N);W5_2(1:2*ny,:)=0;W5_2(2*ny:ny:N,:)=0;W5_2(2*ny-1:ny:N,:)=0;
W6_2 = spdiags(N2,-(ny+2),N,N);W6_2(1:ny+2,:)=0;W6_2(ny+1:ny:N,:)=0;W6_2(ny+2:ny:N,:)=0;
W7_2 = spdiags(N2,-(ny-2),N,N);W7_2(1:ny,:)=0;W7_2(ny:ny:N,:)=0;W7_2(ny-1:ny:N,:)=0;
W8_2 = spdiags(N2,-2,N,N);W8_2(1:ny:N,:)=0;W8_2(2:ny:N,:)=0;
W9_2 = spdiags(N2,2,N,N);W9_2(ny:ny:N,:)=0;W9_2(ny-1:ny:N,:)=0;
W10_2 = spdiags(N2,ny-2,N,N);W10_2(1:ny:N,:)=0;W10_2(2:ny:N,:)=0;W10_2(N-ny+1:N,:)=0;
W11_2 = spdiags(N2,ny+2,N,N);W11_2(ny:ny:N,:)=0;W11_2(ny-1:ny:N,:)=0;
W12_2 = spdiags(N2,2*ny-2,N,N);W12_2(1:ny:N,:)=0;W12_2(2:ny:N,:)=0;W12_2(N-2*ny+1:N,:)=0;
W13_2 = spdiags(N2,2*ny-1,N,N);W13_2(1:ny:N,:)=0;W13_2(N-2*ny+1:N,:)=0;
W14_2 = spdiags(N2,2*ny,N,N);%W14_2(N-2*ny+1:N,:)=0;
W15_2 = spdiags(N2,2*ny+1,N,N);W15_2(ny:ny:N,:)=0;%W15_2(N-2*ny+1:N,:)=0;
W16_2 = spdiags(N2,2*ny+2,N,N);W16_2(ny-1:ny:N,:)=0;W16_2(ny:ny:N,:)=0;%W16_2(N-2*ny:N,:)=0;



N3 = (1/9).*N1;
W1_3 = spdiags(N3,-(3*ny+2),N,N);W1_3(1:3*ny,:)=0;W1_3(1:ny:N,:)=0;W1_3(2:ny:N,:)=0;
W2_3 = spdiags(N3,-(3*ny+1),N,N);W2_3(1:3*ny,:)=0;W2_3(1:ny:N,:)=0;
W3_3 = spdiags(N3,-3*ny,N,N);W3_3(1:3*ny,:)=0;
W4_3 = spdiags(N3,-(3*ny-1),N,N);W4_3(1:3*ny,:)=0;W4_3(4*ny:ny:N,:)=0;
W5_3 = spdiags(N3,-(3*ny-2),N,N);W5_3(1:3*ny,:)=0;W5_3(3*ny:ny:N,:)=0;W5_3(3*ny-1:ny:N,:)=0;

W6_3 = spdiags(N3,-(2*ny+3),N,N);W6_3(1:2*ny+3,:)=0;W6_3(1:ny:N,:)=0;W6_3(2:ny:N,:)=0;W6_3(3:ny:N,:)=0;
W8_3 = spdiags(N3,-(ny+3),N,N);W8_3(1:ny+3,:)=0;W8_3(1:ny:N,:)=0;W8_3(2:ny:N,:)=0;W8_3(3:ny:N,:)=0;
W10_3 = spdiags(N3,-3,N,N);W10_3(1:ny:N,:)=0;W10_3(2:ny:N,:)=0;W10_3(3:ny:N,:)=0;
W12_3 = spdiags(N3,ny-3,N,N);W12_3(N-ny+1:N,:)=0;W12_3(1:ny:N,:)=0;W12_3(2:ny:N,:)=0;W12_3(3:ny:N,:)=0;
W14_3 = spdiags(N3,2*ny-3,N,N);W14_3(N-2*ny+1:N,:)=0;W14_3(1:ny:N,:)=0;W14_3(2:ny:N,:)=0;W14_3(3:ny:N,:)=0;

W7_3 = spdiags(N3,-(2*ny-3),N,N);W7_3(1:2*ny:N,:)=0;W7_3(ny:ny:N,:)=0;W7_3(ny-1:ny:N,:)=0;W7_3(ny-2:ny:N,:)=0;
W9_3 = spdiags(N3,-(ny-3),N,N);W9_3(1:ny,:)=0;W9_3(ny:ny:N,:)=0;W9_3(ny-1:ny:N,:)=0;W9_3(ny-2:ny:N,:)=0;
W11_3 = spdiags(N3,3,N,N);W11_3(ny:ny:N,:)=0;W11_3(ny-1:ny:N,:)=0;W11_3(ny-2:ny:N,:)=0;
W13_3 = spdiags(N3,ny+3,N,N);W13_3(ny:ny:N,:)=0;W13_3(ny-1:ny:N,:)=0;W13_3(ny-2:ny:N,:)=0;
W15_3 = spdiags(N2,2*ny+3,N,N);W15_3(ny:ny:N,:)=0;W15_3(ny-1:ny:N,:)=0;W15_3(ny-2:ny:N,:)=0;

W16_3 = spdiags(N3,3*ny-2,N,N);W16_3(N-3*ny+1:N,:)=0;W16_3(1:ny:N,:)=0;W16_3(2:ny:N,:)=0;
W17_3 = spdiags(N3,3*ny-1,N,N);W17_3(N-3*ny+1:N,:)=0;W17_3(1:ny:N,:)=0;
W18_3 = spdiags(N3,3*ny,N,N);W18_3(N-3*ny+1:N,:)=0;
W19_3 = spdiags(N3,3*ny+1,N,N);W19_3(N-3*ny+1:N,:)=0;W19_3(ny:ny:N,:)=0;
W20_3 = spdiags(N3,3*ny+2,N,N);W20_3(N-3*ny:N,:)=0;W20_3(ny-1:ny:N,:)=0;W20_3(ny:ny:N,:)=0;



N4 = (1/16).*N1;
W1_4 = spdiags(N4,-(4*ny+2),N,N);W1_4(1:4*ny,:)=0;W1_4(1:ny:N,:)=0;W1_4(2:ny:N,:)=0;
W2_4 = spdiags(N4,-(4*ny+1),N,N);W2_4(1:4*ny,:)=0;W2_4(1:ny:N,:)=0;
W3_4 = spdiags(N4,-4*ny,N,N);W3_4(1:4*ny,:)=0;
W4_4 = spdiags(N4,-(4*ny-1),N,N);W4_4(1:4*ny,:)=0;W4_4(4*ny:ny:N,:)=0;
W5_4 = spdiags(N4,-(4*ny-2),N,N);W5_4(1:4*ny,:)=0;W5_4(4*ny:ny:N,:)=0;W5_4(4*ny-1:ny:N,:)=0;

W8_4 = spdiags(N4,-(2*ny+4),N,N);W8_4(1:2*ny+4,:)=0;W8_4(1:ny:N,:)=0;W8_4(2:ny:N,:)=0;W8_4(3:ny:N,:)=0;W8_4(3:ny:N,:)=0;
W10_4 = spdiags(N4,-(ny+4),N,N);W10_4(1:ny+4,:)=0;W10_4(1:ny:N,:)=0;W10_4(2:ny:N,:)=0;W10_4(3:ny:N,:)=0;W10_4(4:ny:N,:)=0;
W12_4 = spdiags(N4,-4,N,N);W12_4(1:ny:N,:)=0;W12_4(2:ny:N,:)=0;W12_4(3:ny:N,:)=0;W12_4(4:ny:N,:)=0;
W14_4 = spdiags(N4,ny-4,N,N);W14_4(N-ny+1:N,:)=0;W14_4(1:ny:N,:)=0;W14_4(2:ny:N,:)=0;W14_4(3:ny:N,:)=0;W14_4(4:ny:N,:)=0;
W16_4 = spdiags(N4,2*ny-4,N,N);W16_4(N-2*ny+1:N,:)=0;W16_4(1:ny:N,:)=0;W16_4(2:ny:N,:)=0;W16_4(3:ny:N,:)=0;W16_4(4:ny:N,:)=0;

W9_4 = spdiags(N4,-(2*ny-4),N,N);W9_4(1:2*ny:N,:)=0;W9_4(ny:ny:N,:)=0;W9_4(ny-1:ny:N,:)=0;W9_4(ny-2:ny:N,:)=0;W9_4(ny-3:ny:N,:)=0;
W11_4 = spdiags(N4,-(ny-4),N,N);W11_4(1:ny,:)=0;W11_4(ny:ny:N,:)=0;W11_4(ny-1:ny:N,:)=0;W11_4(ny-2:ny:N,:)=0;W11_4(ny-3:ny:N,:)=0;
W13_4 = spdiags(N4,4,N,N);W13_4(ny:ny:N,:)=0;W13_4(ny-1:ny:N,:)=0;W13_4(ny-2:ny:N,:)=0;W13_4(ny-3:ny:N,:)=0;
W15_4 = spdiags(N4,ny+4,N,N);W15_4(ny:ny:N,:)=0;W15_4(ny-1:ny:N,:)=0;W15_4(ny-2:ny:N,:)=0;W15_4(ny-3:ny:N,:)=0;
W17_4 = spdiags(N4,2*ny+4,N,N);W17_4(ny:ny:N,:)=0;W17_4(ny-1:ny:N,:)=0;W17_4(ny-2:ny:N,:)=0;W17_4(ny-3:ny:N,:)=0;

W20_4 = spdiags(N4,4*ny-2,N,N);W20_4(N-3*ny+1:N,:)=0;W20_4(1:ny:N,:)=0;W20_4(2:ny:N,:)=0;
W21_4 = spdiags(N4,4*ny-1,N,N);W21_4(N-3*ny+1:N,:)=0;W21_4(1:ny:N,:)=0;
W22_4 = spdiags(N4,4*ny,N,N);W22_4(N-3*ny+1:N,:)=0;
W23_4 = spdiags(N4,4*ny+1,N,N);W23_4(N-3*ny+1:N,:)=0;W23_4(ny:ny:N,:)=0;
W24_4 = spdiags(N4,4*ny+2,N,N);W24_4(N-3*ny:N,:)=0;W24_4(ny-1:ny:N,:)=0;W24_4(ny:ny:N,:)=0;

W6_4 = spdiags(N4,-(3*ny+3),N,N);W6_4(1:3*ny,:)=0;W6_4(1:ny:N,:)=0;W6_4(2:ny:N,:)=0;W6_4(3:ny:N,:)=0;
W7_4 = spdiags(N4,-(3*ny-3),N,N);W7_4(1:3*ny,:)=0;W7_4(ny:ny:N,:)=0;W7_4(ny-1:ny:N,:)=0;W7_4(ny-2:ny:N,:)=0;
W18_4 = spdiags(N4,3*ny-3,N,N);W18_4(N-3*ny+1:N,:)=0;W18_4(1:ny:N,:)=0;WW18_4(2:ny:N,:)=0;W18_4(3:ny:N,:)=0;
W19_4 = spdiags(N4,3*ny+3,N,N);W19_4(N-3*ny:N,:)=0;W19_4(ny:ny:N,:)=0;W19_4(ny-1:ny:N,:)=0;W19_4(ny-2:ny:N,:)=0;W19_4(N-2*ny:N,:)=0;


%飛び火用隣接行列（南からの風、風速9～11m/s）
NT = (1/3000).*N1;
W1_lt = spdiags(NT,-26,N,N); 
for i = 1:26
	W1_lt(i:ny:N,:)=0;
end
W2_lt = spdiags(NT,-27,N,N); 
for i = 1:27
	W2_lt(i:ny:N,:)=0;
end
W3_lt = spdiags(NT,-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W4_lt = spdiags(NT,-29,N,N); 
for i = 1:29
	W4_lt(i:ny:N,:)=0;
end
W5_lt = spdiags(NT,-30,N,N); 
for i = 1:30
	W5_lt(i:ny:N,:)=0;
end
W6_lt = spdiags(NT,-31,N,N); 
for i = 1:31
	W6_lt(i:ny:N,:)=0;
end
W11_lt = spdiags(NT,-(2*ny+26),N,N); 
for i = 1:26
	W1_lt(2*ny+i:ny:N,:)=0;
end
W12_lt = spdiags(NT,-(2*ny+27),N,N); 
for i = 1:27
	W1_lt(2*ny+i:ny:N,:)=0;
end
W13_lt = spdiags(NT,-(2*ny+28),N,N); 
for i = 1:28
	W1_lt(2*ny+i:ny:N,:)=0;
end
W14_lt = spdiags(NT,-(2*ny+29),N,N); 
for i = 1:29
	W1_lt(2*ny+i:ny:N,:)=0;
end
W15_lt = spdiags(NT,-(2*ny+30),N,N); 
for i = 1:30
	W1_lt(2*ny+i:ny:N,:)=0;
end
W16_lt = spdiags(NT,-(2*ny+31),N,N); 
for i = 1:31
	W1_lt(2*ny+i:ny:N,:)=0;
end
W111_lt = spdiags(NT,-(4*ny+27),N,N); 
for i = 1:27
	W1_lt(4*ny+i:ny:N,:)=0;
end
W112_lt = spdiags(NT,-(4*ny+28),N,N); 
for i = 1:28
	W1_lt(4*ny+i:ny:N,:)=0;
end
W113_lt = spdiags(NT,-(4*ny+29),N,N); 
for i = 1:29
	W1_lt(4*ny+i:ny:N,:)=0;
end
W114_lt = spdiags(NT,-(4*ny+30),N,N); 
for i = 1:30
	W1_lt(4*ny+i:ny:N,:)=0;
end
W1111_lt = spdiags(NT,-(6*ny+28),N,N); 
for i = 1:28
	W1_lt(6*ny+i:ny:N,:)=0;
end
W1112_lt = spdiags(NT,-(6*ny+29),N,N); 
for i = 1:29
	W1_lt(6*ny+i:ny:N,:)=0;
end
W11b_lt = spdiags(N2,2*ny-26,N,N); 
for i = 1:26
	W1_lt(i:ny:N,:)=0;
end
W12b_lt = spdiags(N2,2*ny-27,N,N); 
for i = 1:27
	W1_lt(i:ny:N,:)=0;
end
W13b_lt = spdiags(N2,2*ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W14b_lt = spdiags(N2,2*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end
W15b_lt = spdiags(N2,2*ny-30,N,N); 
for i = 1:30
	W1_lt(i:ny:N,:)=0;
end
W16b_lt = spdiags(N2,2*ny-31,N,N); 
for i = 1:31
	W1_lt(i:ny:N,:)=0;
end
W111b_lt = spdiags(NT,4*ny-27,N,N); 
for i = 1:27
	W1_lt(i:ny:N,:)=0;
end
W112b_lt = spdiags(NT,4*ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W113b_lt = spdiags(NT,4*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end
W114b_lt = spdiags(NT,4*ny-30,N,N); 
for i = 1:30
	W1_lt(i:ny:N,:)=0;
end
W1111b_lt = spdiags(NT, 6*ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W1112b_lt = spdiags(NT, 6*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end


NTl = (1/4500).*N1;
W21_lt = spdiags(NTl,-(ny+23),N,N); 
for i = 1:23
	W1_lt(ny+i:ny:N,:)=0;
end
W22_lt = spdiags(NTl,-(ny+24),N,N); 
for i = 1:24
	W1_lt(ny+i:ny:N,:)=0;
end
W23_lt = spdiags(NTl,-(ny+25),N,N); 
for i = 1:25
	W1_lt(ny+i:ny:N,:)=0;
end
W24_lt = spdiags(NTl,-(ny+26),N,N); 
for i = 1:26
	W1_lt(ny+i:ny:N,:)=0;
end
W25_lt = spdiags(NTl,-(ny+27),N,N); 
for i = 1:27
	W1_lt(ny+i:ny:N,:)=0;
end
W26_lt = spdiags(NTl,-(ny+28),N,N); 
for i = 1:28
	W1_lt(ny+i:ny:N,:)=0;
end
W27_lt = spdiags(NTl,-(ny+29),N,N); 
for i = 1:29
	W1_lt(ny+i:ny:N,:)=0;
end
W28_lt = spdiags(NTl,-(ny+30),N,N); 
for i = 1:30
	W1_lt(ny+i:ny:N,:)=0;
end
W29_lt = spdiags(NTl,-(ny+31),N,N); 
for i = 1:31
	W1_lt(ny+i:ny:N,:)=0;
end
W20_lt = spdiags(NTl,-(ny+32),N,N); 
for i = 1:32
	W1_lt(ny+i:ny:N,:)=0;
end
W2ele_lt = spdiags(NTl,-(ny+33),N,N); 
for i = 1:33
	W1_lt(ny+i:ny:N,:)=0;
end
W2twe_lt = spdiags(NTl,-(ny+34),N,N); 
for i = 1:34
	W1_lt(ny+i:ny:N,:)=0;
end
W221_lt = spdiags(NTl,-(3*ny+23),N,N); 
for i = 1:23
	W1_lt(3*ny+i:ny:N,:)=0;
end
W222_lt = spdiags(NTl,-(3*ny+24),N,N); 
for i = 1:24
	W1_lt(3*ny+i:ny:N,:)=0;
end
W223_lt = spdiags(NTl,-(3*ny+25),N,N); 
for i = 1:25
	W1_lt(3*ny+i:ny:N,:)=0;
end
W224_lt = spdiags(NTl,-(3*ny+26),N,N); 
for i = 1:26
	W1_lt(3*ny+i:ny:N,:)=0;
end
W225_lt = spdiags(NTl,-(3*ny+27),N,N); 
for i = 1:27
	W1_lt(3*ny+i:ny:N,:)=0;
end
W226_lt = spdiags(NTl,-(3*ny+28),N,N); 
for i = 1:28
	W1_lt(3*ny+i:ny:N,:)=0;
end
W227_lt = spdiags(NTl,-(3*ny+29),N,N); 
for i = 1:29
	W1_lt(3*ny+i:ny:N,:)=0;
end
W228_lt = spdiags(NTl,-(3*ny+30),N,N); 
for i = 1:30
	W1_lt(3*ny+i:ny:N,:)=0;
end
W229_lt = spdiags(NTl,-(3*ny+31),N,N); 
for i = 1:31
	W1_lt(3*ny+i:ny:N,:)=0;
end
W220_lt = spdiags(NTl,-(3*ny+32),N,N); 
for i = 1:32
	W1_lt(3*ny+i:ny:N,:)=0;
end
W22ele_lt = spdiags(NTl,-(3*ny+33),N,N); 
for i = 1:33
	W1_lt(3*ny+i:ny:N,:)=0;
end
W22twe_lt = spdiags(NTl,-(3*ny+34),N,N); 
for i = 1:34
	W1_lt(3*ny+i:ny:N,:)=0;
end
W2221_lt = spdiags(NTl,-(5*ny+24),N,N); 
for i = 1:24
	W1_lt(5*ny+i:ny:N,:)=0;
end
W2222_lt = spdiags(NTl,-(5*ny+25),N,N); 
for i = 1:25
	W1_lt(5*ny+i:ny:N,:)=0;
end
W2223_lt = spdiags(NTl,-(5*ny+26),N,N); 
for i = 1:26
	W1_lt(5*ny+i:ny:N,:)=0;
end
W2224_lt = spdiags(NTl,-(5*ny+27),N,N); 
for i = 1:27
	W1_lt(5*ny+i:ny:N,:)=0;
end
W2225_lt = spdiags(NTl,-(5*ny+28),N,N); 
for i = 1:28
	W1_lt(5*ny+i:ny:N,:)=0;
end
W2226_lt = spdiags(NTl,-(5*ny+29),N,N); 
for i = 1:29
	W1_lt(5*ny+i:ny:N,:)=0;
end
W2227_lt = spdiags(NTl,-(5*ny+30),N,N); 
for i = 1:30
	W1_lt(5*ny+i:ny:N,:)=0;
end
W2228_lt = spdiags(NTl,-(5*ny+31),N,N); 
for i = 1:31
	W1_lt(5*ny+i:ny:N,:)=0;
end
W2229_lt = spdiags(NTl,-(5*ny+32),N,N); 
for i = 1:32
	W1_lt(5*ny+i:ny:N,:)=0;
end
W2220_lt = spdiags(NTl,-(5*ny+33),N,N); 
for i = 1:33
	W1_lt(5*ny+i:ny:N,:)=0;
end
W222ele_lt = spdiags(NTl,-(5*ny+34),N,N); 
for i = 1:34
	W1_lt(5*ny+i:ny:N,:)=0;
end
W22221_lt = spdiags(NTl,-(7*ny+25),N,N); 
for i = 1:25
	W1_lt(7*ny+i:ny:N,:)=0;
end
W22222_lt = spdiags(NTl,-(7*ny+26),N,N); 
for i = 1:26
	W1_lt(7*ny+i:ny:N,:)=0;
end
W22223_lt = spdiags(NTl,-(7*ny+27),N,N); 
for i = 1:27
	W1_lt(7*ny+i:ny:N,:)=0;
end
W22224_lt = spdiags(NTl,-(7*ny+28),N,N); 
for i = 1:28
	W1_lt(7*ny+i:ny:N,:)=0;
end
W22225_lt = spdiags(NTl,-(7*ny+29),N,N); 
for i = 1:29
	W1_lt(7*ny+i:ny:N,:)=0;
end
W22226_lt = spdiags(NTl,-(7*ny+30),N,N); 
for i = 1:30
	W1_lt(7*ny+i:ny:N,:)=0;
end
W22227_lt = spdiags(NTl,-(7*ny+31),N,N); 
for i = 1:31
	W1_lt(7*ny+i:ny:N,:)=0;
end
W22228_lt = spdiags(NTl,-(7*ny+32),N,N); 
for i = 1:32
	W1_lt(7*ny+i:ny:N,:)=0;
end
W22229_lt = spdiags(NTl,-(7*ny+33),N,N); 
for i = 1:33
	W1_lt(7*ny+i:ny:N,:)=0;
end
W222221_lt = spdiags(NTl,-(9*ny+26),N,N); 
for i = 1:26
	W1_lt(9*ny+i:ny:N,:)=0;
end
W222222_lt = spdiags(NTl,-(9*ny+27),N,N); 
for i = 1:27
	W1_lt(9*ny+i:ny:N,:)=0;
end
W222223_lt = spdiags(NTl,-(9*ny+28),N,N); 
for i = 1:28
	W1_lt(9*ny+i:ny:N,:)=0;
end
W222224_lt = spdiags(NTl,-(9*ny+29),N,N); 
for i = 1:29
	W1_lt(9*ny+i:ny:N,:)=0;
end
W222225_lt = spdiags(NTl,-(9*ny+30),N,N); 
for i = 1:30
	W1_lt(9*ny+i:ny:N,:)=0;
end
W222226_lt = spdiags(NTl,-(9*ny+31),N,N); 
for i = 1:31
	W1_lt(9*ny+i:ny:N,:)=0;
end
W222227_lt = spdiags(NTl,-(9*ny+32),N,N); 
for i = 1:32
	W1_lt(9*ny+i:ny:N,:)=0;
end
W2222221_lt = spdiags(NTl,-(11*ny+27),N,N); 
for i = 1:27
	W1_lt(11*ny+i:ny:N,:)=0;
end
W2222222_lt = spdiags(NTl,-(11*ny+28),N,N); 
for i = 1:28
	W1_lt(11*ny+i:ny:N,:)=0;
end
W2222223_lt = spdiags(NTl,-(11*ny+29),N,N); 
for i = 1:29
	W1_lt(11*ny+i:ny:N,:)=0;
end
W2222224_lt = spdiags(NTl,-(11*ny+30),N,N); 
for i = 1:30
	W1_lt(11*ny+i:ny:N,:)=0;
end
W2222225_lt = spdiags(NTl,-(11*ny+31),N,N); 
for i = 1:31
	W1_lt(11*ny+i:ny:N,:)=0;
end
W22222221_lt = spdiags(NTl,-(13*ny+28),N,N); 
for i = 1:28
	W1_lt(13*ny+i:ny:N,:)=0;
end
W22222222_lt = spdiags(NTl,-(13*ny+29),N,N); 
for i = 1:29
	W1_lt(13*ny+i:ny:N,:)=0;
end
W22222223_lt = spdiags(NTl,-(13*ny+30),N,N); 
for i = 1:30
	W1_lt(13*ny+i:ny:N,:)=0;
end
W222222221_lt = spdiags(NTl,-(15*ny+29),N,N); 
for i = 1:29
	W1_lt(15*ny+i:ny:N,:)=0;
end


W21b_lt = spdiags(NTl,ny-23,N,N); 
for i = 1:23
	W1_lt(i:ny:N,:)=0;
end
W22b_lt = spdiags(NTl,ny-24,N,N); 
for i = 1:24
	W1_lt(i:ny:N,:)=0;
end
W23b_lt = spdiags(NTl,ny-25,N,N); 
for i = 1:25
	W1_lt(i:ny:N,:)=0;
end
W24b_lt = spdiags(NTl,ny-26,N,N); 
for i = 1:26
	W1_lt(i:ny:N,:)=0;
end
W25b_lt = spdiags(NTl,ny-27,N,N); 
for i = 1:27
	W1_lt(i:ny:N,:)=0;
end
W26b_lt = spdiags(NTl,ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W27b_lt = spdiags(NTl,ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end
W28b_lt = spdiags(NTl,ny-30,N,N); 
for i = 1:30
	W1_lt(i:ny:N,:)=0;
end
W29b_lt = spdiags(NTl,ny-31,N,N); 
for i = 1:31
	W1_lt(i:ny:N,:)=0;
end
W20b_lt = spdiags(NTl,ny-32,N,N); 
for i = 1:32
	W1_lt(i:ny:N,:)=0;
end
W2eleb_lt = spdiags(NTl,ny-33,N,N); 
for i = 1:33
	W1_lt(i:ny:N,:)=0;
end
W2tweb_lt = spdiags(NTl,ny-34,N,N); 
for i = 1:34
	W1_lt(i:ny:N,:)=0;
end
W221b_lt = spdiags(NTl,3*ny-23,N,N); 
for i = 1:23
	W1_lt(i:ny:N,:)=0;
end
W222b_lt = spdiags(NTl,3*ny-24,N,N); 
for i = 1:24
	W1_lt(i:ny:N,:)=0;
end
W223b_lt = spdiags(NTl,3*ny-25,N,N); 
for i = 1:25
	W1_lt(i:ny:N,:)=0;
end
W224b_lt = spdiags(NTl,3*ny-26,N,N); 
for i = 1:26
	W1_lt(i:ny:N,:)=0;
end
W225b_lt = spdiags(NTl,3*ny-27,N,N); 
for i = 1:27
	W1_lt(i:ny:N,:)=0;
end
W226b_lt = spdiags(NTl,3*ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W227b_lt = spdiags(NTl,3*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end
W228b_lt = spdiags(NTl,3*ny-30,N,N); 
for i = 1:30
	W1_lt(i:ny:N,:)=0;
end
W229b_lt = spdiags(NTl,3*ny-31,N,N); 
for i = 1:31
	W1_lt(i:ny:N,:)=0;
end
W220b_lt = spdiags(NTl,3*ny-32,N,N); 
for i = 1:32
	W1_lt(i:ny:N,:)=0;
end
W22eleb_lt = spdiags(NTl,3*ny-33,N,N); 
for i = 1:33
	W1_lt(i:ny:N,:)=0;
end
W22tweb_lt = spdiags(NTl,3*ny-34,N,N); 
for i = 1:34
	W1_lt(i:ny:N,:)=0;
end
W2221b_lt = spdiags(NTl,5*ny-24,N,N); 
for i = 1:24
	W1_lt(i:ny:N,:)=0;
end
W2222b_lt = spdiags(NTl,5*ny-25,N,N); 
for i = 1:25
	W1_lt(i:ny:N,:)=0;
end
W2223b_lt = spdiags(NTl,5*ny-26,N,N); 
for i = 1:26
	W1_lt(i:ny:N,:)=0;
end
W2224b_lt = spdiags(NTl,5*ny-27,N,N); 
for i = 1:27
	W1_lt(i:ny:N,:)=0;
end
W2225b_lt = spdiags(NTl,5*ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W2226b_lt = spdiags(NTl,5*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end
W2227b_lt = spdiags(NTl,5*ny-30,N,N); 
for i = 1:30
	W1_lt(i:ny:N,:)=0;
end
W2228b_lt = spdiags(NTl,5*ny-31,N,N); 
for i = 1:31
	W1_lt(i:ny:N,:)=0;
end
W2229b_lt = spdiags(NTl,5*ny-32,N,N); 
for i = 1:32
	W1_lt(i:ny:N,:)=0;
end
W2220b_lt = spdiags(NTl,5*ny-33,N,N); 
for i = 1:33
	W1_lt(i:ny:N,:)=0;
end
W222eleb_lt = spdiags(NTl,5*ny-34,N,N); 
for i = 1:34
	W1_lt(i:ny:N,:)=0;
end
W22221b_lt = spdiags(NTl,7*ny-25,N,N); 
for i = 1:25
	W1_lt(i:ny:N,:)=0;
end
W22222b_lt = spdiags(NTl,7*ny-26,N,N); 
for i = 1:26
	W1_lt(i:ny:N,:)=0;
end
W22223b_lt = spdiags(NTl,7*ny-27,N,N); 
for i = 1:27
	W1_lt(i:ny:N,:)=0;
end
W22224b_lt = spdiags(NTl,7*ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W22225b_lt = spdiags(NTl,7*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end
W22226b_lt = spdiags(NTl,7*ny-30,N,N); 
for i = 1:30
	W1_lt(i:ny:N,:)=0;
end
W22227b_lt = spdiags(NTl,7*ny-31,N,N); 
for i = 1:31
	W1_lt(i:ny:N,:)=0;
end
W22228b_lt = spdiags(NTl,7*ny-32,N,N); 
for i = 1:32
	W1_lt(i:ny:N,:)=0;
end
W22229b_lt = spdiags(NTl,7*ny-33,N,N); 
for i = 1:33
	W1_lt(i:ny:N,:)=0;
end
W222221b_lt = spdiags(NTl,9*ny-26,N,N); 
for i = 1:26
	W1_lt(i:ny:N,:)=0;
end
W222222b_lt = spdiags(NTl,9*ny-27,N,N); 
for i = 1:27
	W1_lt(i:ny:N,:)=0;
end
W222223b_lt = spdiags(NTl,9*ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W222224b_lt = spdiags(NTl,9*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end
W222225b_lt = spdiags(NTl,9*ny-30,N,N); 
for i = 1:30
	W1_lt(i:ny:N,:)=0;
end
W222226b_lt = spdiags(NTl,9*ny-31,N,N); 
for i = 1:31
	W1_lt(i:ny:N,:)=0;
end
W222227b_lt = spdiags(NTl,9*ny-32,N,N); 
for i = 1:32
	W1_lt(i:ny:N,:)=0;
end
W2222221b_lt = spdiags(NTl,11*ny-27,N,N); 
for i = 1:27
	W1_lt(i:ny:N,:)=0;
end
W2222222b_lt = spdiags(NTl,11*ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W2222223b_lt = spdiags(NTl,11*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end
W2222224b_lt = spdiags(NTl,11*ny-30,N,N); 
for i = 1:30
	W1_lt(i:ny:N,:)=0;
end
W2222225b_lt = spdiags(NTl,11*ny-31,N,N); 
for i = 1:31
	W1_lt(i:ny:N,:)=0;
end
W22222221b_lt = spdiags(NTl,13*ny-28,N,N); 
for i = 1:28
	W1_lt(i:ny:N,:)=0;
end
W22222222b_lt = spdiags(NTl,13*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end
W22222223b_lt = spdiags(NTl,13*ny-30,N,N); 
for i = 1:30
	W1_lt(i:ny:N,:)=0;
end
W222222221b_lt = spdiags(NTl,15*ny-29,N,N); 
for i = 1:29
	W1_lt(i:ny:N,:)=0;
end

%自然延焼時重み    W1(1)W2(4),W3(9),W4(16)
%延焼阻止線時重み  W1(1)W2(4),W3(27),W4(64)
W9 = (W1(1:N,1:N)|W2(1:N,1:N)|W3(1:N,1:N)|W4(1:N,1:N)|W5(1:N,1:N)|W6(1:N,1:N)|W7(1:N,1:N)|W8(1:N,1:N));
W17_2 = (1/4).*(W1_2(1:N,1:N)|W2_2(1:N,1:N)|W3_2(1:N,1:N)|W4_2(1:N,1:N)|W5_2(1:N,1:N)|W6_2(1:N,1:N)|W7_2(1:N,1:N)|W8_2(1:N,1:N)|...
    W9_2(1:N,1:N)|W10_2(1:N,1:N)|W11_2(1:N,1:N)|W12_2(1:N,1:N)|W13_2(1:N,1:N)|W14_2(1:N,1:N)|W15_2(1:N,1:N)|W16_2(1:N,1:N));
W21_3 = (1/9).*(W1_3(1:N,1:N)|W2_3(1:N,1:N)|W3_3(1:N,1:N)|W4_3(1:N,1:N)|W5_3(1:N,1:N)|W6_3(1:N,1:N)|W7_3(1:N,1:N)|...
    W8_3(1:N,1:N)|W9_3(1:N,1:N)|W10_3(1:N,1:N)|W11_3(1:N,1:N)|W12_3(1:N,1:N)|W13_3(1:N,1:N)|W14_3(1:N,1:N)|...
    W15_3(1:N,1:N)|W16_3(1:N,1:N)|W17_3(1:N,1:N)|W18_3(1:N,1:N)|W19_3(1:N,1:N)|W20_3(1:N,1:N));
W25_4 = (1/16).*(W1_4(1:N,1:N)|W2_4(1:N,1:N)|W3_4(1:N,1:N)|W4_4(1:N,1:N)|W5_4(1:N,1:N)|W6_4(1:N,1:N)|W7_4(1:N,1:N)|W8_4(1:N,1:N)|...
    W9_4(1:N,1:N)|W10_4(1:N,1:N)|W11_4(1:N,1:N)|W12_4(1:N,1:N)|W13_4(1:N,1:N)|W14_4(1:N,1:N)|W15_4(1:N,1:N)|W16_4(1:N,1:N)|...
    W17_4(1:N,1:N)|W18_4(1:N,1:N)|W19_4(1:N,1:N)|W20_4(1:N,1:N)|W21_4(1:N,1:N)|W22_4(1:N,1:N)|W23_4(1:N,1:N)|W24_4(1:N,1:N));
WS1 = (1/3000).*(W1_lt(1:N,1:N)|W2_lt(1:N,1:N)|W3_lt(1:N,1:N)|W4_lt(1:N,1:N)|W5_lt(1:N,1:N)|W6_lt(1:N,1:N)|...
    W11_lt(1:N,1:N)|W12_lt(1:N,1:N)|W13_lt(1:N,1:N)|W14_lt(1:N,1:N)|W15_lt(1:N,1:N)|W16_lt(1:N,1:N)|...
    W111_lt(1:N,1:N)|W112_lt(1:N,1:N)|W113_lt(1:N,1:N)|W114_lt(1:N,1:N)|W1111_lt(1:N,1:N)|W1112_lt(1:N,1:N)|...
    W11b_lt(1:N,1:N)|W12b_lt(1:N,1:N)|W13b_lt(1:N,1:N)|W14b_lt(1:N,1:N)|W15b_lt(1:N,1:N)|W16b_lt(1:N,1:N)|...
    W111b_lt(1:N,1:N)|W112b_lt(1:N,1:N)|W113b_lt(1:N,1:N)|W114b_lt(1:N,1:N)|W1111b_lt(1:N,1:N)|W1112b_lt(1:N,1:N));
WS2 = (1/4500).*(W21_lt(1:N,1:N)|W22_lt(1:N,1:N)|W23_lt(1:N,1:N)|W24_lt(1:N,1:N)|W25_lt(1:N,1:N)|W26_lt(1:N,1:N)|...
    W27_lt(1:N,1:N)|W28_lt(1:N,1:N)|W29_lt(1:N,1:N)|W20_lt(1:N,1:N)|W2ele_lt(1:N,1:N)|W2twe_lt(1:N,1:N)|...
    W221_lt(1:N,1:N)|W222_lt(1:N,1:N)|W223_lt(1:N,1:N)|W224_lt(1:N,1:N)|W225_lt(1:N,1:N)|W226_lt(1:N,1:N)|...
    W227_lt(1:N,1:N)|W228_lt(1:N,1:N)|W229_lt(1:N,1:N)|W220_lt(1:N,1:N)|W22ele_lt(1:N,1:N)|W22twe_lt(1:N,1:N)|...
    W2221_lt(1:N,1:N)|W2222_lt(1:N,1:N)|W2223_lt(1:N,1:N)|W2224_lt(1:N,1:N)|W2225_lt(1:N,1:N)|W2226_lt(1:N,1:N)|...
    W2227_lt(1:N,1:N)|W2228_lt(1:N,1:N)|W2229_lt(1:N,1:N)|W2220_lt(1:N,1:N)|W222ele_lt(1:N,1:N)|...
    W22221_lt(1:N,1:N)|W22222_lt(1:N,1:N)|W22223_lt(1:N,1:N)|W22224_lt(1:N,1:N)|W22225_lt(1:N,1:N)|W22226_lt(1:N,1:N)|...
    W22227_lt(1:N,1:N)|W22228_lt(1:N,1:N)|W22229_lt(1:N,1:N)|...
    W222221_lt(1:N,1:N)|W222222_lt(1:N,1:N)|W222223_lt(1:N,1:N)|W222224_lt(1:N,1:N)|W222225_lt(1:N,1:N)|W222226_lt(1:N,1:N)|W222227_lt(1:N,1:N)|...
    W2222221_lt(1:N,1:N)|W2222222_lt(1:N,1:N)|W2222223_lt(1:N,1:N)|W2222224_lt(1:N,1:N)|W2222225_lt(1:N,1:N)|...
    W22222221_lt(1:N,1:N)|W22222222_lt(1:N,1:N)|W22222223_lt(1:N,1:N)|W222222221_lt(1:N,1:N)|...
    W21b_lt(1:N,1:N)|W22b_lt(1:N,1:N)|W23b_lt(1:N,1:N)|W24b_lt(1:N,1:N)|W25b_lt(1:N,1:N)|W26b_lt(1:N,1:N)|...
    W27b_lt(1:N,1:N)|W28b_lt(1:N,1:N)|W29b_lt(1:N,1:N)|W20b_lt(1:N,1:N)|W2eleb_lt(1:N,1:N)|W2tweb_lt(1:N,1:N)|...
    W221b_lt(1:N,1:N)|W222b_lt(1:N,1:N)|W223b_lt(1:N,1:N)|W224b_lt(1:N,1:N)|W225b_lt(1:N,1:N)|W226b_lt(1:N,1:N)|...
    W227b_lt(1:N,1:N)|W228b_lt(1:N,1:N)|W229b_lt(1:N,1:N)|W220b_lt(1:N,1:N)|W22eleb_lt(1:N,1:N)|W22tweb_lt(1:N,1:N)|...
    W2221b_lt(1:N,1:N)|W2222b_lt(1:N,1:N)|W2223b_lt(1:N,1:N)|W2224b_lt(1:N,1:N)|W2225b_lt(1:N,1:N)|W2226b_lt(1:N,1:N)|...
    W2227b_lt(1:N,1:N)|W2228b_lt(1:N,1:N)|W2229b_lt(1:N,1:N)|W2220b_lt(1:N,1:N)|W222eleb_lt(1:N,1:N)|...
    W22221b_lt(1:N,1:N)|W22222b_lt(1:N,1:N)|W22223b_lt(1:N,1:N)|W22224b_lt(1:N,1:N)|W22225b_lt(1:N,1:N)|...
    W22226b_lt(1:N,1:N)|W22227b_lt(1:N,1:N)|W22228b_lt(1:N,1:N)|W22229b_lt(1:N,1:N)|...
    W222221b_lt(1:N,1:N)|W222222b_lt(1:N,1:N)|W222223b_lt(1:N,1:N)|W222224b_lt(1:N,1:N)|W222225b_lt(1:N,1:N)|W222226b_lt(1:N,1:N)|W222227b_lt(1:N,1:N)|...
    W2222221b_lt(1:N,1:N)|W2222222b_lt(1:N,1:N)|W2222223b_lt(1:N,1:N)|W2222224b_lt(1:N,1:N)|W2222225b_lt(1:N,1:N)|...
    W22222221b_lt(1:N,1:N)|W22222222b_lt(1:N,1:N)|W22222223b_lt(1:N,1:N)|W222222221b_lt(1:N,1:N));


WW = W9 + W17_2;                                %2セル延焼
WWW = W9 + W17_2 + WS1+ WS2;                    %2セル延焼+飛び火
WWN = W9 + W17_2 + W21_3 + W25_4 + WS1+ WS2;    %自然延焼Nature　4セル延焼+飛び火
WWNc = W9 + W17_2 + W21_3 + W25_4;              %無風時自然延焼Nature　4セル延焼
W10 = reshape(W,[N,1]);

% この計算の遅さは仕方がない
% E2 = (W9./sum(W9,2));% Alt-PageRank
% E = W9.*W10;% Weighted Alt-PageRank
% E2 = (WW./sum(WW,2));
% E = WW.*W10;                  %延焼阻止線設定時（飛び火無し）
E2 = (WWN./sum(WWN,2));
E = WWN.*W10;                 %完全自然延焼（南風在り）
% E2 = (WWNc./sum(WWNc,2));
% E = WWNc.*W10;                %完全自然延焼（無風）
% E2 = (WWW./sum(WWW,2));
% E = WWW.*W10;                 %延焼阻止線設定時（つまり消防隊が機能している時）の自然延焼
maxW = max(W,[],'all');
if maxW > 1 | maxv~=1
    W = (maxv*W/maxW);
    E = (maxv*E/maxW);
end
end

