function [eval] = FimobjectiveMEX(x, params)
% モデル予測制御の評価値を計算するプログラム
%-- MPCで用いる予測状態 Xと予測入力 Uを設定
X = x(1:params.state_size, :);
U = x(params.state_size+1:end, :);
%-- 状態及び入力に対する目標状態や目標入力との誤差を計算
tildeX = X - params.Xr;
tildeU = U;
%
evFim = zeros(1,params.H);
for j = 1:params.H
    Fim = FIM_ObserbSub(X(1,j), X(2,j), X(3,j), X(4,j), X(5,j), params.t, params.dis(1), params.alpha(1), params.phi(1));
%     arrayfun(@(N) FIM_ObserbSub(X(1,1), X(2,1), X(3,1), X(4,1), X(5,1), params.t, params.dis(N), params.alpha(N), params.phi(N)),1:length(params.dis),'UniformOutput',false);
    for i = 2:length(params.dis)
        Fim = Fim + FIM_ObserbSub(X(1,j), X(2,j), X(3,j), X(4,j), X(5,j), params.t, params.dis(i), params.alpha(i), params.phi(i) );
    end
    Fim = (1/(2*params.NoiseR))*Fim;
    InvFim = inv(Fim);
    evFim(1,j) = max(eig(InvFim));
end
%-- 状態及び入力のステージコストを計算
stageState = arrayfun(@(L) tildeX(:, L)' * params.Q * tildeX(:, L), 1:params.H);
stageInput = arrayfun(@(L) tildeU(:, L)' * params.R * tildeU(:, L), 1:params.H);
% stageevFim = arrayfun(@(L) evFim(:,L)' * params.Th * evFim(:,L), 1:params.H);
stageevFim = evFim* params.T * evFim';
%-- 状態の終端コストを計算
terminalState = tildeX(:, end)' * params.Qf * tildeX(:, end);
%-- 評価値計算
eval = sum(stageState + stageInput) + sum(stageevFim) + terminalState;
end
function PP = FIM_ObserbSub(x,y,theta,v,omega,t,d1,alpha1,phi1)
%FIM_OBSERBSUB
%    PP = FIM_OBSERBSUB(X,Y,THETA,V,OMEGA,T,D1,ALPHA1,PHI1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-Jul-2021 16:27:23
%   This function was overwritten by Sota Wada on 2021_10_21 and the reshape function was removed.

t2 = cos(alpha1);
t3 = sin(alpha1);
t4 = cos(theta);
t5 = sin(theta);
t6 = omega.*t;
t7 = -alpha1;
t8 = -d1;
t9 = t.*t4.*v;
t10 = t.*t5.*v;
t11 = t.*t2.*t4;
t12 = t.*t3.*t5;
t17 = phi1+t6+t7+theta;
t13 = t10+y;
t14 = t9+x;
t18 = cos(t17);
t19 = sin(t17);
t20 = t11+t12;
t15 = t2.*t14;
t16 = t3.*t13;
t21 = 1.0./t18.^3;
t22 = t8+t15+t16;
t23 = t.*t19.*t20.*t21.*t22;
PP = [1.0./t18.^2.*t20.^2,t23;t23,t.^2.*1.0./t18.^4.*t19.^2.*t22.^2];
end
