function obsmodel_sub = output_function_for_marker_position(in1,in2)
%OUTPUT_FUNCTION_FOR_MARKER_POSITION
%    OBSMODEL_SUB = OUTPUT_FUNCTION_FOR_MARKER_POSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    23-Mar-2020 10:54:15

%【Inputs】\n\t pos ([1;1;1]): position of COG of the rigid body\n\t mx (=[1 2 3;1 1 1]): marker position w. r. t. pos
X_sym1 = in1(1,:);
X_sym2 = in1(2,:);
X_sym3 = in1(3,:);
X_sym4 = in1(4,:);
X_sym5 = in1(5,:);
X_sym6 = in1(6,:);
mx1 = in2(1,:);
mx2 = in2(2,:);
mx3 = in2(3,:);
t2 = cos(X_sym4);
t3 = cos(X_sym5);
t4 = cos(X_sym6);
t5 = sin(X_sym4);
t6 = sin(X_sym5);
t7 = sin(X_sym6);
obsmodel_sub = [X_sym1-mx2.*(t2.*t7-t4.*t5.*t6)+mx3.*(t5.*t7+t2.*t4.*t6)+mx1.*t3.*t4;X_sym2+mx2.*(t2.*t4+t5.*t6.*t7)-mx3.*(t4.*t5-t2.*t6.*t7)+mx1.*t3.*t7;X_sym3-mx1.*t6+mx3.*t2.*t3+mx2.*t3.*t5];
