function out1 = Jacobian_vehicle(in1,p1)
%Jacobian_vehicle
%    OUT1 = Jacobian_vehicle(IN1,P1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2023/11/13 13:16:27

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
end
