function out1 = Jacobian_vehicle3(in1,in2)
%Jacobian_vehicle3
%    OUT1 = Jacobian_vehicle3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Dec-2022 11:10:29

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
