function dx = roll_pitch_yaw_thrust_torque_physical_parameter_expand_model(in1,in2,in3)
%ROLL_PITCH_YAW_THRUST_TORQUE_PHYSICAL_PARAMETER_EXPAND_MODEL
%    DX = ROLL_PITCH_YAW_THRUST_TORQUE_PHYSICAL_PARAMETER_EXPAND_MODEL(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/16 18:11:55

Tr = in1(13,:);
dTr = in1(14,:);
dp1 = in1(7,:);
dp2 = in1(8,:);
dp3 = in1(9,:);
gravity = in3(:,9);
jx = in3(:,6);
jy = in3(:,7);
jz = in3(:,8);
m = in3(:,1);
o1 = in1(10,:);
o2 = in1(11,:);
o3 = in1(12,:);
pitch = in1(5,:);
roll = in1(4,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
yaw = in1(6,:);
t2 = cos(pitch);
t3 = cos(roll);
t4 = sin(pitch);
t5 = sin(roll);
t6 = 1.0./jx;
t7 = 1.0./jy;
t8 = 1.0./jz;
t9 = 1.0./m;
t11 = pitch./2.0;
t12 = roll./2.0;
t13 = yaw./2.0;
t10 = 1.0./t2;
t14 = cos(t11);
t15 = cos(t12);
t16 = cos(t13);
t17 = sin(t11);
t18 = sin(t12);
t19 = sin(t13);
t20 = t14.*t15.*t16;
t21 = t14.*t15.*t19;
t22 = t14.*t16.*t18;
t23 = t15.*t16.*t17;
t24 = t14.*t18.*t19;
t25 = t15.*t17.*t19;
t26 = t16.*t17.*t18;
t27 = t17.*t18.*t19;
t28 = -t25;
t29 = -t26;
t30 = t20+t27;
t31 = t23+t24;
t32 = t21+t29;
t33 = t22+t28;
dx = [dp1;dp2;dp3;t10.*(o1.*t2+o3.*t3.*t4+o2.*t4.*t5);o2.*t3-o3.*t5;t10.*(o3.*t3+o2.*t5);Tr.*t9.*(t30.*t31.*2.0+t32.*t33.*2.0);-Tr.*t9.*(t30.*t33.*2.0-t31.*t32.*2.0);-gravity+Tr.*t9.*(t30.^2-t31.^2+t32.^2-t33.^2);t6.*u2+t6.*(jy.*o2.*o3-jz.*o2.*o3);t7.*u3-t7.*(jx.*o1.*o3-jz.*o1.*o3);t8.*u4+t8.*(jx.*o1.*o2-jy.*o1.*o2);dTr;u1];
end
