function result = Cov_Elliptical_potential(x,y,obx1,oby1,obx2,oby2)
%COV_ELLIPTICAL_POTENTIAL
%    RESULT = COV_ELLIPTICAL_POTENTIAL(X,Y,OBX1,OBY1,OBX2,OBY2)
%    楕円ポテンシャルを自動で作るやつ，自己位置，障害物短点の順で入れる．
%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Dec-2020 11:53:13

t2 = -obx2;
t3 = -oby2;
t4 = -x;
t5 = -y;
t6 = obx1+t2;
t7 = oby1+t3;
t8 = obx1+t4;
t9 = obx2+t4;
t10 = oby1+t5;
t11 = oby2+t5;
t12 = abs(t8);
t13 = abs(t9);
t14 = abs(t10);
t15 = abs(t11);
t16 = abs(t6);
t17 = abs(t7);
t18 = t16.^2;
t19 = t17.^2;
t20 = t12.^2;
t21 = t13.^2;
t22 = t14.^2;
t23 = t15.^2;
t24 = t18+t19;
t25 = t20+t22;
t26 = t21+t23;
t27 = sqrt(t24);
t28 = sqrt(t25);
t29 = sqrt(t26);
t30 = 1.0./t28;
t31 = 1.0./t29;
t32 = -t27;
t33 = t28+t29+t32;
t34 = 1.0./t33.^3;
result = [t34.*(t12.*t30.*sign(t8)+t13.*t31.*sign(t9)).*2.0;t34.*(t14.*t30.*sign(t10)+t15.*t31.*sign(t11)).*2.0];
