function symVp = Cov_Vp2(symx,symy,symnodex,symnodey,symnoder,obx1,oby1,obx1r,oby1r,obx2,oby2,obx2r,oby2r,obx3,oby3,obx3r,oby3r)
%COV_VP2
%    SYMVP = COV_VP2(SYMX,SYMY,SYMNODEX,SYMNODEY,SYMNODER,OBX1,OBY1,OBX1R,OBY1R,OBX2,OBY2,OBX2R,OBY2R,OBX3,OBY3,OBX3R,OBY3R)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    08-Jan-2021 16:12:09

t2 = -symx;
t3 = -symy;
symVp = exp(sqrt(abs(symx-symnodex).^2+abs(symy-symnodey).^2)./symnoder)./1.0e+1+1.0./(sqrt(abs(obx1-obx1r).^2+abs(oby1-oby1r).^2)+sqrt(abs(obx1+t2).^2+abs(oby1+t3).^2)+sqrt(abs(obx1r+t2).^2+abs(oby1r+t3).^2)).^2+1.0./(sqrt(abs(obx2-obx2r).^2+abs(oby2-oby2r).^2)+sqrt(abs(obx2+t2).^2+abs(oby2+t3).^2)+sqrt(abs(obx2r+t2).^2+abs(oby2r+t3).^2)).^2+1.0./(sqrt(abs(obx3-obx3r).^2+abs(oby3-oby3r).^2)+sqrt(abs(obx3+t2).^2+abs(oby3+t3).^2)+sqrt(abs(obx3r+t2).^2+abs(oby3r+t3).^2)).^2;
