function out1 = F_RPY18(in1,in2)
%F_RPY18
%    OUT1 = F_RPY18(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    01-Feb-2024 17:20:46

dp1 = in1(7,:);
dp2 = in1(8,:);
dp3 = in1(9,:);
gravity = in2(:,9);
jx = in2(:,6);
jy = in2(:,7);
jz = in2(:,8);
o1 = in1(10,:);
o2 = in1(11,:);
o3 = in1(12,:);
pitch = in1(5,:);
roll = in1(4,:);
t2 = cos(pitch);
t3 = cos(roll);
t4 = sin(pitch);
t5 = sin(roll);
t6 = 1.0./t2;
out1 = [dp1;dp2;dp3;t6.*(o1.*t2+o3.*t3.*t4+o2.*t4.*t5);o2.*t3-o3.*t5;t6.*(o3.*t3+o2.*t5);0.0;0.0;-gravity;(jy.*o2.*o3-jz.*o2.*o3)./jx;-(jx.*o1.*o3-jz.*o1.*o3)./jy;(jx.*o1.*o2-jy.*o1.*o2)./jz;0.0;0.0;0.0;0.0;0.0;0.0];
