function Odot = LgO19_11(in1,in2)
%LgO19_11
%    Odot = LgO19_11(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    16-Feb-2024 21:56:14

u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = cos(x5);
t3 = sin(x4);
t4 = sin(x5);
t5 = 1.0./t2;
Odot = t3.*u2.*(-5.0e+1./3.0)-t3.^2.*t4.*t5.*u3.*(1.0e+2./3.0)-t3.*t4.*t5.*u4.*cos(x4).*(1.0e+2./3.0);
