function Odot = LgO19_5(in1,in2)
%LgO19_5
%    Odot = LgO19_5(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    16-Feb-2024 21:56:13

u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(x4);
t5 = sin(x5);
t6 = t5.^2;
t7 = t3.*x10;
t8 = t2.*x12;
t9 = t5.*x10;
t10 = t4.*x11;
t11 = 1.0./t3;
t12 = t11.^2;
t13 = t3.*t8;
t14 = t3.*t10;
t15 = t5.*t8;
t16 = t5.*t10;
t17 = -t9;
t18 = t8+t10;
t19 = t7+t15+t16;
t20 = t13+t14+t17;
Odot = -u4.*(t2.*t18.*(5.0e+1./3.0)+t2.*t11.*t20.*(5.0e+1./3.0)+t2.*t5.*t12.*t19.*(5.0e+1./3.0)+t2.*t6.*t12.*t18.*(5.0e+1./3.0))-u3.*(t4.*t18.*(5.0e+1./3.0)+t4.*t11.*t20.*(5.0e+1./3.0)+t4.*t5.*t12.*t19.*(5.0e+1./3.0)+t4.*t6.*t12.*t18.*(5.0e+1./3.0));
