function Odot = LgO11_5(in1,in2)
%LgO11_5
%    Odot = LgO11_5(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    16-Feb-2024 21:52:41

u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(x4);
t5 = sin(x5);
t6 = t5.^2;
t7 = 1.0./t3.^2;
Odot = u4.*(t2.*(5.0e+1./3.0)+t2.*t6.*t7.*(5.0e+1./3.0))+u3.*(t4.*(5.0e+1./3.0)+t4.*t6.*t7.*(5.0e+1./3.0));
