function Odot = LgO18_11(in1,in2)
%LgO18_11
%    Odot = LgO18_11(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    16-Feb-2024 21:56:12

u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(x4);
t5 = sin(x5);
t6 = t5.^2;
t7 = 1.0./t3.^2;
t8 = t4.*t6.*t7;
t9 = t4+t8;
Odot = -u4.*(t4.*t8.*(5.0e+1./3.0)+t4.*t9.*(5.0e+1./3.0)-t2.*(t2+t2.*t6.*t7).*(5.0e+1./3.0)-t2.^2.*t6.*t7.*(5.0e+1./3.0))+u3.*(t2.*t8.*(1.0e+2./3.0)+t2.*t9.*(1.0e+2./3.0))+(t2.*t5.*u2.*(5.0e+1./3.0))./t3;
