function Odot = LgO13_4(in1,in2)
%LgO13_4
%    Odot = LgO13_4(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    16-Feb-2024 21:52:43

u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = cos(x5);
t3 = 1.0./t2;
Odot = t3.*u3.*cos(x4).*(5.0e+1./3.0)-t3.*u4.*sin(x4).*(5.0e+1./3.0);
