function Odot = LgO19_10(in1,in2)
%LgO19_10
%    Odot = LgO19_10(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    16-Feb-2024 21:56:14

u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
Odot = u4.*cos(x4).*(-5.0e+1./3.0)-u3.*sin(x4).*(5.0e+1./3.0);
