function Odot = LgO20_12(in1,in2)
%LgO20_12
%    Odot = LgO20_12(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    16-Feb-2024 21:56:15

u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(x4);
t5 = sin(x5);
t6 = 1.0./t3.^2;
Odot = u3.*(t2.^2.*t5.*t6.*(1.0e+2./3.0)-t4.^2.*t5.*t6.*(1.0e+2./3.0))-(t4.*u2.*(5.0e+1./3.0))./t3-t2.*t4.*t5.*t6.*u4.*(2.0e+2./3.0);
