function Odot = LgO20_4(in1,in2)
%LgO20_4
%    Odot = LgO20_4(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    16-Feb-2024 21:56:14

u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x4 = in1(4,:);
x5 = in1(5,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(x4);
t5 = sin(x5);
t6 = t3.*x10;
t7 = t2.*x11;
t8 = t2.*x12;
t9 = t4.*x11;
t10 = t4.*x12;
t11 = 1.0./t3.^2;
t12 = t5.*t7;
t13 = t5.*t8;
t14 = t5.*t9;
t15 = t5.*t10;
t16 = -t10;
t18 = t8+t9;
t17 = -t15;
t19 = t7+t16;
t21 = t6+t13+t14;
t20 = t12+t17;
Odot = u3.*(t2.*t11.*t20.*(5.0e+1./3.0)-t4.*t11.*t21.*(5.0e+1./3.0)+t2.*t5.*t11.*t19.*5.0e+1-t4.*t5.*t11.*t18.*5.0e+1)-u4.*(t2.*t11.*t21.*(5.0e+1./3.0)+t4.*t11.*t20.*(5.0e+1./3.0)+t2.*t5.*t11.*t18.*5.0e+1+t4.*t5.*t11.*t19.*5.0e+1)-(t18.*u2.*(5.0e+1./3.0))./t3;
