function out1 = matrix_prod_3x3to9x1(in1,in2)
%MATRIX_PROD_3X3TO9X1
%    OUT1 = MATRIX_PROD_3X3TO9X1(IN1,IN2)
% syms A [9 1] real
% syms B [9 1] real
% 
% AA = [A(1:3),A(4:6),A(7:9)];
% BB = [B(1:3),B(4:6),B(7:9)];
% matlabFunction(reshape(AA*BB,9,1),"file","matrix_prod_3x3to9x1.m","vars",{A,B})

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/30 15:14:38

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
A4 = in1(4,:);
A5 = in1(5,:);
A6 = in1(6,:);
A7 = in1(7,:);
A8 = in1(8,:);
A9 = in1(9,:);
B1 = in2(1,:);
B2 = in2(2,:);
B3 = in2(3,:);
B4 = in2(4,:);
B5 = in2(5,:);
B6 = in2(6,:);
B7 = in2(7,:);
B8 = in2(8,:);
B9 = in2(9,:);
out1 = [A1.*B1+A4.*B2+A7.*B3;A2.*B1+A5.*B2+A8.*B3;A3.*B1+A6.*B2+A9.*B3;A1.*B4+A4.*B5+A7.*B6;A2.*B4+A5.*B5+A8.*B6;A3.*B4+A6.*B5+A9.*B6;A1.*B7+A4.*B8+A7.*B9;A2.*B7+A5.*B8+A8.*B9;A3.*B7+A6.*B8+A9.*B9];
end
