function out1 = matrix_transpose_3x3to9x1(in1)
%MATRIX_TRANSPOSE_3X3TO9X1
%    OUT1 = MATRIX_TRANSPOSE_3X3TO9X1(IN1)
% syms A [9 1] real
% 
% AA = [A(1:3),A(4:6),A(7:9)];
% matlabFunction(reshape(AA',9,1),"file","matrix_transpose_3x3to9x1.m","vars",{A})

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/30 15:17:35

A1 = in1(1,:);
A2 = in1(2,:);
A3 = in1(3,:);
A4 = in1(4,:);
A5 = in1(5,:);
A6 = in1(6,:);
A7 = in1(7,:);
A8 = in1(8,:);
A9 = in1(9,:);
out1 = [A1;A4;A7;A2;A5;A8;A3;A6;A9];
end
