function eul = Quat2Eul(in1)
    % convert quaternion to euler angle
    % 【Input】q : quaternion
    % 【Output】eul : euler angle

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/21 11:23:20
% algorithm
% % syms q [4 1] real
% % nq=norm(q);
% % q0 = q(1)/nq;
% % q1 = q(2)/nq;
% % q2 = q(3)/nq;
% % q3 = q(4)/nq;
% % phi = atan2((2*(q0.*q1 + q2.*q3)),(q0.^2 - q1.^2 - q2.^2 + q3.^2));
% % th  = asin(2*(q0.*q2 - q1.*q3));
% % psi = atan2((2*(q0.*q3 + q1.*q2)),(q0.^2 + q1.^2 - q2.^2 - q3.^2));
% % eul = [phi; th; psi];
% % matlabFunction(eul,"vars",{q},"file","tmp.m")

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = abs(q1);
t3 = abs(q2);
t4 = abs(q3);
t5 = abs(q4);
t6 = q1.^2;
t7 = q2.^2;
t8 = q3.^2;
t9 = q4.^2;
t10 = t2.^2;
t11 = t3.^2;
t12 = t4.^2;
t13 = t5.^2;
t14 = t10+t11+t12+t13;
t15 = 1.0./t14;
t16 = t6.*t15;
t17 = t7.*t15;
t18 = t8.*t15;
t19 = t9.*t15;
t20 = -t18;
eul = [atan2(q1.*q2.*t15.*2.0+q3.*q4.*t15.*2.0,t16-t17+t19+t20);asin(q1.*q3.*t15.*2.0-q2.*q4.*t15.*2.0);atan2(q1.*q4.*t15.*2.0+q2.*q3.*t15.*2.0,t16+t17-t19+t20)];
end
