function [R,L] = RodriguesQuaternion(in1)
% [R,L]=RodriguesQuaternion(q) : convert quaternion to rotaiton matrix
%  R is the rotation matrix
%  q is 4th dim vector : [1 0 0 0]
% R = rotmat(quaternion(q),'frame') と等価？違いそう

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/21 11:27:48
% algorithm
% syms q [4 1] real
% q  = q(:);
%     q0 = q(1);
%     q1 = q(2);
%     q2 = q(3);
%     q3 = q(4);
% 	E = [-q1, q0,-q3, q2;
% 		 -q2, q3, q0,-q1;
% 		 -q3,-q2, q1, q0];
% 	L = [-q1, q0, q3,-q2;
% 		 -q2,-q3, q0, q1;
% 		 -q3, q2,-q1, q0];
% 	R = E*L';
%   matlabFunction(L,"file","tmp.m","vars",{q});

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q1.^2;
t3 = q2.^2;
t4 = q3.^2;
t5 = q4.^2;
t6 = q1.*q2.*2.0;
t7 = q1.*q3.*2.0;
t8 = q1.*q4.*2.0;
t9 = q2.*q3.*2.0;
t10 = q2.*q4.*2.0;
t11 = q3.*q4.*2.0;
t12 = -t3;
t13 = -t4;
t14 = -t5;
L = [-q2, q1, q4,-q3;
  -q3,-q4, q1, q2;
  -q4, q3,-q2, q1];
R = reshape([t2+t3+t13+t14,t8+t9,-t7+t10,-t8+t9,t2+t4+t12+t14,t6+t11,t7+t10,-t6+t11,t2+t5+t12+t13],[3,3]);
end
