function cZep1 = Zep1(in1,in2,in3)
%Zep1
%    cZep1 = Zep1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/20 15:03:28

T1 = in1(14,:);
Xd3 = in2(:,3);
dT1 = in1(15,:);
dXd3 = in2(:,7);
ddXd3 = in2(:,11);
dddXd3 = in2(:,15);
dp3 = in1(10,:);
gravity = in3(:,9);
m = in3(:,1);
o1 = in1(11,:);
o2 = in1(12,:);
o3 = in1(13,:);
p3 = in1(7,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = 1.0./m;
t7 = -t3;
t8 = -t4;
t9 = t2+t5+t7+t8;
cZep1 = [-Xd3+p3;-dXd3+dp3;-ddXd3-gravity+T1.*t6.*t9;-dddXd3+dT1.*t6.*t9-T1.*q0.*t6.*((o1.*q1)./2.0+(o2.*q2)./2.0+(o3.*q3)./2.0).*2.0-T1.*q1.*t6.*((o1.*q0)./2.0-(o2.*q3)./2.0+(o3.*q2)./2.0).*2.0-T1.*q2.*t6.*((o2.*q0)./2.0+(o1.*q3)./2.0-(o3.*q1)./2.0).*2.0+T1.*q3.*t6.*(o1.*q2.*(-1.0./2.0)+(o2.*q1)./2.0+(o3.*q0)./2.0).*2.0];
end
