function out1 = Cov_diffx_Vp_roll(xdx,xdy,px,py,symx,symy)
%COV_DIFFX_VP_ROLL
%    OUT1 = COV_DIFFX_VP_ROLL(XDX,XDY,PX,PY,SYMX,SYMY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    16-Feb-2021 15:46:12

t2 = imag(px);
t3 = imag(symx);
t4 = real(py);
t5 = real(symy);
t6 = -px;
t9 = pi./2.0;
t10 = py.*1i;
t11 = symy.*1i;
t12 = xdy.*1i;
t7 = -t3;
t8 = -t5;
t13 = -t10;
t14 = t2+t4+t7+t8;
t15 = symx+t6+t11+t13;
t16 = t6+t12+t13+xdx;
t17 = angle(t15);
t18 = angle(t16);
t19 = -t17;
t20 = t9+t18+t19;
out1 = -(t14.*1.0./t20.^2.*(tanh(1.0./t20).^2-1.0))./((imag(py)-imag(symy)-real(px)+real(symx)).^2+t14.^2);
