function symVp = Cov_Vp(symx,symy,symnodex,symnodey,symnoder)
%COV_VP
%    SYMVP = COV_VP(SYMX,SYMY,SYMNODEX,SYMNODEY,SYMNODER)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Feb-2021 12:23:47
th =(pi.*sqrt((symx-symnodex).^2+(symy-symnodey).^2))./(symnoder.*2.0);
if th>pi/2
    th =pi/2;
end
symVp = (symnoder.*tan(th).*2.0)./pi;
if isnan(symVp)
    disp('a')
end
end
