function out1 = Cov_diffx_Vp(symx,symy,symnodex,symnodey,symnoder)
%COV_DIFFX_VP
%    OUT1 = COV_DIFFX_VP(SYMX,SYMY,SYMNODEX,SYMNODEY,SYMNODER)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Feb-2021 12:23:47

t2 = -symnodex;
t3 = -symnodey;
t4 = symx+t2;
t5 = symy+t3;
t6 = t4.^2;
t7 = t5.^2;
t8 = t6+t7;
out1 = (1.0./sqrt(t8).*(symx.*2.0-symnodex.*2.0).*(tan((sqrt(t8).*pi)./(symnoder.*2.0)).^2+1.0))./2.0;
