function symVp = Cov_slope(symx,symy,a,b,c,d,e,f,g)
%COV_SLOPE
%    SYMVP = COV_SLOPE(SYMX,SYMY,A,B,C,D,E,F,G)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Aug-2021 11:04:24

t2 = -symx;
t3 = -symy;
symVp = c+tan((pi.*(tanh((d+t2).^3.*(e+t2).^3)+1.0))./4.0)+tan((pi.*(tanh((f+t3).^3.*(g+t3).^3)+1.0))./4.0)+a.*symx+b.*symy;
