function symVp = Cov_Vp_roll(xdx,xdy,px,py,symx,symy)
%COV_VP_ROLL
%    SYMVP = COV_VP_ROLL(XDX,XDY,PX,PY,SYMX,SYMY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    16-Feb-2021 15:46:12

t2 = -px;
t3 = py.*1i;
t4 = -t3;
symVp = tanh(1.0./(pi./2.0-atan2(symy,symx+t2+t4)+atan2(xdy,t2+t4+xdx)));
