function out1 = Cov_diffy_daen(symx,symy,obx1,oby1,obx2,oby2)
%COV_DIFFY_DAEN
%    OUT1 = COV_DIFFY_DAEN(SYMX,SYMY,OBX1,OBY1,OBX2,OBY2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    08-Jan-2021 14:19:30

t2 = -symx;
t3 = -symy;
t4 = obx1+t2;
t5 = obx2+t2;
t6 = oby1+t3;
t7 = oby2+t3;
t8 = abs(t4);
t9 = abs(t5);
t10 = abs(t6);
t11 = abs(t7);
t12 = t8.^2;
t13 = t9.^2;
t14 = t10.^2;
t15 = t11.^2;
t16 = t12+t14;
t17 = t13+t15;
out1 = (t10.*1.0./sqrt(t16).*sign(t6)+t11.*1.0./sqrt(t17).*sign(t7)).*1.0./(sqrt(abs(obx1-obx2).^2+abs(oby1-oby2).^2)+sqrt(t16)+sqrt(t17)).^3.*2.0;
