function out1 = Cov_diffy_slope(symx,symy,a,b,c,d,e,f,g)
%COV_DIFFY_SLOPE
%    OUT1 = COV_DIFFY_SLOPE(SYMX,SYMY,A,B,C,D,E,F,G)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Aug-2021 11:04:24

t2 = -symy;
t3 = f+t2;
t4 = g+t2;
t5 = t3.^3;
t6 = t4.^3;
t7 = t5.*t6;
t8 = tanh(t7);
out1 = b+(pi.*(t8.^2-1.0).*(t3.^2.*t6.*3.0+t4.^2.*t5.*3.0).*(tan((pi.*(t8+1.0))./4.0).^2+1.0))./4.0;
