/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * autoEval.c
 *
 * Code generation for function 'autoEval'
 *
 */

/* Include files */
#include "autoEval.h"
#include "F_HL_MPCfunc.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
void autoEval(const real_T in1[132], const real_T in2[4], real_T Qm, real_T Qmf,
              real_T Qt, real_T Qtf, const real_T in7[4], real_T Ws, real_T Wr,
              const real_T in10[11], const real_T in11[11], real_T BLD, const
              real_T in13[11], real_T *eval, real_T deval[132])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t19;
  real_T t20;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t24;
  real_T t25;
  real_T t26;
  real_T t27;
  real_T t28;
  real_T t29;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t40;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t55;
  real_T t56;
  real_T t57;
  real_T t58;
  real_T t59;
  real_T t60;
  real_T t61;
  real_T t62;
  real_T t63;
  real_T t64;
  real_T t65;
  real_T eval_tmp;
  real_T b_eval_tmp;
  real_T c_eval_tmp;
  real_T d_eval_tmp;
  real_T e_eval_tmp;
  real_T f_eval_tmp;
  real_T g_eval_tmp;
  real_T h_eval_tmp;
  real_T i_eval_tmp;
  real_T j_eval_tmp;
  real_T k_eval_tmp;
  real_T l_eval_tmp;
  real_T m_eval_tmp;
  real_T n_eval_tmp;
  real_T o_eval_tmp;
  real_T p_eval_tmp;
  real_T q_eval_tmp;
  real_T r_eval_tmp;
  real_T s_eval_tmp;
  real_T t_eval_tmp;
  real_T u_eval_tmp;
  real_T v_eval_tmp;
  real_T w_eval_tmp;
  real_T x_eval_tmp;
  real_T y_eval_tmp;
  real_T ab_eval_tmp;
  real_T bb_eval_tmp;
  real_T cb_eval_tmp;
  real_T db_eval_tmp;
  real_T eb_eval_tmp;
  real_T fb_eval_tmp;
  real_T gb_eval_tmp;
  real_T hb_eval_tmp;
  real_T ib_eval_tmp;
  real_T jb_eval_tmp;
  real_T kb_eval_tmp;
  real_T lb_eval_tmp;
  real_T mb_eval_tmp;
  real_T nb_eval_tmp;
  real_T ob_eval_tmp;
  real_T pb_eval_tmp;
  real_T qb_eval_tmp;

  /* AUTOEVAL */
  /*     [EVAL,DEVAL] = AUTOEVAL(IN1,IN2,QM,QMF,QT,QTF,IN7,WS,WR,IN10,IN11,BLD,IN13) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.5. */
  /*     18-Nov-2020 11:06:29 */
  t2 = in7[1] * in1[9];
  t3 = in7[1] * in1[21];
  t4 = in7[1] * in1[33];
  t5 = in7[1] * in1[45];
  t6 = in7[1] * in1[57];
  t7 = in7[1] * in1[69];
  t8 = in7[1] * in1[81];
  t9 = in7[1] * in1[93];
  t10 = in7[1] * in1[105];
  t11 = in7[1] * in1[117];
  t12 = in7[2] * in1[8];
  t13 = in7[2] * in1[20];
  t14 = in7[2] * in1[32];
  t15 = in7[2] * in1[44];
  t16 = in7[2] * in1[56];
  t17 = in7[2] * in1[68];
  t18 = in7[2] * in1[80];
  t19 = in7[2] * in1[92];
  t20 = in7[2] * in1[104];
  t21 = in7[2] * in1[116];
  t22 = in2[2] * in1[1];
  t23 = in2[2] * in1[13];
  t24 = in2[2] * in1[25];
  t25 = in2[2] * in1[37];
  t26 = in2[2] * in1[49];
  t27 = in2[2] * in1[61];
  t28 = in2[2] * in1[73];
  t29 = in2[2] * in1[85];
  t30 = in2[2] * in1[97];
  t31 = in2[1] * in1[5];
  t32 = in2[1] * in1[17];
  t33 = in2[1] * in1[29];
  t34 = in2[1] * in1[41];
  t35 = in2[1] * in1[53];
  t36 = in2[1] * in1[65];
  t37 = in2[1] * in1[77];
  t38 = in2[1] * in1[89];
  t39 = in2[1] * in1[101];
  t40 = in2[2] * in1[109];
  t41 = in2[2] * in1[121];
  t42 = in2[1] * in1[113];
  t43 = in2[1] * in1[125];
  t55 = in13[0] + -in1[4];
  t56 = in13[1] + -in1[16];
  t57 = in13[2] + -in1[28];
  t58 = in13[3] + -in1[40];
  t59 = in13[4] + -in1[52];
  t60 = in13[5] + -in1[64];
  t61 = in13[6] + -in1[76];
  t62 = in13[7] + -in1[88];
  t63 = in13[8] + -in1[100];
  t64 = in13[9] + -in1[112];
  t65 = in13[10] + -in1[124];
  eval_tmp = in2[0] * in1[1];
  b_eval_tmp = in2[3] * in1[5];
  c_eval_tmp = in7[0] * in1[8];
  d_eval_tmp = in7[3] * in1[9];
  e_eval_tmp = in2[0] * in1[13];
  f_eval_tmp = in2[3] * in1[17];
  g_eval_tmp = in7[0] * in1[20];
  h_eval_tmp = in7[3] * in1[21];
  i_eval_tmp = in2[0] * in1[25];
  j_eval_tmp = in2[3] * in1[29];
  k_eval_tmp = in7[0] * in1[32];
  l_eval_tmp = in7[3] * in1[33];
  m_eval_tmp = in2[0] * in1[37];
  n_eval_tmp = in2[3] * in1[41];
  o_eval_tmp = in7[0] * in1[44];
  p_eval_tmp = in7[3] * in1[45];
  q_eval_tmp = in2[0] * in1[49];
  r_eval_tmp = in2[3] * in1[53];
  s_eval_tmp = in7[0] * in1[56];
  t_eval_tmp = in7[3] * in1[57];
  u_eval_tmp = in2[0] * in1[61];
  v_eval_tmp = in2[3] * in1[65];
  w_eval_tmp = in7[0] * in1[68];
  x_eval_tmp = in7[3] * in1[69];
  y_eval_tmp = in2[0] * in1[73];
  ab_eval_tmp = in2[3] * in1[77];
  bb_eval_tmp = in7[0] * in1[80];
  cb_eval_tmp = in7[3] * in1[81];
  db_eval_tmp = in2[0] * in1[85];
  eb_eval_tmp = in2[3] * in1[89];
  fb_eval_tmp = in7[0] * in1[92];
  gb_eval_tmp = in7[3] * in1[93];
  hb_eval_tmp = in2[0] * in1[97];
  ib_eval_tmp = in2[3] * in1[101];
  jb_eval_tmp = in7[0] * in1[104];
  kb_eval_tmp = in7[3] * in1[105];
  lb_eval_tmp = in2[0] * in1[109];
  mb_eval_tmp = in2[3] * in1[113];
  nb_eval_tmp = in7[0] * in1[116];
  ob_eval_tmp = in7[3] * in1[117];
  pb_eval_tmp = in2[0] * in1[121];
  qb_eval_tmp = in2[3] * in1[125];
  *eval =
    (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
    (((((Qt * (t55 * t55) + Qt * (t56 * t56)) + Qt * (t57 * t57)) + Qt * (t58 *
    t58)) + Qt * (t59 * t59)) + Qt * (t60 * t60)) + Qt * (t61 * t61)) + Qt *
    (t62 * t62)) + Qt * (t63 * t63)) + Qt * (t64 * t64)) + Qtf * (t65 * t65)) +
    Wr * (in1[23] * in1[23])) + Wr * (in1[35] * in1[35])) + Wr * (in1[47] * in1
    [47])) + Wr * (in1[59] * in1[59])) + Wr * (in1[71] * in1[71])) + Wr * (in1
    [83] * in1[83])) + Wr * (in1[95] * in1[95])) + Wr * (in1[107] * in1[107])) +
    Wr * (in1[119] * in1[119])) + Wr * (in1[131] * in1[131])) + Ws * (in1[10] *
    in1[10])) + Ws * (in1[22] * in1[22])) + Ws * (in1[34] * in1[34])) + Ws *
    (in1[46] * in1[46])) + Ws * (in1[58] * in1[58])) + Ws * (in1[70] * in1[70]))
    + Ws * (in1[82] * in1[82])) + Ws * (in1[94] * in1[94])) + Ws * (in1[106] *
    in1[106])) + Ws * (in1[118] * in1[118])) + Qm * muDoubleScalarPower((BLD -
    in10[0] * 2.0) + in11[0], 4.0)) + Qm * muDoubleScalarPower((BLD - in10[1] *
    2.0) + in11[1], 4.0)) + Qm * muDoubleScalarPower((BLD - in10[2] * 2.0) +
    in11[2], 4.0)) + Qm * muDoubleScalarPower((BLD - in10[3] * 2.0) + in11[3],
    4.0)) + Qm * muDoubleScalarPower((BLD - in10[4] * 2.0) + in11[4], 4.0)) + Qm
    * muDoubleScalarPower((BLD - in10[5] * 2.0) + in11[5], 4.0)) + Qm *
    muDoubleScalarPower((BLD - in10[6] * 2.0) + in11[6], 4.0)) + Qm *
    muDoubleScalarPower((BLD - in10[7] * 2.0) + in11[7], 4.0)) + Qm *
    muDoubleScalarPower((BLD - in10[8] * 2.0) + in11[8], 4.0)) + Qm *
    muDoubleScalarPower((BLD - in10[9] * 2.0) + in11[9], 4.0)) + Qmf *
    muDoubleScalarPower((BLD - in10[10] * 2.0) + in11[10], 4.0)) + in1[9] * (t12
    + d_eval_tmp)) + in1[21] * (t13 + h_eval_tmp)) + in1[33] * (t14 + l_eval_tmp))
    + in1[45] * (t15 + p_eval_tmp)) + in1[57] * (t16 + t_eval_tmp)) + in1[69] *
    (t17 + x_eval_tmp)) + in1[81] * (t18 + cb_eval_tmp)) + in1[93] * (t19 +
    gb_eval_tmp)) + in1[105] * (t20 + kb_eval_tmp)) + in1[117] * (t21 +
    ob_eval_tmp)) + in1[8] * (t2 + c_eval_tmp)) + in1[20] * (t3 + g_eval_tmp)) +
    in1[32] * (t4 + k_eval_tmp)) + in1[44] * (t5 + o_eval_tmp)) + in1[56] * (t6
    + s_eval_tmp)) + in1[68] * (t7 + w_eval_tmp)) + in1[80] * (t8 + bb_eval_tmp))
    + in1[92] * (t9 + fb_eval_tmp)) + in1[104] * (t10 + jb_eval_tmp)) + in1[116]
    * (t11 + nb_eval_tmp)) + in1[1] * (t31 + eval_tmp)) + in1[13] * (t32 +
    e_eval_tmp)) + in1[25] * (t33 + i_eval_tmp)) + in1[37] * (t34 + m_eval_tmp))
                     + in1[49] * (t35 + q_eval_tmp)) + in1[61] * (t36 +
    u_eval_tmp)) + in1[73] * (t37 + y_eval_tmp)) + in1[85] * (t38 + db_eval_tmp))
                 + in1[97] * (t39 + hb_eval_tmp)) + in1[5] * (t22 + b_eval_tmp))
               + in1[17] * (t23 + f_eval_tmp)) + in1[29] * (t24 + j_eval_tmp)) +
             in1[41] * (t25 + n_eval_tmp)) + in1[53] * (t26 + r_eval_tmp)) +
           in1[65] * (t27 + v_eval_tmp)) + in1[77] * (t28 + ab_eval_tmp)) + in1
         [89] * (t29 + eb_eval_tmp)) + in1[101] * (t30 + ib_eval_tmp)) + in1[109]
       * (t42 + lb_eval_tmp)) + in1[121] * (t43 + pb_eval_tmp)) + in1[113] *
     (t40 + mb_eval_tmp)) + in1[125] * (t41 + qb_eval_tmp);
  deval[0] = 0.0;
  deval[1] = (t31 + eval_tmp * 2.0) + in2[2] * in1[5];
  deval[2] = 0.0;
  deval[3] = 0.0;
  deval[4] = Qt * t55 * -2.0;
  deval[5] = (t22 + in2[1] * in1[1]) + b_eval_tmp * 2.0;
  deval[6] = 0.0;
  deval[7] = 0.0;
  deval[8] = (t2 + in7[2] * in1[9]) + c_eval_tmp * 2.0;
  deval[9] = (t12 + d_eval_tmp * 2.0) + in7[1] * in1[8];
  deval[10] = Ws * in1[10] * 2.0;
  deval[11] = 0.0;
  deval[12] = 0.0;
  deval[13] = (t32 + e_eval_tmp * 2.0) + in2[2] * in1[17];
  deval[14] = 0.0;
  deval[15] = 0.0;
  deval[16] = Qt * t56 * -2.0;
  deval[17] = (t23 + in2[1] * in1[13]) + f_eval_tmp * 2.0;
  deval[18] = 0.0;
  deval[19] = 0.0;
  deval[20] = (t3 + in7[2] * in1[21]) + g_eval_tmp * 2.0;
  deval[21] = (t13 + h_eval_tmp * 2.0) + in7[1] * in1[20];
  deval[22] = Ws * in1[22] * 2.0;
  deval[23] = Wr * in1[23] * 2.0;
  deval[24] = 0.0;
  deval[25] = (t33 + i_eval_tmp * 2.0) + in2[2] * in1[29];
  deval[26] = 0.0;
  deval[27] = 0.0;
  deval[28] = Qt * t57 * -2.0;
  deval[29] = (t24 + in2[1] * in1[25]) + j_eval_tmp * 2.0;
  deval[30] = 0.0;
  deval[31] = 0.0;
  deval[32] = (t4 + in7[2] * in1[33]) + k_eval_tmp * 2.0;
  deval[33] = (t14 + l_eval_tmp * 2.0) + in7[1] * in1[32];
  deval[34] = Ws * in1[34] * 2.0;
  deval[35] = Wr * in1[35] * 2.0;
  deval[36] = 0.0;
  deval[37] = (t34 + m_eval_tmp * 2.0) + in2[2] * in1[41];
  deval[38] = 0.0;
  deval[39] = 0.0;
  deval[40] = Qt * t58 * -2.0;
  deval[41] = (t25 + in2[1] * in1[37]) + n_eval_tmp * 2.0;
  deval[42] = 0.0;
  deval[43] = 0.0;
  deval[44] = (t5 + in7[2] * in1[45]) + o_eval_tmp * 2.0;
  deval[45] = (t15 + p_eval_tmp * 2.0) + in7[1] * in1[44];
  deval[46] = Ws * in1[46] * 2.0;
  deval[47] = Wr * in1[47] * 2.0;
  deval[48] = 0.0;
  deval[49] = (t35 + q_eval_tmp * 2.0) + in2[2] * in1[53];
  deval[50] = 0.0;
  deval[51] = 0.0;
  deval[52] = Qt * t59 * -2.0;
  deval[53] = (t26 + in2[1] * in1[49]) + r_eval_tmp * 2.0;
  deval[54] = 0.0;
  deval[55] = 0.0;
  deval[56] = (t6 + in7[2] * in1[57]) + s_eval_tmp * 2.0;
  deval[57] = (t16 + t_eval_tmp * 2.0) + in7[1] * in1[56];
  deval[58] = Ws * in1[58] * 2.0;
  deval[59] = Wr * in1[59] * 2.0;
  deval[60] = 0.0;
  deval[61] = (t36 + u_eval_tmp * 2.0) + in2[2] * in1[65];
  deval[62] = 0.0;
  deval[63] = 0.0;
  deval[64] = Qt * t60 * -2.0;
  deval[65] = (t27 + in2[1] * in1[61]) + v_eval_tmp * 2.0;
  deval[66] = 0.0;
  deval[67] = 0.0;
  deval[68] = (t7 + in7[2] * in1[69]) + w_eval_tmp * 2.0;
  deval[69] = (t17 + x_eval_tmp * 2.0) + in7[1] * in1[68];
  deval[70] = Ws * in1[70] * 2.0;
  deval[71] = Wr * in1[71] * 2.0;
  deval[72] = 0.0;
  deval[73] = (t37 + y_eval_tmp * 2.0) + in2[2] * in1[77];
  deval[74] = 0.0;
  deval[75] = 0.0;
  deval[76] = Qt * t61 * -2.0;
  deval[77] = (t28 + in2[1] * in1[73]) + ab_eval_tmp * 2.0;
  deval[78] = 0.0;
  deval[79] = 0.0;
  deval[80] = (t8 + in7[2] * in1[81]) + bb_eval_tmp * 2.0;
  deval[81] = (t18 + cb_eval_tmp * 2.0) + in7[1] * in1[80];
  deval[82] = Ws * in1[82] * 2.0;
  deval[83] = Wr * in1[83] * 2.0;
  deval[84] = 0.0;
  deval[85] = (t38 + db_eval_tmp * 2.0) + in2[2] * in1[89];
  deval[86] = 0.0;
  deval[87] = 0.0;
  deval[88] = Qt * t62 * -2.0;
  deval[89] = (t29 + in2[1] * in1[85]) + eb_eval_tmp * 2.0;
  deval[90] = 0.0;
  deval[91] = 0.0;
  deval[92] = (t9 + in7[2] * in1[93]) + fb_eval_tmp * 2.0;
  deval[93] = (t19 + gb_eval_tmp * 2.0) + in7[1] * in1[92];
  deval[94] = Ws * in1[94] * 2.0;
  deval[95] = Wr * in1[95] * 2.0;
  deval[96] = 0.0;
  deval[97] = (t39 + hb_eval_tmp * 2.0) + in2[2] * in1[101];
  deval[98] = 0.0;
  deval[99] = 0.0;
  deval[100] = Qt * t63 * -2.0;
  deval[101] = (t30 + in2[1] * in1[97]) + ib_eval_tmp * 2.0;
  deval[102] = 0.0;
  deval[103] = 0.0;
  deval[104] = (t10 + in7[2] * in1[105]) + jb_eval_tmp * 2.0;
  deval[105] = (t20 + kb_eval_tmp * 2.0) + in7[1] * in1[104];
  deval[106] = Ws * in1[106] * 2.0;
  deval[107] = Wr * in1[107] * 2.0;
  deval[108] = 0.0;
  deval[109] = (t42 + lb_eval_tmp * 2.0) + in2[2] * in1[113];
  deval[110] = 0.0;
  deval[111] = 0.0;
  deval[112] = Qt * t64 * -2.0;
  deval[113] = (t40 + in2[1] * in1[109]) + mb_eval_tmp * 2.0;
  deval[114] = 0.0;
  deval[115] = 0.0;
  deval[116] = (t11 + in7[2] * in1[117]) + nb_eval_tmp * 2.0;
  deval[117] = (t21 + ob_eval_tmp * 2.0) + in7[1] * in1[116];
  deval[118] = Ws * in1[118] * 2.0;
  deval[119] = Wr * in1[119] * 2.0;
  deval[120] = 0.0;
  deval[121] = (t43 + pb_eval_tmp * 2.0) + in2[2] * in1[125];
  deval[122] = 0.0;
  deval[123] = 0.0;
  deval[124] = Qtf * t65 * -2.0;
  deval[125] = (t41 + in2[1] * in1[121]) + qb_eval_tmp * 2.0;
  deval[126] = 0.0;
  deval[127] = 0.0;
  deval[128] = 0.0;
  deval[129] = 0.0;
  deval[130] = 0.0;
  deval[131] = Wr * in1[131] * 2.0;
}

/* End of code generation (autoEval.c) */
