function cU1 = Ufp(in1,in2,in3,in4)
%UF
%    CU1 = UF(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Mar-2020 10:43:23

V1 = in3(:,1);
ddXd3 = in2(:,11);
gravity = in4(:,6);
m = in4(:,1);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = V1+ddXd3+gravity;
t7 = -t3;
t8 = -t4;
t9 = t2+t5+t7+t8;
t10 = 1.0./t9;
t11 = (m.*t6.*t10)./4.0;
cU1 = [t11;t11;t11;t11];
