function cZ2 = Z2(in1,in2,in3,in4)
%Z2
%    CZ2 = Z2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Jul-2020 16:47:44

V1 = in3(:,1);
Xd1 = in2(:,1);
dV1 = in3(:,2);
dXd1 = in2(:,5);
ddXd1 = in2(:,9);
ddXd3 = in2(:,11);
dddXd1 = in2(:,13);
dddXd3 = in2(:,15);
dp1 = in1(8,:);
gravity = in4(:,6);
o1 = in1(11,:);
o2 = in1(12,:);
o3 = in1(13,:);
p1 = in1(5,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = q0.*q2.*2.0;
t7 = q1.*q3.*2.0;
t8 = V1+ddXd3+gravity;
t9 = -t3;
t10 = -t4;
t11 = t6+t7;
t12 = t2+t5+t9+t10;
t13 = 1.0./t12;
t14 = t13.^2;
cZ2 = [-Xd1+p1;-dXd1+dp1;-ddXd1+t8.*t11.*t13;-dddXd1+(q0.*t8.*t13.*2.0+q2.*t8.*t11.*t14.*2.0).*((o2.*q0)./2.0+(o1.*q3)./2.0-(o3.*q1)./2.0)+(q1.*t8.*t13.*2.0-q3.*t8.*t11.*t14.*2.0).*(o1.*q2.*(-1.0./2.0)+(o2.*q1)./2.0+(o3.*q0)./2.0)-(q2.*t8.*t13.*2.0-q0.*t8.*t11.*t14.*2.0).*((o1.*q1)./2.0+(o2.*q2)./2.0+(o3.*q3)./2.0)+(q3.*t8.*t13.*2.0+q1.*t8.*t11.*t14.*2.0).*((o1.*q0)./2.0-(o2.*q3)./2.0+(o3.*q2)./2.0)+t11.*t13.*(dV1+dddXd3)];
