function U2 = H234_SuspendedLoad(obj,in1,in2,in3,in4,in5)
%H234_SUSPENDEDLOAD
%    U2 = H234_SUSPENDEDLOAD(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    15-Aug-2020 14:33:29

U2 = reshape([0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,3]);
