function Rotation = ZYXeuler(in1)
%ZYXEULER
%    ROTATION = ZYXEULER(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-Mar-2020 13:42:13

X1 = in1(1);
X2 = in1(2);
X3 = in1(3);
t2 = cos(X1);
t3 = cos(X2);
t4 = cos(X3);
t5 = sin(X1);
t6 = sin(X2);
t7 = sin(X3);
Rotation = reshape([t3.*t4,t3.*t7,-t6,-t2.*t7+t4.*t5.*t6,t2.*t4+t5.*t6.*t7,t3.*t5,t5.*t7+t2.*t4.*t6,-t4.*t5+t2.*t6.*t7,t2.*t3],[3,3]);
