function D = DeltahDiff(x,y,theta,v,omega,t,d1,alpha1,phi1)
%DELTAHDIFF
%    D = DELTAHDIFF(X,Y,THETA,V,OMEGA,T,D1,ALPHA1,PHI1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    18-Jun-2021 11:45:21

t2 = cos(alpha1);
t3 = sin(alpha1);
t4 = cos(theta);
t5 = sin(theta);
t6 = omega.*t;
t7 = -alpha1;
t8 = -d1;
t9 = t.*t4.*v;
t10 = t.*t5.*v;
t15 = phi1+t6+t7+theta;
t11 = t10+y;
t12 = t9+x;
t16 = cos(t15);
t13 = t2.*t12;
t14 = t3.*t11;
t17 = t8+t13+t14;
D = t.*1.0./t16.^2.*t17.*sin(t15).*((t8+t2.*x+t3.*y)./cos(phi1+t7+theta)-t17./t16).*-2.0;
