function PV = FIMOV_ObserbSubAOmegaRungeKutta(x,y,theta,v,omega,a,t,d1,alpha1,phi1)
%FIMOV_OBSERBSUBAOMEGARUNGEKUTTA
%    PV = FIMOV_OBSERBSUBAOMEGARUNGEKUTTA(X,Y,THETA,V,OMEGA,A,T,D1,ALPHA1,PHI1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    20-Dec-2021 13:55:52

t2 = omega+theta;
t3 = omega./2.0;
t4 = t3+theta;
PV = 1.0./cos(-alpha1+phi1+theta+omega.*t).^2.*((t.*sin(alpha1).*(sin(t2)+sin(t4).*4.0+sin(theta)))./6.0+(t.*cos(alpha1).*(cos(t2)+cos(t4).*4.0+cos(theta)))./6.0).^2;
