function Fomega = InputSouce(fai,alpha,theta,t)
%INPUTSOUCE
%    FOMEGA = INPUTSOUCE(FAI,ALPHA,THETA,T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2021 15:27:52

Fomega = zeros(0,1);
