function D = ObserveDiff(alpha1,alpha2,d1,d2,k1,k2,omega,phi1,phi2,t,theta,v,x,y)
%OBSERVEDIFF
%    D = OBSERVEDIFF(ALPHA1,ALPHA2,D1,D2,K1,K2,OMEGA,PHI1,PHI2,T,THETA,V,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Jun-2021 22:04:22

t2 = cos(alpha1);
t3 = cos(alpha2);
t4 = sin(alpha1);
t5 = sin(alpha2);
t6 = cos(theta);
t7 = sin(theta);
t8 = omega.*t;
t13 = -alpha1;
t14 = -alpha2;
t15 = -d1;
t16 = -d2;
t9 = t2.*x;
t10 = t3.*x;
t11 = t4.*y;
t12 = t5.*y;
t17 = t.*t6.*v;
t18 = t.*t7.*v;
t19 = phi1+t13+theta;
t20 = phi2+t14+theta;
t21 = t18+y;
t22 = t17+x;
t23 = cos(t19);
t24 = cos(t20);
t29 = t8+t19;
t30 = t8+t20;
t35 = t9+t11+t15;
t36 = t10+t12+t16;
t25 = t2.*t22;
t26 = t3.*t22;
t27 = t4.*t21;
t28 = t5.*t21;
t31 = cos(t29);
t32 = cos(t30);
t33 = 1.0./t23;
t34 = 1.0./t24;
t37 = 1.0./t31;
t38 = 1.0./t32;
t39 = t15+t25+t27;
t40 = t16+t26+t28;
t41 = t33.*t35;
t42 = t34.*t36;
t43 = t37.*t39;
t44 = t38.*t40;
t45 = -t43;
t46 = -t44;
t47 = t41+t45;
t48 = t42+t46;
D = (k1.*t.*t37.*t43.*t47.*sin(t29).*2.0+k2.*t.*t38.*t44.*t48.*sin(t30).*2.0).*1.0./(k1.*t47.^2+k2.*t48.^2).^2;
