function U2 = H234_SuspendedLoad_extend(in1,in2,in3,in4,in5)
%H234_SUSPENDEDLOAD_EXTEND
%    U2 = H234_SUSPENDEDLOAD_EXTEND(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Jan-2021 23:23:35

U2 = reshape([0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,3]);
