function H234 = H234_SuspendedLoad(in1,in2,in3,in4)
%H234_SuspendedLoad
%    H234 = H234_SuspendedLoad(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/04/30 19:59:55

H234 = reshape([0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,3]);
end
