function cZ1 = Z1_SuspendedLoad(in1,in2,in3)
%Z1_SuspendedLoad
%    cZ1 = Z1_SuspendedLoad(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/04/30 19:51:49

Xd3 = in2(:,3);
dpl3 = in1(13,:);
pl3 = in1(10,:);
cZ1 = [-Xd3+pl3;dpl3];
end
