/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * computeConstraints_.c
 *
 * Code generation for function 'computeConstraints_'
 *
 */

/* Include files */
#include "computeConstraints_.h"
#include "L_HL_MPCfunc.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Variable Definitions */
static emlrtRSInfo d_emlrtRSI = { 1,   /* lineNo */
  "computeConstraints_",               /* fcnName */
  "C:\\Program Files\\MATLAB\\R2020a\\toolbox\\optim\\+optim\\+coder\\+utils\\+ObjNonlinEvaluator\\computeConstraints_.p"/* pathName */
};

static emlrtBCInfo k_emlrtBCI = { 1,   /* iFirst */
  20,                                  /* iLast */
  1,                                   /* lineNo */
  1,                                   /* colNo */
  "",                                  /* aName */
  "checkVectorNonFinite",              /* fName */
  "C:\\Program Files\\MATLAB\\R2020a\\toolbox\\optim\\+optim\\+coder\\+utils\\+ObjNonlinEvaluator\\+internal\\checkVectorNonFinite.p",/* pName */
  0                                    /* checkKind */
};

static emlrtBCInfo l_emlrtBCI = { 1,   /* iFirst */
  88,                                  /* iLast */
  1,                                   /* lineNo */
  1,                                   /* colNo */
  "",                                  /* aName */
  "checkVectorNonFinite",              /* fName */
  "C:\\Program Files\\MATLAB\\R2020a\\toolbox\\optim\\+optim\\+coder\\+utils\\+ObjNonlinEvaluator\\+internal\\checkVectorNonFinite.p",/* pName */
  0                                    /* checkKind */
};

/* Function Definitions */
int32_T computeConstraints_(const emlrtStack *sp, const real_T
  c_obj_nonlcon_tunableEnvironmen[8], real_T d_obj_nonlcon_tunableEnvironmen,
  const real_T e_obj_nonlcon_tunableEnvironmen[64], const real_T
  f_obj_nonlcon_tunableEnvironmen[16], const real_T x[110], real_T
  Cineq_workspace[20], real_T Ceq_workspace[88])
{
  int32_T status;
  boolean_T allFinite;
  int32_T idx_current;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* LAUTOCONS */
  /*     [CINEQ,CEQ,DCINEQ,DCEQ] = LAUTOCONS(IN1,IN2,IN3,IN4,SR,IN6,IN7) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     02-Mar-2020 20:10:34 */
  Cineq_workspace[0] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [10] + x[0]);
  Cineq_workspace[1] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [20] + x[10]);
  Cineq_workspace[2] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [30] + x[20]);
  Cineq_workspace[3] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [40] + x[30]);
  Cineq_workspace[4] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [50] + x[40]);
  Cineq_workspace[5] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [60] + x[50]);
  Cineq_workspace[6] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [70] + x[60]);
  Cineq_workspace[7] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [80] + x[70]);
  Cineq_workspace[8] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [90] + x[80]);
  Cineq_workspace[9] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [100] + x[90]);
  Cineq_workspace[10] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [14] + x[4]);
  Cineq_workspace[11] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [24] + x[14]);
  Cineq_workspace[12] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [34] + x[24]);
  Cineq_workspace[13] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [44] + x[34]);
  Cineq_workspace[14] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [54] + x[44]);
  Cineq_workspace[15] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [64] + x[54]);
  Cineq_workspace[16] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [74] + x[64]);
  Cineq_workspace[17] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [84] + x[74]);
  Cineq_workspace[18] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [94] + x[84]);
  Cineq_workspace[19] = -d_obj_nonlcon_tunableEnvironmen + muDoubleScalarAbs(-x
    [104] + x[94]);
  Ceq_workspace[0] = -c_obj_nonlcon_tunableEnvironmen[0] + x[0];
  Ceq_workspace[1] = (((((((((x[10] + -e_obj_nonlcon_tunableEnvironmen[0] * x[0])
    + -e_obj_nonlcon_tunableEnvironmen[8] * x[1]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[2]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[3]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[4]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[5]) +
                        -e_obj_nonlcon_tunableEnvironmen[48] * x[6]) +
                       -e_obj_nonlcon_tunableEnvironmen[56] * x[7]) +
                      -f_obj_nonlcon_tunableEnvironmen[0] * x[8]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[9];
  Ceq_workspace[2] = (((((((((x[20] + -e_obj_nonlcon_tunableEnvironmen[0] * x[10])
    + -e_obj_nonlcon_tunableEnvironmen[8] * x[11]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[12]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[13]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[14]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[15]) +
                        -e_obj_nonlcon_tunableEnvironmen[48] * x[16]) +
                       -e_obj_nonlcon_tunableEnvironmen[56] * x[17]) +
                      -f_obj_nonlcon_tunableEnvironmen[0] * x[18]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[19];
  Ceq_workspace[3] = (((((((((x[30] + -e_obj_nonlcon_tunableEnvironmen[0] * x[20])
    + -e_obj_nonlcon_tunableEnvironmen[8] * x[21]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[22]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[23]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[24]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[25]) +
                        -e_obj_nonlcon_tunableEnvironmen[48] * x[26]) +
                       -e_obj_nonlcon_tunableEnvironmen[56] * x[27]) +
                      -f_obj_nonlcon_tunableEnvironmen[0] * x[28]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[29];
  Ceq_workspace[4] = (((((((((x[40] + -e_obj_nonlcon_tunableEnvironmen[0] * x[30])
    + -e_obj_nonlcon_tunableEnvironmen[8] * x[31]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[32]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[33]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[34]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[35]) +
                        -e_obj_nonlcon_tunableEnvironmen[48] * x[36]) +
                       -e_obj_nonlcon_tunableEnvironmen[56] * x[37]) +
                      -f_obj_nonlcon_tunableEnvironmen[0] * x[38]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[39];
  Ceq_workspace[5] = (((((((((x[50] + -e_obj_nonlcon_tunableEnvironmen[0] * x[40])
    + -e_obj_nonlcon_tunableEnvironmen[8] * x[41]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[42]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[43]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[44]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[45]) +
                        -e_obj_nonlcon_tunableEnvironmen[48] * x[46]) +
                       -e_obj_nonlcon_tunableEnvironmen[56] * x[47]) +
                      -f_obj_nonlcon_tunableEnvironmen[0] * x[48]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[49];
  Ceq_workspace[6] = (((((((((x[60] + -e_obj_nonlcon_tunableEnvironmen[0] * x[50])
    + -e_obj_nonlcon_tunableEnvironmen[8] * x[51]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[52]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[53]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[54]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[55]) +
                        -e_obj_nonlcon_tunableEnvironmen[48] * x[56]) +
                       -e_obj_nonlcon_tunableEnvironmen[56] * x[57]) +
                      -f_obj_nonlcon_tunableEnvironmen[0] * x[58]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[59];
  Ceq_workspace[7] = (((((((((x[70] + -e_obj_nonlcon_tunableEnvironmen[0] * x[60])
    + -e_obj_nonlcon_tunableEnvironmen[8] * x[61]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[62]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[63]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[64]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[65]) +
                        -e_obj_nonlcon_tunableEnvironmen[48] * x[66]) +
                       -e_obj_nonlcon_tunableEnvironmen[56] * x[67]) +
                      -f_obj_nonlcon_tunableEnvironmen[0] * x[68]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[69];
  Ceq_workspace[8] = (((((((((x[80] + -e_obj_nonlcon_tunableEnvironmen[0] * x[70])
    + -e_obj_nonlcon_tunableEnvironmen[8] * x[71]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[72]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[73]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[74]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[75]) +
                        -e_obj_nonlcon_tunableEnvironmen[48] * x[76]) +
                       -e_obj_nonlcon_tunableEnvironmen[56] * x[77]) +
                      -f_obj_nonlcon_tunableEnvironmen[0] * x[78]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[79];
  Ceq_workspace[9] = (((((((((x[90] + -e_obj_nonlcon_tunableEnvironmen[0] * x[80])
    + -e_obj_nonlcon_tunableEnvironmen[8] * x[81]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[82]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[83]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[84]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[85]) +
                        -e_obj_nonlcon_tunableEnvironmen[48] * x[86]) +
                       -e_obj_nonlcon_tunableEnvironmen[56] * x[87]) +
                      -f_obj_nonlcon_tunableEnvironmen[0] * x[88]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[89];
  Ceq_workspace[10] = (((((((((x[100] + -e_obj_nonlcon_tunableEnvironmen[0] * x
    [90]) + -e_obj_nonlcon_tunableEnvironmen[8] * x[91]) +
    -e_obj_nonlcon_tunableEnvironmen[16] * x[92]) +
    -e_obj_nonlcon_tunableEnvironmen[24] * x[93]) +
    -e_obj_nonlcon_tunableEnvironmen[32] * x[94]) +
    -e_obj_nonlcon_tunableEnvironmen[40] * x[95]) +
    -e_obj_nonlcon_tunableEnvironmen[48] * x[96]) +
                        -e_obj_nonlcon_tunableEnvironmen[56] * x[97]) +
                       -f_obj_nonlcon_tunableEnvironmen[0] * x[98]) +
    -f_obj_nonlcon_tunableEnvironmen[8] * x[99];
  Ceq_workspace[11] = -c_obj_nonlcon_tunableEnvironmen[1] + x[1];
  Ceq_workspace[12] = (((((((((x[11] + -e_obj_nonlcon_tunableEnvironmen[1] * x[0])
    + -e_obj_nonlcon_tunableEnvironmen[9] * x[1]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[2]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[3]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[4]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[5]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[6]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[7]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[8]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[9];
  Ceq_workspace[13] = (((((((((x[21] + -e_obj_nonlcon_tunableEnvironmen[1] * x
    [10]) + -e_obj_nonlcon_tunableEnvironmen[9] * x[11]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[12]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[13]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[14]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[15]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[16]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[17]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[18]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[19];
  Ceq_workspace[14] = (((((((((x[31] + -e_obj_nonlcon_tunableEnvironmen[1] * x
    [20]) + -e_obj_nonlcon_tunableEnvironmen[9] * x[21]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[22]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[23]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[24]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[25]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[26]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[27]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[28]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[29];
  Ceq_workspace[15] = (((((((((x[41] + -e_obj_nonlcon_tunableEnvironmen[1] * x
    [30]) + -e_obj_nonlcon_tunableEnvironmen[9] * x[31]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[32]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[33]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[34]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[35]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[36]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[37]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[38]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[39];
  Ceq_workspace[16] = (((((((((x[51] + -e_obj_nonlcon_tunableEnvironmen[1] * x
    [40]) + -e_obj_nonlcon_tunableEnvironmen[9] * x[41]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[42]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[43]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[44]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[45]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[46]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[47]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[48]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[49];
  Ceq_workspace[17] = (((((((((x[61] + -e_obj_nonlcon_tunableEnvironmen[1] * x
    [50]) + -e_obj_nonlcon_tunableEnvironmen[9] * x[51]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[52]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[53]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[54]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[55]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[56]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[57]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[58]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[59];
  Ceq_workspace[18] = (((((((((x[71] + -e_obj_nonlcon_tunableEnvironmen[1] * x
    [60]) + -e_obj_nonlcon_tunableEnvironmen[9] * x[61]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[62]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[63]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[64]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[65]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[66]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[67]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[68]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[69];
  Ceq_workspace[19] = (((((((((x[81] + -e_obj_nonlcon_tunableEnvironmen[1] * x
    [70]) + -e_obj_nonlcon_tunableEnvironmen[9] * x[71]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[72]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[73]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[74]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[75]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[76]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[77]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[78]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[79];
  Ceq_workspace[20] = (((((((((x[91] + -e_obj_nonlcon_tunableEnvironmen[1] * x
    [80]) + -e_obj_nonlcon_tunableEnvironmen[9] * x[81]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[82]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[83]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[84]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[85]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[86]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[87]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[88]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[89];
  Ceq_workspace[21] = (((((((((x[101] + -e_obj_nonlcon_tunableEnvironmen[1] * x
    [90]) + -e_obj_nonlcon_tunableEnvironmen[9] * x[91]) +
    -e_obj_nonlcon_tunableEnvironmen[17] * x[92]) +
    -e_obj_nonlcon_tunableEnvironmen[25] * x[93]) +
    -e_obj_nonlcon_tunableEnvironmen[33] * x[94]) +
    -e_obj_nonlcon_tunableEnvironmen[41] * x[95]) +
    -e_obj_nonlcon_tunableEnvironmen[49] * x[96]) +
                        -e_obj_nonlcon_tunableEnvironmen[57] * x[97]) +
                       -f_obj_nonlcon_tunableEnvironmen[1] * x[98]) +
    -f_obj_nonlcon_tunableEnvironmen[9] * x[99];
  Ceq_workspace[22] = -c_obj_nonlcon_tunableEnvironmen[2] + x[2];
  Ceq_workspace[23] = (((((((((x[12] + -e_obj_nonlcon_tunableEnvironmen[2] * x[0])
    + -e_obj_nonlcon_tunableEnvironmen[10] * x[1]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[2]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[3]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[4]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[5]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[6]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[7]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[8]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[9];
  Ceq_workspace[24] = (((((((((x[22] + -e_obj_nonlcon_tunableEnvironmen[2] * x
    [10]) + -e_obj_nonlcon_tunableEnvironmen[10] * x[11]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[12]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[13]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[14]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[15]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[16]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[17]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[18]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[19];
  Ceq_workspace[25] = (((((((((x[32] + -e_obj_nonlcon_tunableEnvironmen[2] * x
    [20]) + -e_obj_nonlcon_tunableEnvironmen[10] * x[21]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[22]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[23]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[24]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[25]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[26]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[27]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[28]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[29];
  Ceq_workspace[26] = (((((((((x[42] + -e_obj_nonlcon_tunableEnvironmen[2] * x
    [30]) + -e_obj_nonlcon_tunableEnvironmen[10] * x[31]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[32]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[33]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[34]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[35]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[36]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[37]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[38]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[39];
  Ceq_workspace[27] = (((((((((x[52] + -e_obj_nonlcon_tunableEnvironmen[2] * x
    [40]) + -e_obj_nonlcon_tunableEnvironmen[10] * x[41]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[42]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[43]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[44]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[45]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[46]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[47]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[48]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[49];
  Ceq_workspace[28] = (((((((((x[62] + -e_obj_nonlcon_tunableEnvironmen[2] * x
    [50]) + -e_obj_nonlcon_tunableEnvironmen[10] * x[51]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[52]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[53]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[54]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[55]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[56]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[57]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[58]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[59];
  Ceq_workspace[29] = (((((((((x[72] + -e_obj_nonlcon_tunableEnvironmen[2] * x
    [60]) + -e_obj_nonlcon_tunableEnvironmen[10] * x[61]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[62]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[63]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[64]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[65]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[66]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[67]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[68]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[69];
  Ceq_workspace[30] = (((((((((x[82] + -e_obj_nonlcon_tunableEnvironmen[2] * x
    [70]) + -e_obj_nonlcon_tunableEnvironmen[10] * x[71]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[72]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[73]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[74]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[75]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[76]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[77]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[78]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[79];
  Ceq_workspace[31] = (((((((((x[92] + -e_obj_nonlcon_tunableEnvironmen[2] * x
    [80]) + -e_obj_nonlcon_tunableEnvironmen[10] * x[81]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[82]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[83]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[84]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[85]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[86]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[87]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[88]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[89];
  Ceq_workspace[32] = (((((((((x[102] + -e_obj_nonlcon_tunableEnvironmen[2] * x
    [90]) + -e_obj_nonlcon_tunableEnvironmen[10] * x[91]) +
    -e_obj_nonlcon_tunableEnvironmen[18] * x[92]) +
    -e_obj_nonlcon_tunableEnvironmen[26] * x[93]) +
    -e_obj_nonlcon_tunableEnvironmen[34] * x[94]) +
    -e_obj_nonlcon_tunableEnvironmen[42] * x[95]) +
    -e_obj_nonlcon_tunableEnvironmen[50] * x[96]) +
                        -e_obj_nonlcon_tunableEnvironmen[58] * x[97]) +
                       -f_obj_nonlcon_tunableEnvironmen[2] * x[98]) +
    -f_obj_nonlcon_tunableEnvironmen[10] * x[99];
  Ceq_workspace[33] = -c_obj_nonlcon_tunableEnvironmen[3] + x[3];
  Ceq_workspace[34] = (((((((((x[13] + -e_obj_nonlcon_tunableEnvironmen[3] * x[0])
    + -e_obj_nonlcon_tunableEnvironmen[11] * x[1]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[2]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[3]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[4]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[5]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[6]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[7]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[8]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[9];
  Ceq_workspace[35] = (((((((((x[23] + -e_obj_nonlcon_tunableEnvironmen[3] * x
    [10]) + -e_obj_nonlcon_tunableEnvironmen[11] * x[11]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[12]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[13]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[14]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[15]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[16]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[17]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[18]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[19];
  Ceq_workspace[36] = (((((((((x[33] + -e_obj_nonlcon_tunableEnvironmen[3] * x
    [20]) + -e_obj_nonlcon_tunableEnvironmen[11] * x[21]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[22]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[23]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[24]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[25]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[26]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[27]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[28]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[29];
  Ceq_workspace[37] = (((((((((x[43] + -e_obj_nonlcon_tunableEnvironmen[3] * x
    [30]) + -e_obj_nonlcon_tunableEnvironmen[11] * x[31]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[32]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[33]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[34]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[35]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[36]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[37]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[38]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[39];
  Ceq_workspace[38] = (((((((((x[53] + -e_obj_nonlcon_tunableEnvironmen[3] * x
    [40]) + -e_obj_nonlcon_tunableEnvironmen[11] * x[41]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[42]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[43]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[44]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[45]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[46]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[47]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[48]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[49];
  Ceq_workspace[39] = (((((((((x[63] + -e_obj_nonlcon_tunableEnvironmen[3] * x
    [50]) + -e_obj_nonlcon_tunableEnvironmen[11] * x[51]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[52]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[53]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[54]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[55]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[56]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[57]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[58]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[59];
  Ceq_workspace[40] = (((((((((x[73] + -e_obj_nonlcon_tunableEnvironmen[3] * x
    [60]) + -e_obj_nonlcon_tunableEnvironmen[11] * x[61]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[62]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[63]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[64]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[65]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[66]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[67]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[68]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[69];
  Ceq_workspace[41] = (((((((((x[83] + -e_obj_nonlcon_tunableEnvironmen[3] * x
    [70]) + -e_obj_nonlcon_tunableEnvironmen[11] * x[71]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[72]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[73]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[74]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[75]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[76]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[77]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[78]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[79];
  Ceq_workspace[42] = (((((((((x[93] + -e_obj_nonlcon_tunableEnvironmen[3] * x
    [80]) + -e_obj_nonlcon_tunableEnvironmen[11] * x[81]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[82]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[83]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[84]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[85]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[86]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[87]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[88]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[89];
  Ceq_workspace[43] = (((((((((x[103] + -e_obj_nonlcon_tunableEnvironmen[3] * x
    [90]) + -e_obj_nonlcon_tunableEnvironmen[11] * x[91]) +
    -e_obj_nonlcon_tunableEnvironmen[19] * x[92]) +
    -e_obj_nonlcon_tunableEnvironmen[27] * x[93]) +
    -e_obj_nonlcon_tunableEnvironmen[35] * x[94]) +
    -e_obj_nonlcon_tunableEnvironmen[43] * x[95]) +
    -e_obj_nonlcon_tunableEnvironmen[51] * x[96]) +
                        -e_obj_nonlcon_tunableEnvironmen[59] * x[97]) +
                       -f_obj_nonlcon_tunableEnvironmen[3] * x[98]) +
    -f_obj_nonlcon_tunableEnvironmen[11] * x[99];
  Ceq_workspace[44] = -c_obj_nonlcon_tunableEnvironmen[4] + x[4];
  Ceq_workspace[45] = (((((((((x[14] + -e_obj_nonlcon_tunableEnvironmen[4] * x[0])
    + -e_obj_nonlcon_tunableEnvironmen[12] * x[1]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[2]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[3]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[4]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[5]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[6]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[7]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[8]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[9];
  Ceq_workspace[46] = (((((((((x[24] + -e_obj_nonlcon_tunableEnvironmen[4] * x
    [10]) + -e_obj_nonlcon_tunableEnvironmen[12] * x[11]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[12]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[13]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[14]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[15]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[16]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[17]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[18]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[19];
  Ceq_workspace[47] = (((((((((x[34] + -e_obj_nonlcon_tunableEnvironmen[4] * x
    [20]) + -e_obj_nonlcon_tunableEnvironmen[12] * x[21]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[22]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[23]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[24]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[25]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[26]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[27]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[28]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[29];
  Ceq_workspace[48] = (((((((((x[44] + -e_obj_nonlcon_tunableEnvironmen[4] * x
    [30]) + -e_obj_nonlcon_tunableEnvironmen[12] * x[31]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[32]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[33]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[34]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[35]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[36]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[37]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[38]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[39];
  Ceq_workspace[49] = (((((((((x[54] + -e_obj_nonlcon_tunableEnvironmen[4] * x
    [40]) + -e_obj_nonlcon_tunableEnvironmen[12] * x[41]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[42]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[43]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[44]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[45]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[46]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[47]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[48]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[49];
  Ceq_workspace[50] = (((((((((x[64] + -e_obj_nonlcon_tunableEnvironmen[4] * x
    [50]) + -e_obj_nonlcon_tunableEnvironmen[12] * x[51]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[52]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[53]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[54]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[55]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[56]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[57]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[58]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[59];
  Ceq_workspace[51] = (((((((((x[74] + -e_obj_nonlcon_tunableEnvironmen[4] * x
    [60]) + -e_obj_nonlcon_tunableEnvironmen[12] * x[61]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[62]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[63]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[64]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[65]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[66]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[67]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[68]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[69];
  Ceq_workspace[52] = (((((((((x[84] + -e_obj_nonlcon_tunableEnvironmen[4] * x
    [70]) + -e_obj_nonlcon_tunableEnvironmen[12] * x[71]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[72]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[73]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[74]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[75]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[76]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[77]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[78]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[79];
  Ceq_workspace[53] = (((((((((x[94] + -e_obj_nonlcon_tunableEnvironmen[4] * x
    [80]) + -e_obj_nonlcon_tunableEnvironmen[12] * x[81]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[82]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[83]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[84]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[85]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[86]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[87]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[88]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[89];
  Ceq_workspace[54] = (((((((((x[104] + -e_obj_nonlcon_tunableEnvironmen[4] * x
    [90]) + -e_obj_nonlcon_tunableEnvironmen[12] * x[91]) +
    -e_obj_nonlcon_tunableEnvironmen[20] * x[92]) +
    -e_obj_nonlcon_tunableEnvironmen[28] * x[93]) +
    -e_obj_nonlcon_tunableEnvironmen[36] * x[94]) +
    -e_obj_nonlcon_tunableEnvironmen[44] * x[95]) +
    -e_obj_nonlcon_tunableEnvironmen[52] * x[96]) +
                        -e_obj_nonlcon_tunableEnvironmen[60] * x[97]) +
                       -f_obj_nonlcon_tunableEnvironmen[4] * x[98]) +
    -f_obj_nonlcon_tunableEnvironmen[12] * x[99];
  Ceq_workspace[55] = -c_obj_nonlcon_tunableEnvironmen[5] + x[5];
  Ceq_workspace[56] = (((((((((x[15] + -e_obj_nonlcon_tunableEnvironmen[5] * x[0])
    + -e_obj_nonlcon_tunableEnvironmen[13] * x[1]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[2]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[3]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[4]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[5]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[6]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[7]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[8]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[9];
  Ceq_workspace[57] = (((((((((x[25] + -e_obj_nonlcon_tunableEnvironmen[5] * x
    [10]) + -e_obj_nonlcon_tunableEnvironmen[13] * x[11]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[12]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[13]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[14]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[15]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[16]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[17]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[18]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[19];
  Ceq_workspace[58] = (((((((((x[35] + -e_obj_nonlcon_tunableEnvironmen[5] * x
    [20]) + -e_obj_nonlcon_tunableEnvironmen[13] * x[21]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[22]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[23]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[24]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[25]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[26]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[27]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[28]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[29];
  Ceq_workspace[59] = (((((((((x[45] + -e_obj_nonlcon_tunableEnvironmen[5] * x
    [30]) + -e_obj_nonlcon_tunableEnvironmen[13] * x[31]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[32]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[33]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[34]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[35]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[36]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[37]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[38]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[39];
  Ceq_workspace[60] = (((((((((x[55] + -e_obj_nonlcon_tunableEnvironmen[5] * x
    [40]) + -e_obj_nonlcon_tunableEnvironmen[13] * x[41]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[42]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[43]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[44]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[45]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[46]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[47]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[48]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[49];
  Ceq_workspace[61] = (((((((((x[65] + -e_obj_nonlcon_tunableEnvironmen[5] * x
    [50]) + -e_obj_nonlcon_tunableEnvironmen[13] * x[51]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[52]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[53]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[54]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[55]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[56]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[57]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[58]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[59];
  Ceq_workspace[62] = (((((((((x[75] + -e_obj_nonlcon_tunableEnvironmen[5] * x
    [60]) + -e_obj_nonlcon_tunableEnvironmen[13] * x[61]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[62]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[63]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[64]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[65]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[66]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[67]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[68]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[69];
  Ceq_workspace[63] = (((((((((x[85] + -e_obj_nonlcon_tunableEnvironmen[5] * x
    [70]) + -e_obj_nonlcon_tunableEnvironmen[13] * x[71]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[72]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[73]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[74]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[75]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[76]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[77]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[78]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[79];
  Ceq_workspace[64] = (((((((((x[95] + -e_obj_nonlcon_tunableEnvironmen[5] * x
    [80]) + -e_obj_nonlcon_tunableEnvironmen[13] * x[81]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[82]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[83]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[84]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[85]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[86]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[87]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[88]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[89];
  Ceq_workspace[65] = (((((((((x[105] + -e_obj_nonlcon_tunableEnvironmen[5] * x
    [90]) + -e_obj_nonlcon_tunableEnvironmen[13] * x[91]) +
    -e_obj_nonlcon_tunableEnvironmen[21] * x[92]) +
    -e_obj_nonlcon_tunableEnvironmen[29] * x[93]) +
    -e_obj_nonlcon_tunableEnvironmen[37] * x[94]) +
    -e_obj_nonlcon_tunableEnvironmen[45] * x[95]) +
    -e_obj_nonlcon_tunableEnvironmen[53] * x[96]) +
                        -e_obj_nonlcon_tunableEnvironmen[61] * x[97]) +
                       -f_obj_nonlcon_tunableEnvironmen[5] * x[98]) +
    -f_obj_nonlcon_tunableEnvironmen[13] * x[99];
  Ceq_workspace[66] = -c_obj_nonlcon_tunableEnvironmen[6] + x[6];
  Ceq_workspace[67] = (((((((((x[16] + -e_obj_nonlcon_tunableEnvironmen[6] * x[0])
    + -e_obj_nonlcon_tunableEnvironmen[14] * x[1]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[2]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[3]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[4]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[5]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[6]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[7]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[8]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[9];
  Ceq_workspace[68] = (((((((((x[26] + -e_obj_nonlcon_tunableEnvironmen[6] * x
    [10]) + -e_obj_nonlcon_tunableEnvironmen[14] * x[11]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[12]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[13]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[14]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[15]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[16]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[17]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[18]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[19];
  Ceq_workspace[69] = (((((((((x[36] + -e_obj_nonlcon_tunableEnvironmen[6] * x
    [20]) + -e_obj_nonlcon_tunableEnvironmen[14] * x[21]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[22]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[23]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[24]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[25]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[26]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[27]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[28]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[29];
  Ceq_workspace[70] = (((((((((x[46] + -e_obj_nonlcon_tunableEnvironmen[6] * x
    [30]) + -e_obj_nonlcon_tunableEnvironmen[14] * x[31]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[32]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[33]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[34]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[35]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[36]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[37]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[38]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[39];
  Ceq_workspace[71] = (((((((((x[56] + -e_obj_nonlcon_tunableEnvironmen[6] * x
    [40]) + -e_obj_nonlcon_tunableEnvironmen[14] * x[41]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[42]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[43]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[44]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[45]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[46]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[47]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[48]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[49];
  Ceq_workspace[72] = (((((((((x[66] + -e_obj_nonlcon_tunableEnvironmen[6] * x
    [50]) + -e_obj_nonlcon_tunableEnvironmen[14] * x[51]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[52]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[53]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[54]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[55]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[56]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[57]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[58]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[59];
  Ceq_workspace[73] = (((((((((x[76] + -e_obj_nonlcon_tunableEnvironmen[6] * x
    [60]) + -e_obj_nonlcon_tunableEnvironmen[14] * x[61]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[62]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[63]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[64]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[65]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[66]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[67]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[68]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[69];
  Ceq_workspace[74] = (((((((((x[86] + -e_obj_nonlcon_tunableEnvironmen[6] * x
    [70]) + -e_obj_nonlcon_tunableEnvironmen[14] * x[71]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[72]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[73]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[74]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[75]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[76]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[77]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[78]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[79];
  Ceq_workspace[75] = (((((((((x[96] + -e_obj_nonlcon_tunableEnvironmen[6] * x
    [80]) + -e_obj_nonlcon_tunableEnvironmen[14] * x[81]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[82]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[83]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[84]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[85]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[86]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[87]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[88]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[89];
  Ceq_workspace[76] = (((((((((x[106] + -e_obj_nonlcon_tunableEnvironmen[6] * x
    [90]) + -e_obj_nonlcon_tunableEnvironmen[14] * x[91]) +
    -e_obj_nonlcon_tunableEnvironmen[22] * x[92]) +
    -e_obj_nonlcon_tunableEnvironmen[30] * x[93]) +
    -e_obj_nonlcon_tunableEnvironmen[38] * x[94]) +
    -e_obj_nonlcon_tunableEnvironmen[46] * x[95]) +
    -e_obj_nonlcon_tunableEnvironmen[54] * x[96]) +
                        -e_obj_nonlcon_tunableEnvironmen[62] * x[97]) +
                       -f_obj_nonlcon_tunableEnvironmen[6] * x[98]) +
    -f_obj_nonlcon_tunableEnvironmen[14] * x[99];
  Ceq_workspace[77] = -c_obj_nonlcon_tunableEnvironmen[7] + x[7];
  Ceq_workspace[78] = (((((((((x[17] + -e_obj_nonlcon_tunableEnvironmen[7] * x[0])
    + -e_obj_nonlcon_tunableEnvironmen[15] * x[1]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[2]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[3]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[4]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[5]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[6]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[7]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[8]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[9];
  Ceq_workspace[79] = (((((((((x[27] + -e_obj_nonlcon_tunableEnvironmen[7] * x
    [10]) + -e_obj_nonlcon_tunableEnvironmen[15] * x[11]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[12]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[13]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[14]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[15]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[16]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[17]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[18]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[19];
  Ceq_workspace[80] = (((((((((x[37] + -e_obj_nonlcon_tunableEnvironmen[7] * x
    [20]) + -e_obj_nonlcon_tunableEnvironmen[15] * x[21]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[22]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[23]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[24]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[25]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[26]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[27]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[28]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[29];
  Ceq_workspace[81] = (((((((((x[47] + -e_obj_nonlcon_tunableEnvironmen[7] * x
    [30]) + -e_obj_nonlcon_tunableEnvironmen[15] * x[31]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[32]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[33]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[34]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[35]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[36]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[37]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[38]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[39];
  Ceq_workspace[82] = (((((((((x[57] + -e_obj_nonlcon_tunableEnvironmen[7] * x
    [40]) + -e_obj_nonlcon_tunableEnvironmen[15] * x[41]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[42]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[43]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[44]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[45]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[46]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[47]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[48]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[49];
  Ceq_workspace[83] = (((((((((x[67] + -e_obj_nonlcon_tunableEnvironmen[7] * x
    [50]) + -e_obj_nonlcon_tunableEnvironmen[15] * x[51]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[52]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[53]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[54]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[55]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[56]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[57]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[58]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[59];
  Ceq_workspace[84] = (((((((((x[77] + -e_obj_nonlcon_tunableEnvironmen[7] * x
    [60]) + -e_obj_nonlcon_tunableEnvironmen[15] * x[61]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[62]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[63]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[64]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[65]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[66]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[67]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[68]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[69];
  Ceq_workspace[85] = (((((((((x[87] + -e_obj_nonlcon_tunableEnvironmen[7] * x
    [70]) + -e_obj_nonlcon_tunableEnvironmen[15] * x[71]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[72]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[73]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[74]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[75]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[76]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[77]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[78]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[79];
  Ceq_workspace[86] = (((((((((x[97] + -e_obj_nonlcon_tunableEnvironmen[7] * x
    [80]) + -e_obj_nonlcon_tunableEnvironmen[15] * x[81]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[82]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[83]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[84]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[85]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[86]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[87]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[88]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[89];
  Ceq_workspace[87] = (((((((((x[107] + -e_obj_nonlcon_tunableEnvironmen[7] * x
    [90]) + -e_obj_nonlcon_tunableEnvironmen[15] * x[91]) +
    -e_obj_nonlcon_tunableEnvironmen[23] * x[92]) +
    -e_obj_nonlcon_tunableEnvironmen[31] * x[93]) +
    -e_obj_nonlcon_tunableEnvironmen[39] * x[94]) +
    -e_obj_nonlcon_tunableEnvironmen[47] * x[95]) +
    -e_obj_nonlcon_tunableEnvironmen[55] * x[96]) +
                        -e_obj_nonlcon_tunableEnvironmen[63] * x[97]) +
                       -f_obj_nonlcon_tunableEnvironmen[7] * x[98]) +
    -f_obj_nonlcon_tunableEnvironmen[15] * x[99];
  st.site = &d_emlrtRSI;
  status = 1;
  allFinite = true;
  idx_current = 0;
  while (allFinite && (idx_current + 1 <= 20)) {
    allFinite = ((!muDoubleScalarIsInf(Cineq_workspace[idx_current])) &&
                 (!muDoubleScalarIsNaN(Cineq_workspace[idx_current])));
    idx_current++;
  }

  if (!allFinite) {
    if ((idx_current < 1) || (idx_current > 20)) {
      emlrtDynamicBoundsCheckR2012b(idx_current, 1, 20, &k_emlrtBCI, &st);
    }

    if (muDoubleScalarIsNaN(Cineq_workspace[idx_current - 1])) {
      status = -3;
    } else if (Cineq_workspace[idx_current - 1] < 0.0) {
      status = -1;
    } else {
      status = -2;
    }
  }

  if (status == 1) {
    st.site = &d_emlrtRSI;
    allFinite = true;
    idx_current = 0;
    while (allFinite && (idx_current + 1 <= 88)) {
      allFinite = ((!muDoubleScalarIsInf(Ceq_workspace[idx_current])) &&
                   (!muDoubleScalarIsNaN(Ceq_workspace[idx_current])));
      idx_current++;
    }

    if (!allFinite) {
      if ((idx_current < 1) || (idx_current > 88)) {
        emlrtDynamicBoundsCheckR2012b(idx_current, 1, 88, &l_emlrtBCI, &st);
      }

      if (muDoubleScalarIsNaN(Ceq_workspace[idx_current - 1])) {
        status = -3;
      } else if (Ceq_workspace[idx_current - 1] < 0.0) {
        status = -1;
      } else {
        status = -2;
      }
    }
  }

  return status;
}

/* End of code generation (computeConstraints_.c) */
