/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * finDiffEvalAndChkErr.c
 *
 * Code generation for function 'finDiffEvalAndChkErr'
 *
 */

/* Include files */
#include "finDiffEvalAndChkErr.h"
#include "L_HL_MPCfunc.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include <string.h>

/* Function Definitions */
boolean_T finDiffEvalAndChkErr(const struct0_T obj_objfun_tunableEnvironment[1],
  const real_T c_obj_nonlin_tunableEnvironment[8], real_T
  d_obj_nonlin_tunableEnvironment, const real_T e_obj_nonlin_tunableEnvironment
  [64], const real_T f_obj_nonlin_tunableEnvironment[16], real_T *fplus, real_T
  cIneqPlus[20], real_T cEqPlus[88], int32_T dim, real_T delta, real_T xk[110])
{
  boolean_T evalOK;
  real_T temp_tmp;
  real_T varargout_1[20];
  int32_T idx;
  temp_tmp = xk[dim - 1];
  xk[dim - 1] = temp_tmp + delta;
  *fplus = __anon_fcn(obj_objfun_tunableEnvironment[0].Q,
                      obj_objfun_tunableEnvironment[0].Qf,
                      obj_objfun_tunableEnvironment[0].R,
                      obj_objfun_tunableEnvironment[0].Xr, xk);
  evalOK = ((!muDoubleScalarIsInf(*fplus)) && (!muDoubleScalarIsNaN(*fplus)));
  if (evalOK) {
    /* LAUTOCONS */
    /*     [CINEQ,CEQ,DCINEQ,DCEQ] = LAUTOCONS(IN1,IN2,IN3,IN4,SR,IN6,IN7) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
    /*     02-Mar-2020 20:10:34 */
    varargout_1[0] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk[10]
      + xk[0]);
    varargout_1[1] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk[20]
      + xk[10]);
    varargout_1[2] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk[30]
      + xk[20]);
    varargout_1[3] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk[40]
      + xk[30]);
    varargout_1[4] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk[50]
      + xk[40]);
    varargout_1[5] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk[60]
      + xk[50]);
    varargout_1[6] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk[70]
      + xk[60]);
    varargout_1[7] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk[80]
      + xk[70]);
    varargout_1[8] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk[90]
      + xk[80]);
    varargout_1[9] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [100] + xk[90]);
    varargout_1[10] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [14] + xk[4]);
    varargout_1[11] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [24] + xk[14]);
    varargout_1[12] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [34] + xk[24]);
    varargout_1[13] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [44] + xk[34]);
    varargout_1[14] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [54] + xk[44]);
    varargout_1[15] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [64] + xk[54]);
    varargout_1[16] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [74] + xk[64]);
    varargout_1[17] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [84] + xk[74]);
    varargout_1[18] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [94] + xk[84]);
    varargout_1[19] = -d_obj_nonlin_tunableEnvironment + muDoubleScalarAbs(-xk
      [104] + xk[94]);
    cEqPlus[0] = -c_obj_nonlin_tunableEnvironment[0] + xk[0];
    cEqPlus[1] = (((((((((xk[10] + -e_obj_nonlin_tunableEnvironment[0] * xk[0])
                         + -e_obj_nonlin_tunableEnvironment[8] * xk[1]) +
                        -e_obj_nonlin_tunableEnvironment[16] * xk[2]) +
                       -e_obj_nonlin_tunableEnvironment[24] * xk[3]) +
                      -e_obj_nonlin_tunableEnvironment[32] * xk[4]) +
                     -e_obj_nonlin_tunableEnvironment[40] * xk[5]) +
                    -e_obj_nonlin_tunableEnvironment[48] * xk[6]) +
                   -e_obj_nonlin_tunableEnvironment[56] * xk[7]) +
                  -f_obj_nonlin_tunableEnvironment[0] * xk[8]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[9];
    cEqPlus[2] = (((((((((xk[20] + -e_obj_nonlin_tunableEnvironment[0] * xk[10])
                         + -e_obj_nonlin_tunableEnvironment[8] * xk[11]) +
                        -e_obj_nonlin_tunableEnvironment[16] * xk[12]) +
                       -e_obj_nonlin_tunableEnvironment[24] * xk[13]) +
                      -e_obj_nonlin_tunableEnvironment[32] * xk[14]) +
                     -e_obj_nonlin_tunableEnvironment[40] * xk[15]) +
                    -e_obj_nonlin_tunableEnvironment[48] * xk[16]) +
                   -e_obj_nonlin_tunableEnvironment[56] * xk[17]) +
                  -f_obj_nonlin_tunableEnvironment[0] * xk[18]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[19];
    cEqPlus[3] = (((((((((xk[30] + -e_obj_nonlin_tunableEnvironment[0] * xk[20])
                         + -e_obj_nonlin_tunableEnvironment[8] * xk[21]) +
                        -e_obj_nonlin_tunableEnvironment[16] * xk[22]) +
                       -e_obj_nonlin_tunableEnvironment[24] * xk[23]) +
                      -e_obj_nonlin_tunableEnvironment[32] * xk[24]) +
                     -e_obj_nonlin_tunableEnvironment[40] * xk[25]) +
                    -e_obj_nonlin_tunableEnvironment[48] * xk[26]) +
                   -e_obj_nonlin_tunableEnvironment[56] * xk[27]) +
                  -f_obj_nonlin_tunableEnvironment[0] * xk[28]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[29];
    cEqPlus[4] = (((((((((xk[40] + -e_obj_nonlin_tunableEnvironment[0] * xk[30])
                         + -e_obj_nonlin_tunableEnvironment[8] * xk[31]) +
                        -e_obj_nonlin_tunableEnvironment[16] * xk[32]) +
                       -e_obj_nonlin_tunableEnvironment[24] * xk[33]) +
                      -e_obj_nonlin_tunableEnvironment[32] * xk[34]) +
                     -e_obj_nonlin_tunableEnvironment[40] * xk[35]) +
                    -e_obj_nonlin_tunableEnvironment[48] * xk[36]) +
                   -e_obj_nonlin_tunableEnvironment[56] * xk[37]) +
                  -f_obj_nonlin_tunableEnvironment[0] * xk[38]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[39];
    cEqPlus[5] = (((((((((xk[50] + -e_obj_nonlin_tunableEnvironment[0] * xk[40])
                         + -e_obj_nonlin_tunableEnvironment[8] * xk[41]) +
                        -e_obj_nonlin_tunableEnvironment[16] * xk[42]) +
                       -e_obj_nonlin_tunableEnvironment[24] * xk[43]) +
                      -e_obj_nonlin_tunableEnvironment[32] * xk[44]) +
                     -e_obj_nonlin_tunableEnvironment[40] * xk[45]) +
                    -e_obj_nonlin_tunableEnvironment[48] * xk[46]) +
                   -e_obj_nonlin_tunableEnvironment[56] * xk[47]) +
                  -f_obj_nonlin_tunableEnvironment[0] * xk[48]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[49];
    cEqPlus[6] = (((((((((xk[60] + -e_obj_nonlin_tunableEnvironment[0] * xk[50])
                         + -e_obj_nonlin_tunableEnvironment[8] * xk[51]) +
                        -e_obj_nonlin_tunableEnvironment[16] * xk[52]) +
                       -e_obj_nonlin_tunableEnvironment[24] * xk[53]) +
                      -e_obj_nonlin_tunableEnvironment[32] * xk[54]) +
                     -e_obj_nonlin_tunableEnvironment[40] * xk[55]) +
                    -e_obj_nonlin_tunableEnvironment[48] * xk[56]) +
                   -e_obj_nonlin_tunableEnvironment[56] * xk[57]) +
                  -f_obj_nonlin_tunableEnvironment[0] * xk[58]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[59];
    cEqPlus[7] = (((((((((xk[70] + -e_obj_nonlin_tunableEnvironment[0] * xk[60])
                         + -e_obj_nonlin_tunableEnvironment[8] * xk[61]) +
                        -e_obj_nonlin_tunableEnvironment[16] * xk[62]) +
                       -e_obj_nonlin_tunableEnvironment[24] * xk[63]) +
                      -e_obj_nonlin_tunableEnvironment[32] * xk[64]) +
                     -e_obj_nonlin_tunableEnvironment[40] * xk[65]) +
                    -e_obj_nonlin_tunableEnvironment[48] * xk[66]) +
                   -e_obj_nonlin_tunableEnvironment[56] * xk[67]) +
                  -f_obj_nonlin_tunableEnvironment[0] * xk[68]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[69];
    cEqPlus[8] = (((((((((xk[80] + -e_obj_nonlin_tunableEnvironment[0] * xk[70])
                         + -e_obj_nonlin_tunableEnvironment[8] * xk[71]) +
                        -e_obj_nonlin_tunableEnvironment[16] * xk[72]) +
                       -e_obj_nonlin_tunableEnvironment[24] * xk[73]) +
                      -e_obj_nonlin_tunableEnvironment[32] * xk[74]) +
                     -e_obj_nonlin_tunableEnvironment[40] * xk[75]) +
                    -e_obj_nonlin_tunableEnvironment[48] * xk[76]) +
                   -e_obj_nonlin_tunableEnvironment[56] * xk[77]) +
                  -f_obj_nonlin_tunableEnvironment[0] * xk[78]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[79];
    cEqPlus[9] = (((((((((xk[90] + -e_obj_nonlin_tunableEnvironment[0] * xk[80])
                         + -e_obj_nonlin_tunableEnvironment[8] * xk[81]) +
                        -e_obj_nonlin_tunableEnvironment[16] * xk[82]) +
                       -e_obj_nonlin_tunableEnvironment[24] * xk[83]) +
                      -e_obj_nonlin_tunableEnvironment[32] * xk[84]) +
                     -e_obj_nonlin_tunableEnvironment[40] * xk[85]) +
                    -e_obj_nonlin_tunableEnvironment[48] * xk[86]) +
                   -e_obj_nonlin_tunableEnvironment[56] * xk[87]) +
                  -f_obj_nonlin_tunableEnvironment[0] * xk[88]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[89];
    cEqPlus[10] = (((((((((xk[100] + -e_obj_nonlin_tunableEnvironment[0] * xk[90])
                          + -e_obj_nonlin_tunableEnvironment[8] * xk[91]) +
                         -e_obj_nonlin_tunableEnvironment[16] * xk[92]) +
                        -e_obj_nonlin_tunableEnvironment[24] * xk[93]) +
                       -e_obj_nonlin_tunableEnvironment[32] * xk[94]) +
                      -e_obj_nonlin_tunableEnvironment[40] * xk[95]) +
                     -e_obj_nonlin_tunableEnvironment[48] * xk[96]) +
                    -e_obj_nonlin_tunableEnvironment[56] * xk[97]) +
                   -f_obj_nonlin_tunableEnvironment[0] * xk[98]) +
      -f_obj_nonlin_tunableEnvironment[8] * xk[99];
    cEqPlus[11] = -c_obj_nonlin_tunableEnvironment[1] + xk[1];
    cEqPlus[12] = (((((((((xk[11] + -e_obj_nonlin_tunableEnvironment[1] * xk[0])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[1]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[2]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[3]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[4]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[5]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[6]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[7]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[8]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[9];
    cEqPlus[13] = (((((((((xk[21] + -e_obj_nonlin_tunableEnvironment[1] * xk[10])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[11]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[12]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[13]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[14]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[15]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[16]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[17]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[18]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[19];
    cEqPlus[14] = (((((((((xk[31] + -e_obj_nonlin_tunableEnvironment[1] * xk[20])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[21]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[22]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[23]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[24]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[25]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[26]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[27]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[28]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[29];
    cEqPlus[15] = (((((((((xk[41] + -e_obj_nonlin_tunableEnvironment[1] * xk[30])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[31]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[32]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[33]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[34]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[35]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[36]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[37]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[38]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[39];
    cEqPlus[16] = (((((((((xk[51] + -e_obj_nonlin_tunableEnvironment[1] * xk[40])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[41]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[42]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[43]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[44]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[45]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[46]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[47]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[48]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[49];
    cEqPlus[17] = (((((((((xk[61] + -e_obj_nonlin_tunableEnvironment[1] * xk[50])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[51]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[52]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[53]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[54]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[55]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[56]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[57]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[58]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[59];
    cEqPlus[18] = (((((((((xk[71] + -e_obj_nonlin_tunableEnvironment[1] * xk[60])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[61]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[62]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[63]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[64]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[65]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[66]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[67]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[68]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[69];
    cEqPlus[19] = (((((((((xk[81] + -e_obj_nonlin_tunableEnvironment[1] * xk[70])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[71]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[72]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[73]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[74]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[75]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[76]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[77]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[78]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[79];
    cEqPlus[20] = (((((((((xk[91] + -e_obj_nonlin_tunableEnvironment[1] * xk[80])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[81]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[82]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[83]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[84]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[85]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[86]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[87]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[88]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[89];
    cEqPlus[21] = (((((((((xk[101] + -e_obj_nonlin_tunableEnvironment[1] * xk[90])
                          + -e_obj_nonlin_tunableEnvironment[9] * xk[91]) +
                         -e_obj_nonlin_tunableEnvironment[17] * xk[92]) +
                        -e_obj_nonlin_tunableEnvironment[25] * xk[93]) +
                       -e_obj_nonlin_tunableEnvironment[33] * xk[94]) +
                      -e_obj_nonlin_tunableEnvironment[41] * xk[95]) +
                     -e_obj_nonlin_tunableEnvironment[49] * xk[96]) +
                    -e_obj_nonlin_tunableEnvironment[57] * xk[97]) +
                   -f_obj_nonlin_tunableEnvironment[1] * xk[98]) +
      -f_obj_nonlin_tunableEnvironment[9] * xk[99];
    cEqPlus[22] = -c_obj_nonlin_tunableEnvironment[2] + xk[2];
    cEqPlus[23] = (((((((((xk[12] + -e_obj_nonlin_tunableEnvironment[2] * xk[0])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[1]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[2]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[3]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[4]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[5]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[6]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[7]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[8]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[9];
    cEqPlus[24] = (((((((((xk[22] + -e_obj_nonlin_tunableEnvironment[2] * xk[10])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[11]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[12]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[13]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[14]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[15]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[16]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[17]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[18]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[19];
    cEqPlus[25] = (((((((((xk[32] + -e_obj_nonlin_tunableEnvironment[2] * xk[20])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[21]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[22]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[23]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[24]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[25]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[26]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[27]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[28]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[29];
    cEqPlus[26] = (((((((((xk[42] + -e_obj_nonlin_tunableEnvironment[2] * xk[30])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[31]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[32]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[33]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[34]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[35]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[36]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[37]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[38]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[39];
    cEqPlus[27] = (((((((((xk[52] + -e_obj_nonlin_tunableEnvironment[2] * xk[40])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[41]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[42]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[43]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[44]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[45]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[46]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[47]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[48]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[49];
    cEqPlus[28] = (((((((((xk[62] + -e_obj_nonlin_tunableEnvironment[2] * xk[50])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[51]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[52]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[53]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[54]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[55]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[56]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[57]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[58]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[59];
    cEqPlus[29] = (((((((((xk[72] + -e_obj_nonlin_tunableEnvironment[2] * xk[60])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[61]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[62]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[63]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[64]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[65]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[66]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[67]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[68]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[69];
    cEqPlus[30] = (((((((((xk[82] + -e_obj_nonlin_tunableEnvironment[2] * xk[70])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[71]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[72]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[73]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[74]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[75]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[76]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[77]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[78]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[79];
    cEqPlus[31] = (((((((((xk[92] + -e_obj_nonlin_tunableEnvironment[2] * xk[80])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[81]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[82]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[83]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[84]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[85]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[86]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[87]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[88]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[89];
    cEqPlus[32] = (((((((((xk[102] + -e_obj_nonlin_tunableEnvironment[2] * xk[90])
                          + -e_obj_nonlin_tunableEnvironment[10] * xk[91]) +
                         -e_obj_nonlin_tunableEnvironment[18] * xk[92]) +
                        -e_obj_nonlin_tunableEnvironment[26] * xk[93]) +
                       -e_obj_nonlin_tunableEnvironment[34] * xk[94]) +
                      -e_obj_nonlin_tunableEnvironment[42] * xk[95]) +
                     -e_obj_nonlin_tunableEnvironment[50] * xk[96]) +
                    -e_obj_nonlin_tunableEnvironment[58] * xk[97]) +
                   -f_obj_nonlin_tunableEnvironment[2] * xk[98]) +
      -f_obj_nonlin_tunableEnvironment[10] * xk[99];
    cEqPlus[33] = -c_obj_nonlin_tunableEnvironment[3] + xk[3];
    cEqPlus[34] = (((((((((xk[13] + -e_obj_nonlin_tunableEnvironment[3] * xk[0])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[1]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[2]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[3]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[4]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[5]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[6]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[7]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[8]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[9];
    cEqPlus[35] = (((((((((xk[23] + -e_obj_nonlin_tunableEnvironment[3] * xk[10])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[11]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[12]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[13]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[14]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[15]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[16]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[17]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[18]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[19];
    cEqPlus[36] = (((((((((xk[33] + -e_obj_nonlin_tunableEnvironment[3] * xk[20])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[21]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[22]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[23]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[24]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[25]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[26]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[27]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[28]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[29];
    cEqPlus[37] = (((((((((xk[43] + -e_obj_nonlin_tunableEnvironment[3] * xk[30])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[31]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[32]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[33]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[34]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[35]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[36]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[37]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[38]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[39];
    cEqPlus[38] = (((((((((xk[53] + -e_obj_nonlin_tunableEnvironment[3] * xk[40])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[41]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[42]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[43]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[44]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[45]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[46]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[47]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[48]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[49];
    cEqPlus[39] = (((((((((xk[63] + -e_obj_nonlin_tunableEnvironment[3] * xk[50])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[51]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[52]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[53]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[54]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[55]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[56]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[57]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[58]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[59];
    cEqPlus[40] = (((((((((xk[73] + -e_obj_nonlin_tunableEnvironment[3] * xk[60])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[61]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[62]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[63]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[64]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[65]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[66]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[67]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[68]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[69];
    cEqPlus[41] = (((((((((xk[83] + -e_obj_nonlin_tunableEnvironment[3] * xk[70])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[71]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[72]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[73]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[74]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[75]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[76]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[77]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[78]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[79];
    cEqPlus[42] = (((((((((xk[93] + -e_obj_nonlin_tunableEnvironment[3] * xk[80])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[81]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[82]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[83]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[84]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[85]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[86]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[87]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[88]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[89];
    cEqPlus[43] = (((((((((xk[103] + -e_obj_nonlin_tunableEnvironment[3] * xk[90])
                          + -e_obj_nonlin_tunableEnvironment[11] * xk[91]) +
                         -e_obj_nonlin_tunableEnvironment[19] * xk[92]) +
                        -e_obj_nonlin_tunableEnvironment[27] * xk[93]) +
                       -e_obj_nonlin_tunableEnvironment[35] * xk[94]) +
                      -e_obj_nonlin_tunableEnvironment[43] * xk[95]) +
                     -e_obj_nonlin_tunableEnvironment[51] * xk[96]) +
                    -e_obj_nonlin_tunableEnvironment[59] * xk[97]) +
                   -f_obj_nonlin_tunableEnvironment[3] * xk[98]) +
      -f_obj_nonlin_tunableEnvironment[11] * xk[99];
    cEqPlus[44] = -c_obj_nonlin_tunableEnvironment[4] + xk[4];
    cEqPlus[45] = (((((((((xk[14] + -e_obj_nonlin_tunableEnvironment[4] * xk[0])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[1]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[2]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[3]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[4]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[5]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[6]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[7]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[8]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[9];
    cEqPlus[46] = (((((((((xk[24] + -e_obj_nonlin_tunableEnvironment[4] * xk[10])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[11]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[12]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[13]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[14]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[15]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[16]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[17]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[18]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[19];
    cEqPlus[47] = (((((((((xk[34] + -e_obj_nonlin_tunableEnvironment[4] * xk[20])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[21]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[22]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[23]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[24]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[25]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[26]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[27]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[28]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[29];
    cEqPlus[48] = (((((((((xk[44] + -e_obj_nonlin_tunableEnvironment[4] * xk[30])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[31]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[32]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[33]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[34]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[35]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[36]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[37]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[38]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[39];
    cEqPlus[49] = (((((((((xk[54] + -e_obj_nonlin_tunableEnvironment[4] * xk[40])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[41]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[42]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[43]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[44]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[45]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[46]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[47]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[48]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[49];
    cEqPlus[50] = (((((((((xk[64] + -e_obj_nonlin_tunableEnvironment[4] * xk[50])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[51]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[52]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[53]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[54]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[55]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[56]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[57]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[58]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[59];
    cEqPlus[51] = (((((((((xk[74] + -e_obj_nonlin_tunableEnvironment[4] * xk[60])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[61]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[62]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[63]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[64]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[65]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[66]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[67]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[68]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[69];
    cEqPlus[52] = (((((((((xk[84] + -e_obj_nonlin_tunableEnvironment[4] * xk[70])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[71]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[72]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[73]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[74]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[75]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[76]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[77]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[78]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[79];
    cEqPlus[53] = (((((((((xk[94] + -e_obj_nonlin_tunableEnvironment[4] * xk[80])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[81]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[82]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[83]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[84]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[85]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[86]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[87]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[88]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[89];
    cEqPlus[54] = (((((((((xk[104] + -e_obj_nonlin_tunableEnvironment[4] * xk[90])
                          + -e_obj_nonlin_tunableEnvironment[12] * xk[91]) +
                         -e_obj_nonlin_tunableEnvironment[20] * xk[92]) +
                        -e_obj_nonlin_tunableEnvironment[28] * xk[93]) +
                       -e_obj_nonlin_tunableEnvironment[36] * xk[94]) +
                      -e_obj_nonlin_tunableEnvironment[44] * xk[95]) +
                     -e_obj_nonlin_tunableEnvironment[52] * xk[96]) +
                    -e_obj_nonlin_tunableEnvironment[60] * xk[97]) +
                   -f_obj_nonlin_tunableEnvironment[4] * xk[98]) +
      -f_obj_nonlin_tunableEnvironment[12] * xk[99];
    cEqPlus[55] = -c_obj_nonlin_tunableEnvironment[5] + xk[5];
    cEqPlus[56] = (((((((((xk[15] + -e_obj_nonlin_tunableEnvironment[5] * xk[0])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[1]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[2]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[3]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[4]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[5]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[6]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[7]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[8]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[9];
    cEqPlus[57] = (((((((((xk[25] + -e_obj_nonlin_tunableEnvironment[5] * xk[10])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[11]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[12]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[13]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[14]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[15]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[16]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[17]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[18]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[19];
    cEqPlus[58] = (((((((((xk[35] + -e_obj_nonlin_tunableEnvironment[5] * xk[20])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[21]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[22]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[23]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[24]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[25]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[26]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[27]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[28]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[29];
    cEqPlus[59] = (((((((((xk[45] + -e_obj_nonlin_tunableEnvironment[5] * xk[30])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[31]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[32]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[33]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[34]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[35]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[36]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[37]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[38]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[39];
    cEqPlus[60] = (((((((((xk[55] + -e_obj_nonlin_tunableEnvironment[5] * xk[40])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[41]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[42]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[43]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[44]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[45]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[46]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[47]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[48]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[49];
    cEqPlus[61] = (((((((((xk[65] + -e_obj_nonlin_tunableEnvironment[5] * xk[50])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[51]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[52]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[53]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[54]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[55]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[56]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[57]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[58]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[59];
    cEqPlus[62] = (((((((((xk[75] + -e_obj_nonlin_tunableEnvironment[5] * xk[60])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[61]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[62]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[63]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[64]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[65]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[66]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[67]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[68]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[69];
    cEqPlus[63] = (((((((((xk[85] + -e_obj_nonlin_tunableEnvironment[5] * xk[70])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[71]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[72]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[73]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[74]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[75]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[76]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[77]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[78]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[79];
    cEqPlus[64] = (((((((((xk[95] + -e_obj_nonlin_tunableEnvironment[5] * xk[80])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[81]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[82]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[83]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[84]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[85]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[86]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[87]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[88]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[89];
    cEqPlus[65] = (((((((((xk[105] + -e_obj_nonlin_tunableEnvironment[5] * xk[90])
                          + -e_obj_nonlin_tunableEnvironment[13] * xk[91]) +
                         -e_obj_nonlin_tunableEnvironment[21] * xk[92]) +
                        -e_obj_nonlin_tunableEnvironment[29] * xk[93]) +
                       -e_obj_nonlin_tunableEnvironment[37] * xk[94]) +
                      -e_obj_nonlin_tunableEnvironment[45] * xk[95]) +
                     -e_obj_nonlin_tunableEnvironment[53] * xk[96]) +
                    -e_obj_nonlin_tunableEnvironment[61] * xk[97]) +
                   -f_obj_nonlin_tunableEnvironment[5] * xk[98]) +
      -f_obj_nonlin_tunableEnvironment[13] * xk[99];
    cEqPlus[66] = -c_obj_nonlin_tunableEnvironment[6] + xk[6];
    cEqPlus[67] = (((((((((xk[16] + -e_obj_nonlin_tunableEnvironment[6] * xk[0])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[1]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[2]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[3]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[4]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[5]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[6]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[7]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[8]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[9];
    cEqPlus[68] = (((((((((xk[26] + -e_obj_nonlin_tunableEnvironment[6] * xk[10])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[11]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[12]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[13]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[14]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[15]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[16]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[17]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[18]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[19];
    cEqPlus[69] = (((((((((xk[36] + -e_obj_nonlin_tunableEnvironment[6] * xk[20])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[21]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[22]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[23]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[24]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[25]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[26]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[27]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[28]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[29];
    cEqPlus[70] = (((((((((xk[46] + -e_obj_nonlin_tunableEnvironment[6] * xk[30])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[31]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[32]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[33]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[34]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[35]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[36]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[37]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[38]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[39];
    cEqPlus[71] = (((((((((xk[56] + -e_obj_nonlin_tunableEnvironment[6] * xk[40])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[41]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[42]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[43]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[44]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[45]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[46]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[47]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[48]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[49];
    cEqPlus[72] = (((((((((xk[66] + -e_obj_nonlin_tunableEnvironment[6] * xk[50])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[51]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[52]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[53]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[54]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[55]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[56]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[57]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[58]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[59];
    cEqPlus[73] = (((((((((xk[76] + -e_obj_nonlin_tunableEnvironment[6] * xk[60])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[61]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[62]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[63]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[64]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[65]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[66]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[67]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[68]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[69];
    cEqPlus[74] = (((((((((xk[86] + -e_obj_nonlin_tunableEnvironment[6] * xk[70])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[71]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[72]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[73]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[74]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[75]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[76]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[77]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[78]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[79];
    cEqPlus[75] = (((((((((xk[96] + -e_obj_nonlin_tunableEnvironment[6] * xk[80])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[81]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[82]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[83]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[84]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[85]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[86]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[87]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[88]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[89];
    cEqPlus[76] = (((((((((xk[106] + -e_obj_nonlin_tunableEnvironment[6] * xk[90])
                          + -e_obj_nonlin_tunableEnvironment[14] * xk[91]) +
                         -e_obj_nonlin_tunableEnvironment[22] * xk[92]) +
                        -e_obj_nonlin_tunableEnvironment[30] * xk[93]) +
                       -e_obj_nonlin_tunableEnvironment[38] * xk[94]) +
                      -e_obj_nonlin_tunableEnvironment[46] * xk[95]) +
                     -e_obj_nonlin_tunableEnvironment[54] * xk[96]) +
                    -e_obj_nonlin_tunableEnvironment[62] * xk[97]) +
                   -f_obj_nonlin_tunableEnvironment[6] * xk[98]) +
      -f_obj_nonlin_tunableEnvironment[14] * xk[99];
    cEqPlus[77] = -c_obj_nonlin_tunableEnvironment[7] + xk[7];
    cEqPlus[78] = (((((((((xk[17] + -e_obj_nonlin_tunableEnvironment[7] * xk[0])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[1]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[2]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[3]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[4]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[5]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[6]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[7]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[8]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[9];
    cEqPlus[79] = (((((((((xk[27] + -e_obj_nonlin_tunableEnvironment[7] * xk[10])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[11]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[12]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[13]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[14]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[15]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[16]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[17]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[18]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[19];
    cEqPlus[80] = (((((((((xk[37] + -e_obj_nonlin_tunableEnvironment[7] * xk[20])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[21]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[22]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[23]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[24]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[25]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[26]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[27]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[28]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[29];
    cEqPlus[81] = (((((((((xk[47] + -e_obj_nonlin_tunableEnvironment[7] * xk[30])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[31]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[32]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[33]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[34]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[35]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[36]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[37]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[38]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[39];
    cEqPlus[82] = (((((((((xk[57] + -e_obj_nonlin_tunableEnvironment[7] * xk[40])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[41]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[42]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[43]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[44]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[45]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[46]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[47]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[48]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[49];
    cEqPlus[83] = (((((((((xk[67] + -e_obj_nonlin_tunableEnvironment[7] * xk[50])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[51]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[52]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[53]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[54]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[55]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[56]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[57]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[58]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[59];
    cEqPlus[84] = (((((((((xk[77] + -e_obj_nonlin_tunableEnvironment[7] * xk[60])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[61]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[62]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[63]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[64]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[65]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[66]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[67]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[68]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[69];
    cEqPlus[85] = (((((((((xk[87] + -e_obj_nonlin_tunableEnvironment[7] * xk[70])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[71]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[72]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[73]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[74]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[75]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[76]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[77]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[78]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[79];
    cEqPlus[86] = (((((((((xk[97] + -e_obj_nonlin_tunableEnvironment[7] * xk[80])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[81]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[82]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[83]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[84]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[85]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[86]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[87]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[88]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[89];
    cEqPlus[87] = (((((((((xk[107] + -e_obj_nonlin_tunableEnvironment[7] * xk[90])
                          + -e_obj_nonlin_tunableEnvironment[15] * xk[91]) +
                         -e_obj_nonlin_tunableEnvironment[23] * xk[92]) +
                        -e_obj_nonlin_tunableEnvironment[31] * xk[93]) +
                       -e_obj_nonlin_tunableEnvironment[39] * xk[94]) +
                      -e_obj_nonlin_tunableEnvironment[47] * xk[95]) +
                     -e_obj_nonlin_tunableEnvironment[55] * xk[96]) +
                    -e_obj_nonlin_tunableEnvironment[63] * xk[97]) +
                   -f_obj_nonlin_tunableEnvironment[7] * xk[98]) +
      -f_obj_nonlin_tunableEnvironment[15] * xk[99];
    memcpy(&cIneqPlus[0], &varargout_1[0], 20U * sizeof(real_T));
    idx = 0;
    while (evalOK && (idx + 1 <= 20)) {
      evalOK = ((!muDoubleScalarIsInf(cIneqPlus[idx])) && (!muDoubleScalarIsNaN
                 (cIneqPlus[idx])));
      idx++;
    }

    if (evalOK) {
      idx = 0;
      while (evalOK && (idx + 1 <= 88)) {
        evalOK = ((!muDoubleScalarIsInf(cEqPlus[idx])) && (!muDoubleScalarIsNaN
                   (cEqPlus[idx])));
        idx++;
      }

      xk[dim - 1] = temp_tmp;
    }
  }

  return evalOK;
}

/* End of code generation (finDiffEvalAndChkErr.c) */
